docs/programming_guide.md

* Explicit syntax highlighting for code blocks
* Fix indentation for nested list

Tweak markdown in programing_guide.md.

---

sharktank/sharktank/models/llama/llama.py
sharktank/sharktank/types/theta.py
sharktank/sharktank/utils/hf_datasets.py

* I had a NYI assert for GQA. Fixes that.
* Just grabs some pre-made weights of unknown providence to test for gross correctness.

[llama3] Enable a llama3 model.

---

sharktank/sharktank/utils/hf_datasets.py

* Model from https://huggingface.co/TheBloke/Mistral-7B-v0.1-GGUF
* Tokenizer from https://huggingface.co/TheBloke/Mistral-7B-v0.1-GPTQ
This works on my machine:
```
python -m sharktank.examples.paged_llm_v1 --hf-dataset=mistral_7b_q8_0_gguf "1, 2, 3, 4"
:: Prompting:
b'1, 2, 3, 4'
:: Prompt tokens: tensor([[    1, 28705, 28740, 28725, 28705, 28750, 28725, 28705, 28770, 28725,
28705, 28781,     0,     0,     0,     0]])
:: Invoke prefill:
:: Prefill results:
[[28725]]
[',']
:: Result tokens: [[28725, 28705]]
0(2, 13): ,
:: Result tokens: [[28725, 28705, 28782]]
0(3, 14): , 5
:: Result tokens: [[28725, 28705, 28782, 28725]]
0(4, 15): , 5,
:: Result tokens: [[28725, 28705, 28782, 28725, 28705]]
0(5, 16): , 5, 
:: Result tokens: [[28725, 28705, 28782, 28725, 28705, 28784]]
0(6, 17): , 5, 6 …
```

Add a few mistral/mixtral datasets to hf_datasets.py.

---

docs/model_cookbook.md

* Add some helpful links
* Document `--hf-dataset`
* Add context for formats with sample links

Expand on notes in model_cookbook.md.

---

shortfin/tests/llm/api_server_test.py

The test was failing with `ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use` (https://github.com/nod-ai/sharktank/actions/runs/8944166670/job/24570503674?pr=16#step:7:1330). Some other process on the test runner may be using port 8000, so this attempts to find a free port before starting the server.

Try de-flaking api_server_test.

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/utils/math.py
sharktank/tests/ops/sharded_test.py

* Sharding of output channel dimension of conv2d with a single group.
* Sharding by groups in group normalization.
* Sharding of non-normalization dimension in layer norm.

Add sharding of conv2d, group norm and layer norm

---

sharktank/sharktank/ops/__init__.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/qconv_impls.py
sharktank/sharktank/ops/qlinear_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/tests/ops/qconv_test.py

Leaving one case failing. Issue logged: #55

Add linear quantized conv layer.

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/types/tensors_test.py

Introduces a sharded tensor type that needs to be reduced over the shards to get the actual tensor.
Make matmul produce such a tensor in one case.

Add shareded unreduced tensor type

---

sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py

This eliminates the use of mixed signedness mm/conv by shifting the weight zero point to use signed i8 values. Note that this only requires changing the brevitas import script as the rest of the tooling just responds to the type change.

[punet] Switch weight quantization to signed.

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/sharded_test.py

* Sharded parallel dimensions for RHS and LHS.
* Sharded LHS and replicated RHS.
* Sharded LHS.

Add a few cases of sharded matmul

---

sharktank/sharktank/types/tensors.py
sharktank/tests/types/tensors_test.py

* Slicing of replicated tensor.
* Slicing of split tensor, when not slicing the split dimension.

Add some slicing cases for sharded tensors

---

docs/amdgpu_kernel_optimization_guide.md

Based on https://gpuopen.com/learn/amd-lab-notes/amd-lab-notes-register-pressure-readme/

Update VGPR info in the kernel optimization guide

---

sharktank/sharktank/ops/__init__.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/tests/ops/sharded_test.py

Add fully replicated case.
Add split batch or channel dimensions.

Add sharded interpolate

---

sharktank/sharktank/ops/qlinear_impls.py

Was reversed. This works better with the bmm mixed precision op which conceptually does an internal ext.

[quant] When broadcasting the weight of a bmm, broadcast then ext.

---

.github/workflows/test.yaml
pytorch-rocm-requirements.txt
sharktank/sharktank/models/punet/README.md

Sample run (with failures): https://github.com/nod-ai/sharktank/actions/runs/9752141473/job/26915109873
Definitely room for improvement, but it's a start.
Progress on https://github.com/nod-ai/sharktank/issues/76

Add CI job for punet tests, running nightly.

---

sharktank/integration/models/punet/integration_test.py

These are currently failing: https://github.com/nod-ai/sharktank/actions/runs/9752141473. We'll be validating numerics/accuracy soon.
Test run triggered: https://github.com/nod-ai/sharktank/actions/runs/9752992626

Comment out punet golden checks until accuracy is validated.

---

sharktank/integration/models/punet/integration_test.py
sharktank/sharktank/models/punet/README.md
sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py
sharktank/sharktank/models/punet/tools/run_diffuser_ref.py
sharktank/sharktank/models/punet/tools/run_punet.py
sharktank/sharktank/models/punet/tools/sample_data.py
sharktank/sharktank/tools/compare_safetensors.py
sharktank/sharktank/utils/patching.py

* File renamed to quant_params.json (plural).
* Zero points now have a `{name}_dtype` field and are properly signed/unsigned vs requiring us to manually offset.

[punet] Adapt to brevitas quant_params.json change.

---

sharktank/setup.py
sharktank/sharktank/kernels/__init__.py

Fixes so that when sharktank tools are used in other repos (SHARK-Turbine), it works as intended.

Minor packaging fixes

---

sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py

These were just some bug fixes from never getting this combination before.

[punet] Generalize the brevitas importer slightly to handle symmetric quant.

---

sharktank/sharktank/kernels/__init__.py
sharktank/sharktank/kernels/attention.py
sharktank/sharktank/kernels/templates/flash_attention.mlir
sharktank/sharktank/models/punet/layers.py
sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py
sharktank/sharktank/ops/__init__.py
sharktank/sharktank/ops/attention_impls.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/layouts.py

Setup the framework for invoking flash attention when available

Flash Attention invocation

---

sharktank/sharktank/examples/paged_llm_v1.py

adds support for saving intermediate outputs in llama

---

sharktank/sharktank/kernels/templates/flash_attention.mlir
sharktank/sharktank/models/punet/layers.py
sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py

Each of q, k, and v may use slightly different quantization parameters. Update the import / modeling tooling to import the new quantization parameters.

Switch fp8 attention to proper quantization

---

sharktank/sharktank/layers/rotary_embedding.py
sharktank/sharktank/models/llama/llama.py
sharktank/sharktank/models/llama/testing.py
sharktank/tests/models/llama/attention_test.py

Created an FP32 test to verify and compare the numerical outputs of sharktank's PagedLlamaAttentionBlock and HuggingFace's equivalent LlamaDecoderLayer. Expects, given random weights and inputs, exact equality.
Enjoy!

Llama Testing

---

sharktank/sharktank/types/tensors.py
sharktank/tests/models/punet/conftest.py
sharktank/tests/models/punet/sharded_resnet_block_with_iree_test.py

The test targets llvm-cpu with the local-task IREE driver.

Add test that shards, exports and runs with IREE a Unet Resnet block

---

docs/amdgpu_kernel_optimization_guide.md

Specify the exact threads participating in concurrent LDS accesses

[docs] Update LDS information

---

.github/workflows/ci_linux_x64-libshortfin.yml
libshortfin/pyproject.toml
libshortfin/requirements-tests.txt
libshortfin/tests/examples/fastapi_test.py

Lists and installs the missing test deps and removes the expected fail marking.

[libshortfin] Allow tests to pass

---

tuner/examples/punet/README.md
tuner/examples/punet/__main__.py
tuner/examples/punet/punet_autotune.py

Issue: https://github.com/nod-ai/sharktank/issues/160

[tuner] Use __main__.py for punet tuner example

---

sharktank/sharktank/layers/paged_llama_attention_block.py

fixes bs1/direct cache exports.

replaces some logic with index ops

---

libshortfin/tests/examples/async_test.py

[libshortfin] Dynamically skip certain flaky tests with a message.

---

libshortfin/CMakeLists.txt

LSP relying on clangd needs this

[libshortfin] Add CMAKE_EXPORT_COMPILE_COMMANDS to CMakeLists.txt

---

libshortfin/python/array_binding.cc
libshortfin/src/shortfin/array/array.cc
libshortfin/src/shortfin/array/array.h
libshortfin/tests/api/array_test.py

Currently only restricted to row-major dense array views.

[libshortfin] Add device_array.view

---

libshortfin/python/lib_ext.cc
libshortfin/python/shortfin/interop/support/logging_setup.py
libshortfin/src/shortfin/support/logging.cc

This patch moves logging functions from
https://github.com/nod-ai/sharktank/pull/181

[libshortfin] Move the logging setup

---

libshortfin/.readthedocs.yaml

This adds a configuration for Read the Docs.

[libshortfin] Add a .readthedocs.yaml

---

libshortfin/docs/conf.py
libshortfin/docs/reference.rst
libshortfin/python/array_binding.cc

Auto-docs further members and classes for which docstrings are present.

[libshortfin] Add additional auto documentation

---

.github/workflows/build_packages.yml

Progress on https://github.com/nod-ai/SHARK-Platform/issues/130.
* Successful run: https://github.com/nod-ai/SHARK-Platform/actions/runs/11147915256
* Dev wheels release: https://github.com/nod-ai/SHARK-Platform/releases/tag/dev-wheels
* Install with `python -m pip install shortfin -f https://github.com/nod-ai/SHARK-Platform/releases/expanded_assets/dev-wheels`

Add new access token for release publishing.

---

sharktank/sharktank/examples/paged_llm_v1.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/utils/hf_datasets.py
sharktank/tests/models/llama/llama_cpp_instructions.md
sharktank/tests/models/llama/prefill_tests.py

Paged and direct kv cache prefill tests for llama 2 7b and llama 3.1 8b.

Prefill tests for llama 2 7b and llama 3.1 8b

---

tuner/candidate_gen.py
tuner/candidate_gen_test.py

Update to the new syntax used by IREE.

[tuner] Update mfma intrinsic syntax

---

tuner/tuner/candidate_gen.py

Follow up to https://github.com/nod-ai/SHARK-Platform/pull/249 where I missed this

[tuner] Also update mfma class to match new format

---

tuner/tuner/candidate_gen.py

[tuner] Fixes for python 3.12

---

.github/workflows/ci_linux_x64-libshortfin.yml
.github/workflows/ci_linux_x64_nogil-libshortfin.yml

* Removes extra path from command line
* Adds quotes to make call compatible with Windows CI
* Removes no longer required deps

Cleanup workflow files

---

tuner/tuner/candidate_gen.py
tuner/tuner/candidate_gen_test.py

Use the attribute format introduced in
https://github.com/iree-org/iree/pull/18458.
Fixes: https://github.com/nod-ai/SHARK-Platform/issues/186

[tuner] Update gpu pipeline option handling

---

.github/workflows/ci_eval.yaml
.github/workflows/test.yaml
sharktank/conftest.py
sharktank/sharktank/evaluate/perplexity.py
sharktank/tests/evaluate/perplexity_test.py

Fix Evaluation CI failure

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/layers/causal_llm.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/llama/llama.py
sharktank/sharktank/models/llama/tools/shard_llama.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/tests/models/llama/sharded_llama_test.py

This include some minor fixes for exporting llama style LLMs

Finish end-to-end sharded workflow

---

.github/workflows/ci_linux_x64_nogil-libshortfin.yml
shortfin/requirements-tests-nogil.txt
shortfin/tests/apps/llm/components/cache_test.py
shortfin/tests/apps/llm/test_llm_server.py

Also reorganizes server test to test multiple batch sizes.

Add simple cache unit test and move server test to proper location

---

shortfin/python/shortfin_apps/sd/README.md
shortfin/python/shortfin_apps/sd/components/generate.py
shortfin/python/shortfin_apps/sd/components/io_struct.py
shortfin/python/shortfin_apps/sd/components/manager.py
shortfin/python/shortfin_apps/sd/components/messages.py
shortfin/python/shortfin_apps/sd/components/service.py
shortfin/python/shortfin_apps/sd/examples/sdxl_request.json
shortfin/python/shortfin_apps/sd/examples/sdxl_request_bs8.json
shortfin/python/shortfin_apps/sd/server.py

This change also includes an update to the README for the SD server.
The motivation behind this patch is to enable pipelining efforts and keep execution seamless and linear. It also makes the batcher actually work, instead of just letting any requests batch with a prayer for density in program config / invocation parameters.
It also:
- pipes through a simple option for specifying device indices 
- cleans up a bit of the client generation request struct.
- adds a bs8 example request.

(shortfin-apps)(sd) Rework batching and structuring of image generation requests.

---

shortfin/tests/apps/llm/cpu_llm_server_test.py

Add skip statements for cases where requirements-test.txt is not installed

Fix LLM Server Failing CIs

---

shortfin/tests/apps/llm/cpu_llm_server_test.py

Reverts nod-ai/SHARK-Platform#362

Revert "Fix LLM Server Failing CIs"

---

.github/workflows/ci-llama.yaml
sharktank/conftest.py
sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/models/llama/tools/shard_llama.py
sharktank/sharktank/utils/export_artifacts.py
sharktank/tests/models/llama/benchmark_amdgpu_test.py
sharktank/tests/models/llama/benchmark_amdgpu_tests.py

Modify all the changes merged into the sharktank repo to make Llama Benchmarking test work.

Fix Llama Benchmarking 8b f16 tests to run on presubmit

---

docs/nightly_releases.md

Progress on https://github.com/nod-ai/SHARK-Platform/issues/130 and https://github.com/nod-ai/SHARK-Platform/issues/294 . These developer docs can also be considered a draft for user docs (https://github.com/nod-ai/SHARK-Platform/issues/359).

[packaging] Add developer doc for working with nightly releases.

---

.github/workflows/ci_eval.yaml
sharktank/README.md
sharktank/sharktank/evaluate/README.md

Add nightly Perplexity CI workflow's status badge to sharktank's README

[sharktank] Add Perplexity updates to README

---

.github/workflows/ci-sdxl.yaml

fixes https://github.com/nod-ai/SHARK-Platform/issues/407

(ci-sdxl) check for apt dependencies before installing

---

sharktank/sharktank/models/llama/llama.py

Reverts nod-ai/SHARK-Platform#353

Revert "temporary decompose for decode"

---

shortfin/docs/reference.rst

Autogenerate documentation for further classes, members and functions.

[shortfin] Expand autodoc documentation

---

.github/workflows/ci-sdxl.yaml
.github/workflows/ci_linux_x64-libshortfin.yml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
.github/workflows/ci_linux_x64_nogil-libshortfin.yml
.github/workflows/ci_windows_x64-libshortfin.yml
shortfin/CMakeLists.txt
shortfin/requirements-iree-compiler.txt
shortfin/src/shortfin/local/scheduler.cc

Required for iree.build compile action. (https://github.com/nod-ai/SHARK-Platform/pull/427)

(shortfin) Bump IREE to candidate-20241104.1068

---

shortfin/python/_shortfin/asyncio_bridge.py
shortfin/python/shortfin_apps/sd/server.py

With this unit tests appear to pass (I'm on a system with other issues but appear unrelated).

[shortfin] Fix some issues blocking operation on Python 3.10.

---

tuner/pyproject.toml
tuner/setup.py
tuner/tuner/candidate_gen.py
tuner/tuner/candidate_gen_test.py
tuner/version.json

* Pass context explicitly to the parse function
* Fix mypy typing violations
* Add pyproject.toml

[tuner] Clean up candidate generation code

---

tuner/tuner/libtuner.py
tuner/tuner/libtuner_test.py

Make libtuner and its test type-check with mypy.

[tuner] Fix typing issues in libtuner. NFC.

---

.github/workflows/ci-tuner.yml
tuner/requirements-dev.txt

For now only typecheck the tuner implementation. In the future, we should extend it to examples.

[tuner][CI] Enable mypy type checking

---

README.md
tuner/README.md

Add a warning about the tuner being in early development. Update the tuner readme and remove obsolete instructions.

[tuner] Update README

---

sharktank/version.json
shortfin/version.json
tuner/version.json

Still working out the details for release process / branching.
Planned next steps:
1. Merge this
2. Trigger https://github.com/nod-ai/shark-ai/actions/workflows/build_packages.yml to build 2.9.2
3. Delete 3.0.0 wheels from https://github.com/nod-ai/shark-ai/releases/tag/dev-wheels
4. Push 2.9.2 to PyPI
5. Revert this PR to get the version back to 3.0.0

Downgrade version to 2.9.2 to push a patch release.

---

README.md

Small change here to make user documentation more prominent and remove the notice on the WIP banner (though it is ever true). If there are other small touch ups on this page we want to clean up, feel free to comment or submit a patch.

Small change to clean up main page for release

---

docs/nightly_releases.md
docs/user_guide.md

Hopefully this helps with issues like https://github.com/nod-ai/shark-ai/issues/544

Update documentation for using nightly releases.

---

shortfin/python/shortfin_apps/llm/components/generate.py
shortfin/python/shortfin_apps/llm/components/service.py

This is required for kvcache sharing.

Give InferenceExecRequest full token context

---

docs/developer_guide.md

[skip ci]
Clicked merge before some of #575 's comments showed up.

Fix some linux developer_guide.md comments that didn't show up at time of merge

---

shortfin/python/shortfin_apps/llm/server.py

In troubleshooting tests, I realized that we weren't getting any logging output from the server, which used to happen. Realized that shortfin LLM server wasn't logging output. Copied over the UVICORN_CONFIG from sdxl, which seems to fix the problem.

Fix logging for shortfin LLM server

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
sharktank/sharktank/utils/export_artifacts.py
sharktank/tests/models/llama/benchmark_amdgpu_test.py

Use iree_device to run tests on different hip devices to avoid conflict/queue times

Use iree_device to run tests on different hip devices to avoid conflict/queue times

---

.github/workflows/ci-sglang-benchmark.yml
.github/workflows/ci-sglang-integration-tests.yml
.github/workflows/ci-shark-ai.yml
.github/workflows/ci-sharktank.yml
.github/workflows/ci_eval.yaml

Missed these as part of https://github.com/nod-ai/shark-ai/pull/639 (too many workflows :dizzy_face: )

Move additional actions/checkout steps to job start.

---

sharktank/tests/models/llama/benchmark_amdgpu_test.py

Add test for llama 3.1 8b f16 non-decomposed prefill bs4 tp1 for input len 2048.

Add input len 2048 test for bs4 tp1 8b f16 non-decomposed prefill

---

shortfin/python/shortfin_apps/llm/components/service.py

Fix gibberish token problem for prefill also

---

tuner/examples/simple/README.md
tuner/examples/simple/compile_flags.txt
tuner/examples/simple/model_benchmark_flags.txt
tuner/examples/simple/simple_tuner.py

This generalizes the simple tuner such that it can be used for real-world models without having to modify the python code.

[Tuner] Add support for flag files in the simple tuner

---

sharktank/README.md

Update perplexity status badge to reflect latest run on main branch [here](https://github.com/nod-ai/shark-ai/tree/main/sharktank#project-status).

[sharktank] Update perplexity status badge

---

tuner/tuner/candidate_gen.py

- removed unused function `apply_params`
- removed unused function `validate translation`

[tuner] clean up candidate gen

---

tuner/tuner/libtuner.py

[Tuner] Fix handling of compilation failures

---

sharktank/requirements-tests.txt
sharktank/sharktank/layers/mmdit.py
sharktank/sharktank/layers/testing.py
sharktank/sharktank/models/flux/export.py
sharktank/sharktank/models/flux/flux.py
sharktank/sharktank/models/flux/testing.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/tests/layers/mmdit_test.py
sharktank/tests/models/flux/flux_test.py

* Fix layer norm to use the correct normalized_shape.
* Fix attention to not be causal.
* Make GELU use Tanh approximation.
Add tests that compare eager bf16 and f32 against Huggging Face's transformer.

Fix Flux transformer numerics and add test comparing eager against Hugging Face

---

app_tests/integration_tests/llm/shortfin/conftest.py
app_tests/integration_tests/llm/shortfin/cpu_llm_server_test.py
sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/kernels/__init__.py
sharktank/sharktank/kernels/rotary.py
sharktank/sharktank/kernels/templates/rotary_embedding.mlir
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/layers/rotary_embedding.py
sharktank/sharktank/models/llama/llama.py
sharktank/tests/evaluate/perplexity_iree_test.py
sharktank/tests/kernels/rotary.py

This reverts commit 63ff841c83afb6b2474b8a456d870ea0f755c169.
Our [user docs](https://github.com/nod-ai/shark-ai/blob/main/docs/shortfin/llm/user/llama_serving.md) started producing repetitive output:
```bash
curl http://localhost:8003/generate \
-H "Content-Type: application/json" \
-d '{
"text": "Name the capital of the United States.",
"sampling_params": {"max_completion_tokens": 50}
}'
data:  Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington
```
After bisecting, the problematic commit was found to be 63ff841c83afb6b2474b8a456d870ea0f755c169.
Without commit reverted:
```bash
curl http://localhost:8003/generate \
-H "Content-Type: application/json" …
```

Revert "[sharktank] Revert "[llama] Added the fused rotary embedding kernel (#719)" (#752)"

---

tuner/examples/simple/simple_tuner.py
tuner/tuner/candidate_gen.py
tuner/tuner/libtuner.py
tuner/tuner/libtuner_test.py

- Fix mypy warning issues.
- remove unused parameter for benchmark function.
- remove unused import.

[tuner] clean up the code. NFC.

---

sharktank/tests/models/flux/flux_test.py

Remove the single layer with random weights test in favor for the pretrained Dev model variant.
We test IREE f32 and bf16 against eager f32.
The particular initialization parameters for the random values caused large intermediate values during execution, which deteriorated the model output.
The pretrained variant does not suffer from this problem and the numerical error looks reasonable.

Add flux transformer Dev test with IREE

---

docs/shortfin/llm/user/llama_serving.md

See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

Fix markdown note syntax in llama_serving.md.

---

sharktank/sharktank/evaluate/perplexity_iree.py
sharktank/sharktank/evaluate/perplexity_torch.py
sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/examples/paged_llm_v1.py
sharktank/sharktank/export_layer/export_paged_attention.py
sharktank/sharktank/utils/cli.py
sharktank/sharktank/utils/load_llm.py
sharktank/tests/evaluate/perplexity_iree_test.py

- Update DirectKVCache changes from #854 to fix failing torch perplexity CI
- Update flags to align with #860

[sharktank] Update Directkvcache removal to fix CI tests and update model flags

---

sharktank/tests/models/llama/benchmark_amdgpu_test.py

Update model path to fix Llama Benchmark CI after re-organizing artifacts on CI machine

[sharktank] Update model path to fix Llama Benchmark CI

---

sharktank/requirements.txt
sharktank/sharktank/layers/rotary_embedding.py
sharktank/tests/models/llama/attention_test.py
sharktank/tests/models/llama/rot_emb_test.py
sharktank/tests/models/t5/t5_test.py

[sharktank][llama] Adds parity to hf's rotary_embedding layer and a test to maintain it

---

.github/workflows/pkgci_shark_ai.yml

Simplify pkgci_shark_ai workflow using wildcard downloads

---

app_tests/benchmark_tests/llm/sglang_benchmarks/conftest.py
app_tests/benchmark_tests/llm/sglang_benchmarks/sglang_benchmark_test.py
app_tests/benchmark_tests/llm/sglang_benchmarks/shortfin_benchmark_test.py
app_tests/integration_tests/llm/logging_utils.py
app_tests/integration_tests/llm/model_management.py
app_tests/integration_tests/llm/server_management.py
app_tests/integration_tests/llm/sglang/conftest.py
app_tests/integration_tests/llm/sglang/sglang_frontend_test.py
app_tests/integration_tests/llm/shortfin/conftest.py
app_tests/integration_tests/llm/utils.py

This is a continuation of #728 .
Next step: make hf download share the hf dataset download code in sharktank and make sure caching works.

Make sglang tests use `model_management.py` and `server_management.py`

---

docs/shortfin/llm/user/llama_serving.md

Small update. This just makes the `overview` items links, which improves the ability to navigate our doc for different sections.

Make overview navigable

---

sharktank/sharktank/models/vae/model.py
sharktank/sharktank/pipelines/flux/export_components.py
sharktank/sharktank/tools/import_hf_dataset.py
sharktank/tests/models/vae/vae_test.py

Fixes data dependent test failures from VAE

Some dtype fixes for vae tests

---

.github/workflows/update_iree_requirement_pins.yml

Address Scott's comment in #973

[iree auto bump workflow] Put the bumped-to version in pr title

---

sharktank/tests/models/vae/vae_test.py

[sharktank] Fix VAE string formatting in tests

---

shortfin/python/shortfin_apps/sd/server.py

Clarify the format of device IDs.

[sd] Clean up server flags. NFC.

---

sharktank/tests/models/deepseek/test_deepseek.py
sharktank/tests/models/llama/test_llama.py

Add xfail to toy llama and deepseek tests

---

sharktank/sharktank/ops/sharded_impls.py

Same idea as #957. Reduce amount of copying and speed up execution since copies can't happening in parallel.

Speed-up all_gather by reducing buffer copies.

---

shortfin/python/shortfin/interop/fastapi/__init__.py
shortfin/python/shortfin/support/responder.py
shortfin/python/shortfin_apps/llm/cli.py
shortfin/python/shortfin_apps/llm/server.py

For testing purposes its easier to invoke a single CLI that can batch run values. This can be reworked to include benchmarking the throughput and batch processing local files.

Add CLI client for shortfin LLM server

---

sharktank/sharktank/models/punet/README.md

[sharktank][docs] update path

---

docs/shortfin/llm/user/llama_serving.md

- Update support table to include Mistral-Nemo-12B
- Update docs to mention `Llama` and `Llama-Like` models
- Update server arguments
Basic update to the support table, and some wording to highlight that we support `Llama` and `Llama-Like` models.
Recently learned of some smaller Mistral models that we may have support for as well. Will look at them today, and make subsequent updates/PRs.

`Llama_serving` 3.3 updates

---

.github/workflows/ci-sharktank-nightly.yml
.github/workflows/ci-sharktank.yml
sharktank/conftest.py
sharktank/pyproject.toml
sharktank/sharktank/utils/testing.py
sharktank/tests/models/clip/clip_test.py
sharktank/tests/models/flux/flux_test.py

Since there are toy sized model tests for these models, we could run tests with the actual model less often.

[sharktank] move expensive Flux transformer and Clip tests to nightly CI

---

shortfin/python/shortfin_apps/flux/README.md

If you follow the current documentation you will be missing some dependencies. This can be solved by following the developer guide.

Update the flux environment documentation

---

sharktank/sharktank/torch_exports/sdxl/unet.py
shortfin/python/shortfin_apps/sd/components/builders.py
shortfin/python/shortfin_apps/sd/components/exports.py
shortfin/python/shortfin_apps/sd/components/generate.py
shortfin/python/shortfin_apps/sd/python_pipe.py
shortfin/python/shortfin_apps/sd/server.py
shortfin/python/shortfin_apps/sd/simple_client.py

Clean up unused imports, including fastapi that blocks gil-free shortfin harness.

Clean up import for sd

---

sharktank/version.json
shortfin/version.json
tuner/version.json

Release tracker: https://github.com/iree-org/iree/issues/19960

Bump version to 3.4.0 after 3.3.0 release.

---

shortfin/tests/apps/llm/components/kvcache/base_attention_cache_test.py

Seems to be flaky
Failing:
- https://github.com/nod-ai/shark-ai/actions/runs/14090574602/job/39465967182?pr=1164
- https://github.com/nod-ai/shark-ai/actions/runs/14072827880/job/39410389505?pr=1157

Xfail page-forking in shortfin/tests/apps

---

sharktank/sharktank/types/tensors.py

Follow up from https://github.com/nod-ai/shark-ai/pull/1008#discussion_r1985012786

Simplify __init__ for ShardedTensor and subclasses

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
.github/workflows/ci-sdxl.yaml
.github/workflows/ci-sglang-benchmark.yml
.github/workflows/ci-sglang-integration-tests.yml
.github/workflows/ci-sharktank-nightly.yml
.github/workflows/ci-sharktank.yml
.github/workflows/ci_eval_short.yaml
.github/workflows/pkgci_shark_ai.yml

refactored linux-mi300-1gpu-ossci to linux-mi300-1gpu-ossci-nod-ai

refactored linux-mi300-1gpu-ossci to linux-mi300-1gpu-ossci-nod-ai

---

shortfin/tests/apps/llm/components/kvcache/base_attention_cache_test.py

For flakiness
Xfail will be tracked in #1176

Xfail test_fork_pages entirely

---

docs/shortfin/llm/developer/e2e_llama8b_mi300x.md

Updates example config and fixes a typo in export command.

docs: Fixes for llama3.1 8b instructions

---

sharktank/sharktank/ops/attention_impls.py

previous patch erroneously rerouted the flash attention function inside of attention_impls.py directly to the custom kernel, skipping the important step of managing the scales properly. This restores the previous functionality. Something similar probably needs to be done for the masked kernel, and thats why the previous patch renamed flash_attention() to prepare_args(), with the intention of factoring out the code needed for both.

[sharktank][kernels] restores unmasked attn functionality

---

sharktank/sharktank/export_layer/export_kv_cache.py

Fix incorrect import

---

sharktank/sharktank/types/tensors.py

Helper function for moving shards of ShardedTensor between pipelines.
Changed to return PrimitiveTensors with the names of the original shards.

Make move_shards_to_new_devices help function more useful

---

.github/workflows/ci-libshortfin.yml

This reverts commit 5f7bfa9d923549fbd2724d7540bf339a8be151ee.
Fix ci errors in PR #1171

Revert "[shortfin] Enable building Rust deps on Linux (#619)"

---

sharktank/tests/models/t5/t5_test.py
sharktank/tests/utils/iree_test.py

Disable IREE T5 toy test.
Disable IREE Tracy tracing test.

[sharktank] disable hanging tests

---

app_tests/integration_tests/llm/shortfin/direct_to_batcher_test.py
shortfin/python/shortfin_apps/llm/components/batcher.py
shortfin/python/shortfin_apps/llm/components/config_struct.py
shortfin/python/shortfin_apps/llm/components/lifecycle.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/__init__.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/base_token_selection_strategy.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/beam_group.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/beam_search_token_selection_strategy.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/config.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/greedy_token_selection_strategy.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/multi_greedy_token_selection_strategy.py
shortfin/tests/apps/llm/components/token_selection_strategy/beam_search_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/greedy_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/multi_greedy_token_selection_strategy_test.py

Normalization is significantly faster on device, so support whether the logits were returned in a normalized fashion when doing beam search. This allows existing support for previous decoding strategies.
Also add support for decoder reservation system to better support batched decoding.

Integrate reservation system and normalization to decoding

---

sharktank/tests/models/llama/benchmark_amdgpu_test.py

Temporary fix to unblock [ci-llama-large-tests](https://github.com/nod-ai/shark-ai/actions/workflows/ci-llama-large-tests.yaml)
General fix will be https://github.com/iree-org/iree/issues/20491

xfail llama 8b benchmark fp16 test

---

sharktank/sharktank/ops/sharded_impls.py

Needed for pipeline parallelism.

Add all replicated version of index_put_

---

.github/workflows/ci-llama-large-tests.yaml
sharktank/tests/models/llama/benchmark_amdgpu_test.py

https://github.com/iree-org/iree/issues/20491 has fix the f16 compiler issue So remove the iree compile xfail.

Remove the iree compile xfail

---

shortfin/python/shortfin_apps/llm/components/generate.py

Introduced a bug in #1214 where when sending a batch request with `sampling_params` defined, we were improperly attempting to update the `DecodeConfig` with the `List[SamplingParams]`, instead of updating with the `SamplingParams` object that corresponded to the specific request within the batch.
This implements a fix for it.

Fix processing of `sampling_params` within a batched request

---

sharktank/sharktank/examples/pipeline/export_ppffn_net.py

Implements several fixes and refactors to the pipeline parallelism example based on recent changes to attempt to get it working again.
It will still be broken after this PR, but it's blocked by: https://github.com/iree-org/iree/issues/20354

Fixes for pipeline parallelism example

---

.github/workflows/ci-sharktank-nightly.yml
sharktank/sharktank/evaluate/perplexity_torch.py
sharktank/sharktank/layers/linear.py
sharktank/sharktank/utils/iree.py
sharktank/tests/evaluate/perplexity_torch_test.py

Fix issues from recent refactor:
- Eager mode ppl being skipped in nightly
- torch.view issue
- FP8 issue

[sharktank] Fix issues from recent refactor

---

sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/utils/load_llm.py

Found as part of perplexity testing (multi-device perplexity tests not currently running as part of CI).

Fixes for llm from pipeline PR

---

tuner/tuner/candidate_gen.py

This PR is just retiring functions,  which are used to walk the mlir file and locate root ops. 
Issue: #1303

[tuner][NFC] remove walk function over input module

---

sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/tests/ops/sharded_test.py

Implement ops.pad

---

sharktank/sharktank/types/pipelining.py

Generalizes the code slightly and allows it to work on deepseek.

Simplify pipeline parallelism code

---

docs/tune_sdxl.md
sharktuner/model_tuner/README.md
sharktuner/model_tuner/model_tuner.py
sharktuner/sharktuner/libtuner.py

Fixing runtime error in sharktuner introduced by https://github.com/nod-ai/shark-ai/commit/b19f0f8759a376706935f94d9dd1f7b21cda2ee5

[sharktuner] resolving option name conflict with libtuner

---

sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/sharded_test.py

- `ops.masked_fill` & `InferenceTensor.masked_fill`
- `InferenceTensor.bool`
- `InferenceTensor.__invert__`

More Ops for deepseek

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/types/tensors.py

- reshape implementation
- bug fix for InferenceTensor.reshape

Ops.reshape for ReplicatedTensor

---

sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/layers/testing.py
sharktank/sharktank/models/deepseek/toy_deepseek.py

- Fixes for toy deepseek
- Read more data from gguf_props, using default values if unavailable.

Toy model fixes

---

build_tools/python_deploy/README.md
build_tools/python_deploy/compute_common_version.py
build_tools/python_deploy/pypi_deploy.sh
build_tools/python_deploy/write_requirements.py

Adding sharktuner to shark-ai meta package and adding to python deployment.
See: https://github.com/nod-ai/shark-ai/issues/1248

[sharktuner] Add sharktuner to the meta-package

---

sharktank/sharktank/examples/export_paged_llm_v1.py

Currently if you have a mismatch between `--tensor-parallelism-size` and the sharding of the provided IRPA file you will get a hard to understand error message.
E.g. if you provide an unsharded IRPA, but specified to `export_paged_llm_v1` that the data is sharded with TP>1 you will get the following hard to understand error.
```
File "/home/alvasile/repos/shark-ai/sharktank/sharktank/ops/signatures.py", line 292, in _embedding_lookup_trampoline
d.fail(tensors)
File "/home/alvasile/repos/shark-ai/sharktank/sharktank/ops/_registry.py", line 270, in fail
raise NotImplementedError(
NotImplementedError: Overridable operator sharktank.ops.signatures.embedding_lookup does not have an implementation for argument types: [<class 'sharktank.types.tensors.ReplicatedTensor'>, <class …
```

Fail out early if mismatch in tensor_parallelism_size

---

sharktank/sharktank/examples/export_paged_llm_v1.py

For https://github.com/nod-ai/shark-ai/pull/1361#issuecomment-2845647798

Fix for undeclared variable

---

.github/workflows/ci-llama-large-tests.yaml
sharktank/tests/models/llama/benchmark_amdgpu_test.py

To fix 405b export issue https://github.com/nod-ai/shark-ai/issues/1354
The cause of the issue from https://github.com/nod-ai/shark-ai/pull/1000/files#r2070558146

Fix 405b irpa shard TP8 path

---

sharktank/version.json
sharktuner/version.json
shortfin/version.json

Release tracker: https://github.com/iree-org/iree/issues/20361

Bump version to 3.5.0 after 3.4.0 release.

---

README.md
sharktuner/README.md
sharktuner/model_tuner/README.md

Various improvements to documentation related to sharktuner prior to first release.

[docs] Updating documentation for may 5th 2025 release

---

shortfin/python/shortfin_apps/llm/benchmark_client.py

adding benchmark client file from demo branch to main

Adding benchmark_client.py from demo branch

---

sharktank/sharktank/ops/sharded_impls.py

fixes #1325
updating the topk ops for when dim==shard_dim

improving topk

---

sharktank/tests/evaluate/perplexity_iree_test.py

Cleanup to reduce duplicate work in prep for Deepseek PPL tests.

Refactor IREE PPL Tests

---

sharktank/sharktank/types/tensors.py
sharktank/tests/ops/ops_test.py

- Leaving method unimplemented for abstract class
- Adding tests

Cleanup InferenceTensor.__invert__

---

shortfin/python/shortfin_apps/llm/components/token_selection_strategy/beam_group.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/beam_search_token_selection_strategy.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/greedy_token_selection_strategy.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/sampler.py
shortfin/tests/apps/llm/components/token_selection_strategy/beam_group_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/beam_search_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/sampler_test.py

Move the post-processing sampling/selection logic entirely from `xtensor` to `numpy`.

Shortfin llm numpy postprocessing

---

app_tests/integration_tests/llm/model_management.py
sharktank/sharktank/evaluate/perplexity_iree.py
sharktank/sharktank/evaluate/perplexity_torch.py
sharktank/sharktank/tools/dump_gguf.py
sharktank/sharktank/utils/evaluate.py
sharktank/sharktank/utils/load_llm.py
sharktank/sharktank/utils/tokenizer.py
sharktank/tests/transforms/dataset_transforms_test.py

Refactor tokenizer, dump_gguf and DatasetShardingTransformTest.
These changes are part of Deepseek model bringup.

[sharktank] Refactor tokenizer and dump_gguf

---

shortfin/python/shortfin_apps/llm/components/batcher.py
shortfin/python/shortfin_apps/llm/components/messages.py
shortfin/python/shortfin_apps/llm/components/scheduler.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/beam_search_token_selection_strategy.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/greedy_token_selection_strategy.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/multi_greedy_token_selection_strategy.py
shortfin/tests/apps/llm/components/scheduler_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/beam_search_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/greedy_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/multi_greedy_token_selection_strategy_test.py

Reservations should be made unique to original requests. Prioritizes throughput by ensuring related requests are executed together. Strobing is still used to dispatch work known to the reservation system.
It will attempt to minimize the number of dispatches by maximizing to the ideal size. Any remaining work post-reservation filled will be filled with non-reservation work.

Make improved reservation scheduler with strobing

---

sharktank/sharktank/tools/compare_safetensors.py

Adding new features to the safetensor comparison tool including key remapping and shape mismatch reporting. 
The changes here are based on @sogartar 's llama4 branch:
https://github.com/nod-ai/shark-ai/commit/0b8b714a01e67b9979b9c2037f9058a583b2a1b9#diff-1fa7df2134f0e9af9e77392a39c63be49797f8a2e0978be996bd0dd5d058b30f

[SharkTank] improving compare_safetensors.py tool

---

requirements-iree-pinned.txt
sharktank/tests/models/flux/flux_test.py
sharktank/tests/models/llama/quark_parity_test.py
shortfin/CMakeLists.txt

Bump iree branch

---

sharktank/sharktank/utils/patching.py

fixing a bug in the patching.py in sharktank

[SharkTank] patching_bug

---

sharktank/sharktank/ops/shape.py
sharktank/sharktank/ops/sharded_impls.py

Part of deepseek model bringup.

Normalize negative dim for reshard_split

---

sharktank/sharktank/types/tensors.py

Part of deepseek model bringup.

Add .device to InferenceTensor, matching torch.Tensor.device

---

sharktank/sharktank/layers/testing.py
sharktank/tests/layers/mixture_of_experts_block_test.py

Part of deepseek model bringup.

Add missing names to toy weights

---

sharktank/sharktank/layers/causal_llm.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/models/llm/llm.py

This commit adds support for chunk attention for the prefill step of the Llama 4 model.
The code is adopted from https://github.com/nod-ai/shark-ai/tree/users/sogartar/llama4.
Authored-by: Boian Petkantchin <Boian.Petkantchin@amd.com>
Co-authore-by: Vivek Khandelwal <vivekkhandelwal1424@gmail.com>

[sharktank] Add chunk attention support for Llama 4 model

---

sharktank/tests/layers/sharded_paged_latent_attention_block.py
sharktank/tests/models/deepseek/test_deepseek.py
sharktank/tests/models/deepseek/test_sharded.py

Tests are skipped for now, will be enabled by subsequent PR which adds the implementation.

Deepseek tests

---

shortfin/python/shortfin/interop/fastapi/__init__.py
shortfin/python/shortfin/support/responder.py
shortfin/python/shortfin/support/status_tracker.py
shortfin/python/shortfin_apps/llm/cli.py
shortfin/python/shortfin_apps/llm/components/generate.py
shortfin/python/shortfin_apps/llm/components/service.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/multi_greedy_token_selection_strategy.py
shortfin/python/shortfin_apps/llm/server.py
shortfin/requirements-tests.txt

- A previous PR introduced a bug that broke the CLI script. This fixes that bug.
- Also reorganized the flags between the server and cli
- Added loguru as the logger for the cli script

Fix CLI script

---

sharktank/sharktank/layers/configs/llm_configs.py

Update llm_config to fix deepseek toy model tests
Spillover from #1486

[sharktank] Add fixes for deepseek toy model 

---

sharktank/sharktank/tools/dump_gguf.py

Handle use case of tensor_regex and num_blocks together in dump_gguf

[sharktank] Handle tensor_regex  and num_blocks in dump_gguf

---

sharktank/sharktank/layers/mixture_of_experts_block.py
sharktank/sharktank/layers/testing.py
sharktank/sharktank/models/deepseek/testing.py
sharktank/sharktank/models/llama/testing.py
sharktank/tests/layers/mixture_of_experts_block_test.py

- Add toy theta for Deepseek
- Refactor toy theta for Llama

[sharktank] Add toy theta for Deepseek

---

sharktank/sharktank/layers/paged_attention.py

Depends on https://github.com/nod-ai/shark-ai/pull/1477 and IREE bump to get the iree_linalg_ext.gather IR changes in.

[PagedAttention] Add mlir_kernel for KVCache reads

---

sharktank/sharktank/layers/configs/llm_configs.py

lamma.cpp's GGUF has this config so I am adding it here.

[sharktank] add vocab_size to LlamaHParams

---

sharktank/sharktank/layers/rotary_embedding.py
sharktank/sharktank/models/llm/llm.py
sharktank/tests/models/llama/rot_emb_test.py

Not every model uses scaling for theta

[RoPE] Only use llama3 scaling if requested

---

sharktank/sharktank/export_layer/export_moe.py
sharktank/sharktank/layers/activations.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/layers/ffn_block.py
sharktank/sharktank/layers/ffn_moe_block.py
sharktank/sharktank/layers/mixture_of_experts_block.py
sharktank/sharktank/layers/testing.py
sharktank/sharktank/models/llama/testing.py
sharktank/sharktank/models/llm/llm.py
sharktank/tests/layers/mixture_of_experts_block_test.py

This commit adds support for mixture of experts for the Llama 4 model.
The code is adopted from https://github.com/nod-ai/shark-ai/tree/users/sogartar/llama4.
Authored-by: Boian Petkantchin <Boian.Petkantchin@amd.com>
Co-authore-by: Vivek Khandelwal <vivekkhandelwal1424@gmail.com>

[sharktank] Add mixture of experts(moe) support for Llama 4 model

---

sharktank/sharktank/utils/patching.py

Sometimes torch module functions may have arguments/results that are not tensors. Don't trace these.

[sharktank] skip non-tensor args/results in TraceTensorModulePatch

---

sharktank/sharktank/utils/patching.py

In some strange cases torch does not want to trace tensors during export.
It complains about that we are trying to modify frozen tensors. We need our signature to be
```
trace_tensor(str trace_key, Tensor(a!) tensor) -> ()
```
This means it modifies the tensor in-place and returns nothing. Then the op
will not be removed.
Cloning the tensor before tracing does not help as torch export is smart and
removes the whole expression.
Ideally we would like to say that the op is side-effecting but that seems
unavailable in torch.
With this change you can exclude some trace key patterns to be excluded from the trace.
Thus circumventing the torch weirdness.

[sharktank] In trace tensor module patching allow for exclusion by regex key search

---

.coveragerc
.github/workflows/ci-sharktank.yml
sharktank/pyproject.toml
sharktank/requirements-tests.txt
sharktank/setup.cfg
sharktank/sharktank/kernels/topk.py

This PR is to test out code coverage in the shartank package. Once we tweak this and are satisfied with the results, we can enable it for all the code in the repo. 
Example: https://app.codecov.io/github/nod-ai/shark-ai/commit/f24ce4c301b042c50c6fd2192579300fa0b66128

Initial code coverage commit for sharktank

---

sharktank/sharktank/layers/base.py

It is beneficial to have a record on how a model was compiled. The compiler does not record the compile command into the VMFB. See feature issue for that https://github.com/iree-org/iree/issues/20463

[sharktank] save compile command when compiling

---

sharktank/sharktank/utils/export_artifacts.py

Standardize exceptions with base class, add runtime exception to use in future PR.

Refactor ExportArtifact exceptions

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
sharktank/sharktank/evaluate/perplexity_iree.py
sharktank/sharktank/utils/export_artifacts.py
sharktank/tests/models/deepseek/test_sharded.py
sharktank/tests/models/llama/benchmark_amdgpu_test.py

This should be the end of the major refactors required for ExportArtifacts.
Had to refactor a few other files to get their usage of ExportArtifacts inline with the new interfaces.

Further ExportArtifacts and benchmark_amd_gpu refactors

---

sharktank/sharktank/evaluate/perplexity_iree.py
sharktank/sharktank/utils/cli.py
sharktank/sharktank/utils/export_artifacts.py

Now the flags are really extra, meaning they do not override existing flags.
Also refactor to always skip file generation if they exist.

[sharktank] in perplexity allow for passing as CLI of extra compiler flags

---

.github/workflows/ci_llama_3.1_405b_fp16_tp8.yml
.github/workflows/ci_llama_3.1_405b_fp8_tp8.yml
.github/workflows/ci_llama_3.1_70b_fp16.yml
.github/workflows/ci_llama_3.1_70b_fp16_tp8.yml
.github/workflows/ci_llama_3.1_70b_fp8.yml
.github/workflows/ci_llama_3.1_8b_fp16.yml
.github/workflows/ci_llama_3.1_8b_fp8.yml
.github/workflows/ci_mistral_nemo_instruct_2407.yml
scripts/export_and_compile.sh
scripts/run_iree_benchmark.sh

Updated yml files to generate json file

Updated yml to generate json file

---

scripts/run_serving.sh

TP8 expect list as IRPA and also device IDs should match with TP size

TP8 expect list as IRPA and also device IDs should match with TP size

---

shortfin/python/shortfin_apps/llm/components/generate.py
shortfin/python/shortfin_apps/llm/components/lifecycle.py
shortfin/python/shortfin_apps/llm/components/request_queue_manager.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/__init__.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/beam_group.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/config.py
shortfin/tests/apps/llm/components/request_queue_manager_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/beam_search_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/independent_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/token_selection_strategy_test.py

Constructor reached into sub objects (batchers, page cache), didn't cache useful information (rid), and did not leverage data grouping (DecodeConfig)

Cleanup the build for the ItemProcessor

---

sharktank/sharktank/models/llama/tools/import_quark_dataset.py

Fix the number of layers of llama 405b import_quark_dataset.py

---

sharktank/sharktank/examples/pipeline/export_ppffn_net.py
sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/types/pipelining.py
sharktank/tests/examples/main_test.py

Pipeline cleanup

---

shortfin/python/shortfin_apps/llm/components/generate.py

These parameters / state was leftover cruft that could be trivially deleted.

Delete some old cruft code that was unused

---

sharktank/sharktank/ops/sharded_impls.py

Allows for integrating with fp4 kernel.

Move transpose responsibility to matmul

---

app_tests/integration_tests/llm/shortfin/tinystories_llama2_25m_test.py
shortfin/python/shortfin_apps/llm/components/batcher.py
shortfin/python/shortfin_apps/llm/components/scheduler.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/__init__.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/config.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/token_selector.py
shortfin/tests/apps/llm/components/scheduler_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/beam_search_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/independent_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/token_selection_strategy_test.py

Makes more sense to notify the expected size instead of sending deltas. This is more realistic as we would not want a constant update on what future job sizes will look like.

Cleanup scheduler to update rather than add / remove

---

docs/model_cookbook.md
sharktank/sharktank/tools/convert_dataset.py
sharktank/sharktank/transforms/dataset/dataset.py
sharktank/tests/tools/convert_dataset_test.py

Now the tool can convert from source dtype(s) to target dtype(s). It may get extended with more functionality in the future.

[sharktank] Add dataset conversion tool

---

sharkfuser/include/fusili/attributes/attributes.h
sharkfuser/include/fusili/attributes/conv_attributes.h
sharkfuser/include/fusili/attributes/tensor_attributes.h
sharkfuser/include/fusili/context.h
sharkfuser/include/fusili/graph.h
sharkfuser/include/fusili/logging.h
sharkfuser/include/fusili/node/conv_node.h
sharkfuser/include/fusili/node/node.h
sharkfuser/include/fusili/types.h
sharkfuser/samples/convolution/conv_fprop.cpp
sharkfuser/tests/test_attributes.cpp
sharkfuser/tests/test_context.cpp
sharkfuser/tests/test_conv_attributes.cpp
sharkfuser/tests/test_conv_node.cpp
sharkfuser/tests/test_graph.cpp
sharkfuser/tests/test_logging.cpp
sharkfuser/tests/test_tensor.cpp
sharkfuser/tests/test_tensor_attributes.cpp

We started off not knowing where Fusili would live and which code style to adopt but we're soon converging towards having this as an IREE extension / frontend. Adopting IREE style (based off LLVM) makes sense.

[fusili][NFC] Adopt LLVM code style throughout

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/sharded_test.py

In principal this allows the shards be any inference tensor.

[sharktank] Make sharded-split tensor support quantized tensors

---

sharktank/sharktank/models/llama/testing.py
sharktank/sharktank/models/llama/toy_llama.py
sharktank/tests/models/llama/quantized_test.py

We need something so that we can work with a toy model. It does not need to be a good quantization.

[sharktank] Add toy Llama FP4 quantization

---

sharkfuser/include/fusili/asm_emitter.h
sharkfuser/include/fusili/attributes/tensor_attributes.h
sharkfuser/tests/lit/test_asm_emitter.cpp

Address a post-merge comment: https://github.com/nod-ai/shark-ai/pull/1906#discussion_r2231249763

[Fusili] s/RankedTensorType/ValueTensorType

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/tests/ops/sharded_test.py

The FP4 block quantized tensor does not support transposition of the blocked dimension and it is not clear how to support this. This forces us to not use transposition to simplify matmuls, but to propagate the bool arg transpose_rhs to the multiplication of the shards.
Rework the tests to cover more cases.

[sharktank] propagate transpose_rhs into the shards on sharded matmumls

---

sharktank/version.json
sharktuner/version.json
shortfin/version.json

Release tracker: iree-org/iree#21457

Bump version to 3.7.0 after 3.6.0 release.

---

sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/ops/quantized_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/qconv_test.py
sharktank/tests/ops/sharded_test.py

We want unpack for quantized tensors, layouts and quantized sharded tensors.

[sharktank] make unpack an op with dispatch

---

sharktank/sharktank/types/layouts.py
sharktank/tests/ops/quantized_test.py

The change https://github.com/nod-ai/shark-ai/pull/1900 introduced a bug where a loaded tensor would have no external trait, which then during export caused the tensor to get inlined into the MLIR.

[sharktank] Fix loading of legacy fp4 block scaled quantized tensors having scale with no external tensor trait

---

.github/workflows/ci-sharktank.yml
sharktank/integration/models/punet/integration_test.py

**Why:**
GitHub hosted runner does not have enough disk space in /tmp to store all files. This is the reason that cause this CI test fail
**How:**
Split "Run punet tests" into two tests, one for fp16 and one for int8

Fix Model Integration Test

---

sharktank/sharktank/models/t5/export.py
sharktank/sharktank/types/theta.py

Fix wrong inlining into the MLIR of model parameters.

[sharktank] Fix nightly testCompareV1_1XxlFluxRepoIreeBf16AgainstTorchEagerF32

---

shortfin/python/shortfin_apps/llm/components/generate.py
shortfin/python/shortfin_apps/llm/components/io_struct.py

Tweak temperature default and temperature value check

---

sharktank/sharktank/layers/rotary_embedding_hf.py
sharktank/tests/layers/rotary_embedding_hf_test.py

[sharktank] Rope for openweight

---

.github/workflows/ci_llama_3.1_8b_fp16_nightly_harness.yml

Added the nightly harness for llama model 3.1 8b fp16.

[CI] Llama 3.1 8b fp16 nightly harness

---

app_tests/integration_tests/llm/server_management.py
app_tests/integration_tests/llm/shortfin/conftest.py
app_tests/integration_tests/llm/shortfin/tinystories_llama2_25m_test.py
shortfin/python/shortfin_apps/llm/components/decode_config.py
shortfin/python/shortfin_apps/llm/components/decoder/decoder.py
shortfin/python/shortfin_apps/llm/components/io_struct.py
shortfin/python/shortfin_apps/llm/components/lifecycle.py
shortfin/python/shortfin_apps/llm/components/request_queue_manager.py
shortfin/python/shortfin_apps/llm/server.py
shortfin/tests/apps/llm/components/invocation_test.py
shortfin/tests/apps/llm/components/request_queue_manager_test.py

Testing the full request matrix is not necessary. Stripped down to a limited subset of tests.

Strip down tinystories to fewer tests - strip beam search crud

---

.github/workflows/ci_llama_3.1_70b_fp16.yml
.github/workflows/ci_llama_3.1_70b_fp8.yml
.github/workflows/ci_llama_3.1_8b_fp16.yml
.github/workflows/ci_llama_3.1_8b_fp8.yml
.github/workflows/ci_mistral_nemo_instruct_2407.yml
scripts/export_and_compile.sh

add checks to CI for early fail

test adding checks

---

sharktank/sharktank/tools/run_llm_vmfb.py
sharktank/sharktank/utils/llm_utils.py

Existing version returns post the EOS token. This should return the EOS version. Steps are performed until all requests have hit the EOS token or the step limit has been hit.

Add EOS token ids for decode utility

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/layers/causal_llm.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/utils/tokenizer.py
sharktank/tests/layers/configs_test.py

- `static_tables` from `LlamaModelConfig`
- `_assert_device` from `BaseCausalLMModel`

[Sharktank] Remove old unused code

---

.github/workflows/ci_llama_3.1_8b_fp16_from_source.yml
.github/workflows/ci_llama_3.1_8b_fp8_from_source.yml
scripts/run_serving.sh

Some changes for 6 hour Workflow file

Changes for six hour report

---

sharktank/sharktank/export_layer/export_paged_attention.py
sharktank/sharktank/layers/paged_attention.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/types/quantizers.py
sharktank/sharktank/utils/create_cache.py
sharktank/tests/layers/paged_llama_attention_block_test.py

- Move quantizer from arg to state inside KVCache.
- Move packing and unpacking of quantized tensors inside kvcache read and writes.
- Remove sharding related checks.

[Sharktank] Replumb KV Quantizers

---

.github/workflows/ci_llama_3.1_8b_fp8.yml
.github/workflows/ci_llama_3.1_8b_fp8_from_source.yml

fixed file path

---

sharktank/tests/models/llama/attention_test.py

Current version of the tests does **not** use a causal mask, which we can't support after the masking replumbing. Landing this separately to show it doesn't affect correctness when we switch to a causal mask.

[Sharktank] Change TestAttentionBlock to use causal attention mask

---

.github/workflows/ci_llama_3.1_8b_fp16_nightly_harness.yml

Updates for MI355 machine

---

sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/ops/quantized_impls.py
sharktank/sharktank/ops/signatures.py

We will want to deal with this TODO sooner rather than later.

[Sharktank] Unpack to qs

---

sharktank/tests/layers/mixture_of_experts_block_test.py

adding new torch tests for MOE

[Sharktank] MoE golden tests

---

sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/models/flux/export.py
sharktank/sharktank/tools/import_hf_dataset_from_hub.py
sharktank/sharktank/transforms/dataset/dataset.py
sharktank/sharktank/utils/functools.py
sharktank/sharktank/utils/hf.py
sharktank/tests/models/llama/test_llama.py

This would allow us to stop using llama.cpp's `convert_hf_to_gguf.py` tool.

[sharktank] add tool to import/convert LLM Hugging Face model parameters to sharktank

---

sharktank/sharktank/layers/__init__.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/tests/layers/paged_llama_attention_block_test.py

- Move common functionality into PagedLlamaAttentionBlock
- Fix missing import for logger
- Mix unused matmul_kernel arg

[Sharktank] Refactor PagedLlamaAttentionBlocks to remove duplicated code

---

sharktank/sharktank/layers/rotary_embedding.py

Simplify implementation based on implementation of PagedAttention.

[Sharktank] Redo ReplicatedRotaryLayer implementation

---

sharktuner/sharktuner/dispatch_constraints.py

Change tuning search space to exclude invalid candidates.

[Tuner] Add m tile size alignment constraint

---

scripts/run_serving.sh

fix the check for llama model

---

.github/workflows/ci-sharktank.yml
sharktank/integration/models/punet/integration_test.py

This should resolve #2346 by using `temp_dir` for storing hf artifacts.

Resolve CI issue with punet int8 export

---

sharktank/sharktank/layers/rotary_embedding.py
sharktank/sharktank/layers/rotary_embedding_hf.py

[Sharktank] Change RotaryEmbeddingLayer to work with ReplicatedTensors

---

shortfin/README.md

- Add a section to `shortfin README.md` w/ instructions for accuracy tests

[LLM Server] 8b Accuracy Test Instructions

---

app_tests/integration_tests/llm/shortfin/tinystories_llama2_25m_test.py
shortfin/python/shortfin_apps/llm/components/decoder/decoder.py
shortfin/python/shortfin_apps/llm/components/kvcache/attention_cache_abstract.py
shortfin/python/shortfin_apps/llm/components/kvcache/base_attention_cache.py
shortfin/python/shortfin_apps/llm/components/messages.py
shortfin/tests/apps/llm/components/invocation_test.py
shortfin/tests/apps/llm/components/messages_test.py

This PR includes the following work:
1. update BaseAttentionCache APIs to work with decoder
2. update related tests.

Update BaseAttentionCache APIs

---

sharkfuser/benchmarks/CMakeLists.txt
sharkfuser/benchmarks/driver.cpp
sharkfuser/include/fusilli/attributes/tensor_attributes.h
sharkfuser/include/fusilli/support/asm_emitter.h
sharkfuser/samples/convolution/conv_fprop_nchw_kcrs.cpp
sharkfuser/samples/convolution/conv_fprop_nhwc_krsc.cpp
sharkfuser/tests/test_tensor_attributes.cpp

Support for:
TBD in follow-on:

[Fusilli] Benchmark Driver 2/N
