nod-ai/shark-ai

sharktank/sharktank/examples/paged_llm_v1.py
sharktank/sharktank/layers/causal_llm.py
sharktank/sharktank/layers/kv_cache.py
sharktank/sharktank/layers/rotary_embedding.py
sharktank/sharktank/models/llama/llama.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/types/theta.py
sharktank/sharktank/utils/tokenizer.py
sharktank/tests/types/dataset_test.py
sharktank/tests/types/tensors_test.py

* Threads explicit device through models.
* Implements functional InferenceTensor, Theta and Dataset transformations and uses it to implement `to(device=)`.
* Adds `--device foo` to example runner.
* With https://github.com/iree-org/iree-turbine/pull/3 and supporting patches, this allows custom ops and kernels to transparently be used on CUDA/ROCM devices (instead of just CPU).

Support moving theta and models to a specific device.

---

requirements.txt
sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/examples/paged_llm_v1.py
sharktank/sharktank/layers/causal_llm.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/layers/kv_cache.py
sharktank/sharktank/layers/norm.py
sharktank/sharktank/models/llama/llama.py
sharktank/sharktank/ops/base.py
sharktank/sharktank/ops/mmt_block_scaled_q8.py
sharktank/sharktank/ops/mmtfp.py
sharktank/sharktank/ops/templates/mmt_block_scaled_offset_q4_unsigned.mlir
sharktank/sharktank/ops/templates/mmt_block_scaled_q8_3d.mlir
sharktank/sharktank/ops/templates/mmt_super_block_scaled_offset_q4_unsigned_3d.mlir
sharktank/sharktank/ops/templates/mmtfp_2d.mlir
sharktank/sharktank/ops/templates/mmtfp_3d.mlir
sharktank/tests/ops/mmt_block_scaled_offset_q4_test.py
sharktank/tests/ops/mmt_block_scaled_q8_test.py
sharktank/tests/ops/mmt_super_block_scaled_offset_q4_test.py
sharktank/tests/ops/mmtfp_test.py

* Reworks all layers to respect declared activation/attention dtypes.
* Defaults normalization layers to promote to f32.
* Reworks all custom kernels to support mixed data types.
* Adds parameterized tests for dtype combinations.
* Switches template engine from str.format to jinja2 (this has been planned from the get-go and it was needed to handle switchiness due to dtype changes).
* Verified that inference works with `--activation-dtype float16`.
New deps added: parameterized, jinja2

Add explicit activation and attention dtypes.

---

.github/workflows/ci.yaml
README.md
sharktank/setup.py
turbine-requirements.txt

The main project moved from https://github.com/nod-ai/SHARK-Turbine/ to https://github.com/iree-org/iree-turbine. Some package names and import paths still need to be migrated.
The package name is still "shark-turbine", even when using the "iree-turbine" repo.

Migrate dep from SHARK-Turbine to iree-turbine git repo.

---

sharktank/sharktank/examples/validate_llama_ref_model.py

This file had the copyright header twice.

Remove repeated copyright header from validate_llama_ref_model.py.

---

requirements.txt
sharktank/sharktank/examples/validate_llama_ref_model.py
sharktank/sharktank/models/llama/llama_ref.py

huggingface-hub is needed for hf_datasets.py and transformers is needed for AutoTokenizer

Clean up validate_llama_ref_model example and requirements for examples

---

sharktank/README.md
sharktank/sharktank/examples/export_paged_llm_v1.py

This helps when changing the script, exporting multiple versions, or using different inputs (via the `--hf-dataset` or `--gguf-file` input flags).

Add `--output` argument to `export_paged_llm_v1.py`.

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/examples/paged_llm_v1.py
sharktank/sharktank/examples/sharding/shard_llm_dataset.py
sharktank/sharktank/examples/validate_llama_ref_model.py
sharktank/sharktank/tools/dump_gguf.py
sharktank/sharktank/transforms/dataset/__init__.py
sharktank/sharktank/transforms/dataset/sharding.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/types/theta.py
sharktank/sharktank/utils/cli.py
sharktank/sharktank/utils/io.py
sharktank/sharktank/utils/logging.py
sharktank/tests/transforms/dataset_transforms_test.py

* Adds a new ShardedTensor and ShardedPrimitiveTensor (ShardedQuantizedTensor is TBI).
* Adds an example `shard_llm_dataset` tool which will shard most of the LLM MLP layers for standard models.
* Extends dataset saving and loading to save 'global' IRPA files by default, but if shards are present in the dataset, they will be written/read from dedicated `*.rank{n}.irpa` files. For serving, this will allow each rank to have a subset of only the parameters it needs in certain advanced topologies.
* May make this optional in the future, also allowing to save a flat IRPA.
* Threads through some additional CLI handling niceties for dataset input/output tools.
* Next steps will add op support for these ShardedTensor cases by emitting appropriate device-affinity and reduction ops.

Add support for tensor parallel sharding of datasets.

---

sharktank/README.md
sharktank/sharktank/examples/export_paged_llm_v1.py
shortfin/shortfin/llm/config.py

Beyond the exported `mlir` file additional configuration information is needed for inference, specifically the hyper parameters to allocating kv cache information along with maximum context length, etc.

[sharktank] Support exporting LLM configuration information

---

sharktank/sharktank/kernels/templates/mmt_block_scaled_offset_q4_unsigned.mlir
sharktank/sharktank/kernels/templates/mmt_block_scaled_q8_3d.mlir
sharktank/sharktank/kernels/templates/mmt_super_block_scaled_offset_q4_unsigned_3d.mlir

`tensor.expand_shape` has been updated for supporting between dynamic dimensions.

Bump kernels for `tensor.expand_shape` update

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/models/llama/llama.py
shortfin/shortfin/framework/session.py
shortfin/shortfin/llm/impl/service_v1.py
shortfin/shortfin/llm/impl/service_v1_cli.py
shortfin/shortfin/llm/testing/fake_v1_module.py

Updated for what the outgoing prefill looks like. This included validation with llama 2 that a reasonable sequent (one two three four) correctly predicted preceding tokens.
This should support generic export / execution of gguf prefill however there still exists issues with the newly added decoder path.

[shortfin] Add end-to-end cli for testing / executing prefill

---

sharktank/sharktank/transforms/dataset/sharding.py
sharktank/sharktank/types/gguf_interop/base.py
sharktank/sharktank/types/gguf_interop/layouts.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/ops_test.py
sharktank/tests/transforms/dataset_transforms_test.py
sharktank/tests/types/dataset_test.py
sharktank/tests/types/tensors_test.py

This was bugging me for a while. Practically, it lets us make the `name` optional, which makes sense for activations and such.

Change signature of InferenceTensor constructors to be kwarg based.

---

sharktank/sharktank/kernels/mmtfp.py
sharktank/sharktank/ops/__init__.py
sharktank/sharktank/ops/_registry.py
sharktank/sharktank/ops/custom_impls.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/ops_test.py
sharktank/tests/ops/sharded_test.py

This level of math is aimed at the inner-most level of the device hierarchy, where it is assumed that the devices connected to a process are connected via high-speed links. By coding the model with explicit sharded arithmetic, we naturally get multi-device distribution by having a few points where we insert communication primitives. In this approach, the same math expressions run on either unary or nary-sharded tensor-parallel weight partitions. Using duck typing, the nary-sharded partitions are seen as a `ShardedTensor` and corresponding duplication of the math is undertaken. Unlike fully automatic solutions, this approach *requires* that the model author does some minimal coding for placement and distribution. In practice, this is unavoidable anyway, so by taking the layers of …

Implement explicit sharded arithmetic operations using duck typing.

---

sharktank/sharktank/utils/testing.py

This fixes errors during cleanup on Windows like:
```
============================================ FAILURES ============================================= _________________________________ ShardingTests.testExportFfnNet __________________________________
path = WindowsPath('C:/Users/Scott/AppData/Local/Temp/tmpi6mjj021ShardingTests')
onerror = <function onerror at 0x000001CE81C54FE0>
def _rmtree_unsafe(path, onerror):
try:
with os.scandir(path) as scandir_it:
entries = list(scandir_it)
except OSError:
onerror(os.scandir, path, sys.exc_info())
entries = []
for entry in entries:
fullname = entry.path
if _rmtree_isdir(entry):
try:
if entry.is_symlink():
raise OSError("Cannot call rmtree on a symbolic link")
except OSError:
onerror(os.path.islink, fullname, sys.exc_info())
continue …
```

Ignore errors in `shutil.rmtree`, fixing test failure on Windows.

---

sharktank/sharktank/examples/validate_llama_ref_model.py
sharktank/sharktank/examples/validate_paged_llama_model.py
sharktank/sharktank/models/llama/llama_ref.py

Both of these commands work now:
```bash
python -m sharktank.examples.validate_paged_llama_model --hf-dataset=open_llama_3b_v2_f16_gguf
python -m sharktank.examples.validate_llama_ref_model --hf-dataset=open_llama_3b_v2_f16_gguf
```
Changes:
* Fixed these scripts to use the latest dataset utilities, avoiding errors about flag parsing:
```
(sharktank) λ python -m sharktank.examples.validate_paged_llama_model --hf-dataset=open_llama_3b_v2_f16_gguf
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "D:\dev\projects\sharktank\sharktank\sharktank\examples\validate_paged_llama_model.py", line 184, in <module>
sys.exit(main(sys.argv[1:]))
^^^^^^^^^^^^^^^^^^
File …
```

Fix validate_*_model.py scripts, plumb dtype in llama_ref.

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/examples/validate_direct_llama_model.py

It sounds like we'll end up with a bs1-only variant for client use and a bsN variant for serving with a couple of batch sizes compiled in that can be switched between dynamically to optimize for throughput.
* A new `--bs` argument can be used to specify batch sizes:
flag | result
-- | --
--bs=1 | direct cache, batch size 1
--bs=4 | paged cache, batch size 4
--bs=1,4 | paged cache, batch sizes 1 and 4
--bs=2,4,8 | paged cache, batch sizes 2, 4, and 8
* `prefill_bs1` exports successfully, with `generate_batch_decode(bs)` commented out and a command like
```
python -m sharktank.examples.export_paged_llm_v1 \
--hf-dataset=open_llama_3b_v2_f16_gguf \
--output_mlir=/tmp/llama_prefill_bs1.mlir \
--output_config=/tmp/llama_prefill_bs1.json \
--bs=1
```
* `decode_bs1` fails during fx tracing, see …

Export using "direct" kv_cache_type with batch size 1.

---

.github/workflows/ci.yaml

If we want this coverage (it would help me as I develop mainly on Windows).
The Linux job currently take ~1 minute, Windows take ~3 minutes (mostly extra take taken installing deps via pip).
~~There is one test failure at the moment, which https://github.com/nod-ai/sharktank/pull/34 will fix.~~

Enable ci.yml tests on Windows.

---

sharktank/sharktank/layers/__init__.py
sharktank/sharktank/layers/conv.py
sharktank/sharktank/layers/linear.py
sharktank/sharktank/models/punet/layers.py
sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py
sharktank/sharktank/models/punet/tools/run_punet.py
sharktank/sharktank/ops/_registry.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/types/__init__.py
sharktank/sharktank/types/layout_utils.py
sharktank/sharktank/types/layouts.py
sharktank/sharktank/types/quantizers.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/types/theta.py
sharktank/sharktank/utils/testing.py
sharktank/tests/layers/linear_test.py
sharktank/tests/types/layouts_test.py
sharktank/tests/types/quantizer_test.py
sharktank/tests/types/quantizers_test.py

This is a fairly substantial body of work that will be refined as we bring the model fully online. As of now, it runs and exports properly with the smoothquant int8 strategy and configuration we chose, but the results do not look correct. We will need to go through with a fine tooth comb and validate all of the numerics in conjunction with the quantization simulator that produced the parameters.
Key things added:
* Quantizer tensors for expressing the parameters needed in order to quantize from a higher precision to lower precision (tests both integer and fp8).
* First pass of teaching Linear and Conv layers how to work with quantized tensors and quantizers.
* Teach Linear and Conv layer how to handle high precision input pre multiplier (needed for SmoothQuant like strategies).
* Add a …

Implement quantization import for punet model.

---

sharktank/sharktank/layers/conv.py
sharktank/sharktank/layers/linear.py
sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py
sharktank/sharktank/ops/__init__.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/q_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/layout_utils.py
sharktank/sharktank/types/quantizers.py
sharktank/sharktank/types/tensors.py
sharktank/tests/layers/linear_test.py

Capturing a stable state from iterating with the quantization simulator.
Primary changes:
* Drastically simplify the way that linear and conv layers are configured. Now the primary knob is the presence of a `q_input` quantizer. If present, it will be used to quantize the activations prior to feeding to the underlying op.
* Add `qdq_input` tensor to linear and conv, which can be used to simulate quantization for testing/compare/goldens/etc.
* Implemented bias quantization (disabled for now because still tracking down numeric instability).
* Added an option to the brevitas importer to bootstrap from a base safetensors file, only using the primary one for quantized layers. Not clear it is meaningful but aided some debugging.
* Added an optimized quantized linear op override. This will get …

Iterate on quantized linear and conv layers.

---

sharktank/sharktank/layers/base.py
sharktank/sharktank/models/punet/model.py
sharktank/sharktank/models/punet/tools/run_punet.py
sharktank/sharktank/utils/debugging.py

* run_punet.py gets a `--inputs` argument, where a safetensors file can be supplied to override random inputs.
* Added APIs for `trace_tensor(golden=True)` which is meant to be kept permanently at key points in the model (as opposed to normal trace_tensor which is meant as a debugging aid to be removed when done).
* Added `TURBINE_LLM_DEBUG=save_goldens_path=...some/path` env var setting. This dumps a sequenced list of safetensors files for every tensor traced with golden=True.
* Added golden traces at input/output/down/mid/up block boundaries in the punet model.
* Verified with an offline script that without our optimized linear layer, we are within the margin of error with stability unet, using Brevitas i8 quantization. The layer with optimized math enabled diverges slowly, causing a …

Add some features that make it easier to do A/B comparison on punet.

---

sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py
sharktank/sharktank/ops/q_impls.py
sharktank/sharktank/types/layouts.py
sharktank/sharktank/types/quantizers.py
sharktank/sharktank/types/tensors.py
sharktank/tests/types/quantizers_test.py

Previously, the dtype of the scale dictated the output dtype after dequant. This makes it impossible to execute in low-p (i.e. fp16) while preserving rescale computation in high-p (i.e. fp32). The latter is needed to avoid integer->float overflow after integer arithmetic. (There are other ways to factor this to avoid higher precision scales but this is simple/standard)
Also enables quantized bias, since this avoids the overflow and fixes an unnecessarily large eps.

[punet] Update quantizer to allow explicit mixed precision rescale.

---

sharktank/sharktank/ops/q_impls.py

Use int32 dtype for linear offset correction to avoid warp reduction bit width error for int64 during compilation on MI300
Signed-off-by: aviator19941 <avinash.sharma@amd.com>

[q_impls] Use int32 dtype for linear offset correction

---

sharktank/sharktank/examples/sharding/export_ffn_net.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/qlinear_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/ops_test.py
sharktank/tests/ops/sharded_test.py

Add the `permute` function that is equivalent to `torch.permute`. Add the `T` property to `InferenceTensor`.
Implement `linear` for some sharded tensor cases.

Make matmul's transpose_rhs default to False and use linear instead

---

sharktank/sharktank/ops/custom_impls.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/ops_test.py
sharktank/tests/ops/sharded_test.py

Add polymorphic `replicate`, `shard` and `shard_like` ops.
Add operator `+` for InferenceTensor.
Add `ops.equal`, analogous to `torch.equal` that operates on sharktank tensor types.

Expand sharded element-wise binary ops support

---

sharktank/sharktank/examples/sharding/export_ffn_net.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/transforms/dataset/sharding.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/sharded_test.py
sharktank/tests/transforms/dataset_transforms_test.py
sharktank/tests/types/tensors_test.py

We are using the term sharded as a general term to mean a tensor that is distributed across a number of logical devices.
On the other hand we are also using it to mean a tensor split along a dimension and distributed across the logical devices. To avoid confusion in the latter context we will talk about a sharded split tensor or simply a split tensor.

Disentangle the sharded and split notions

---

sharktank/tests/types/quantizers_test.py

Each call to `_roundtrip` was creating a file with the same name in the temp directory and the second write would fail. This gives each temp file a unique name manually.
We could also
* Close the file to allow it to be reopened
* Use other functions in tempfile to create uniquely named _files_, not just a directory
Sample error: `FAILED sharktank\tests\types\quantizers_test.py::StaticScaledQuantizerTest::testPerTensorQuantDequant - RuntimeError: Error building parameter archive: D:\a\iree\iree\c\runtime\src\iree\base\internal\file_io.c:381: UNKNOWN; failed to open file 'C:\Users\RUNNER~1\AppData\Local\Temp\tmpejgrnsnpStaticScaledQuantizerTest\poodoo.irpa'`. Full logs: https://github.com/nod-ai/sharktank/actions/runs/9509442435/job/26212392662.
References:
* …

Fix quantizers_test on Windows.

---

sharktank/sharktank/ops/_registry.py
sharktank/tests/ops/ops_test.py
sharktank/tests/ops/qconv_test.py

Only enables it when needed.
This trips up Dynamo to have multiple things mutating this global.

Guard the testing facility used to verify last op dispatch.

---

docs/debug_flags.md
sharktank/sharktank/kernels/__init__.py
sharktank/sharktank/kernels/base.py
sharktank/sharktank/kernels/batch_matmul_transpose_b.py
sharktank/sharktank/kernels/conv_2d_nchw_fchw.py
sharktank/sharktank/kernels/pooling_nchw_sum.py
sharktank/sharktank/kernels/templates/batch_matmul_transpose_b.mlir
sharktank/sharktank/kernels/templates/conv_2d_nchw_fchw.mlir
sharktank/sharktank/kernels/templates/pooling_nchw_sum.mlir
sharktank/sharktank/ops/qconv_impls.py
sharktank/sharktank/ops/qlinear_impls.py
sharktank/sharktank/utils/debugging.py
sharktank/tests/kernels/batch_matmul_transpose_b_test.py
sharktank/tests/kernels/conv_2d_nchw_fchw_test.py
sharktank/tests/kernels/pooling_nchw_sum_test.py

Our quantization scheme relies on having integer kernels for a few key ops. While torch mm/conv ops are technically defined for integer operands, in practice, the type matrix is very sparsely implemented across backends. As such, we just define IREE specific ops for these and use them.
Unlike mm/conv, torch does not have a good pooling sum operator, instead using avg_pool with a denominator override (only defined for FP). Therefore, we provide that too.

[punet] Add direct to linalg integer kernels for mmt, conv, pooling sum.

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/sharding.py
sharktank/sharktank/types/theta.py
sharktank/tests/ops/sharded_test.py

Sharding specs are concise description of tensor and layer sharding. They can be applied to tensors and thetas to get the sharded counterpart.
This is mostly the pluming around specific cases. Only sharing of the channel dimension in group normalization is provided.

Add sharding specs

---

sharktank/sharktank/models/punet/sharding.py
sharktank/sharktank/models/punet/tests/resnet_test.py
sharktank/sharktank/ops/__init__.py
sharktank/sharktank/ops/_registry.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/qconv_impls.py
sharktank/sharktank/ops/qlinear_impls.py
sharktank/sharktank/ops/shape.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/sharding.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/types/theta.py
sharktank/tests/layers/resnet_test.py
sharktank/tests/ops/ops_test.py
sharktank/tests/ops/sharded_test.py

Add one case of resnet block sharding
`ResnetBlock2DSplitOutputChannelsSharding`.
Move AnyTensor to avoid cyclic dependencies.
Add broadcast_dim(s) functions and handle broadcasting for element-wise binary with sharded split tensors.
Make sharded linear override for a cartesian product of type sets. Let the constituent ops fail if they can't handle the input.
Add matmul for replicated LHS and split RHS.
Fix resharding of thetas.
Add unshard op.
Fix slicing of split tensor.
Refactor Theta to reflect that it is actually a tree of tensors and expose the tree.
Fix some asserts during construction.

Add sharding of ResnetBlock2D

---

sharktank/sharktank/kernels/conv_2d_nchw_fchw.py
sharktank/sharktank/kernels/pooling_nchw_sum.py
sharktank/sharktank/kernels/templates/conv_2d_nchw_fchw.mlir
sharktank/sharktank/kernels/templates/pooling_nchw_sum.mlir
sharktank/sharktank/ops/qconv_impls.py
sharktank/tests/kernels/conv_2d_nchw_fchw_test.py
sharktank/tests/kernels/pooling_nchw_sum_test.py

Moves the padding for conv and pooling kernels before extsi operations of operands.
Fixes https://github.com/nod-ai/SHARK-Turbine/issues/750

Insert padding for conv and pooling ops before bit-width extend operations of operands

---

sharktank/conftest.py
sharktank/integration/models/punet/integration_test.py
sharktank/pyproject.toml
sharktank/sharktank/models/punet/README.md
sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py
sharktank/sharktank/models/punet/tools/import_hf_dataset.py
sharktank/sharktank/models/punet/tools/run_punet.py
sharktank/sharktank/utils/testing.py

* Imports/validates the FP16 model running eagerly.
* Imports/validates the int8 model running eagerly.
* Exports the models.
Progress on #76

[punet] Add integration tests.

---

sharktank/integration/models/punet/integration_test.py
sharktank/sharktank/kernels/base.py
sharktank/sharktank/kernels/batch_matmul_transpose_b.py
sharktank/sharktank/kernels/conv_2d_nchw_fchw.py
sharktank/sharktank/kernels/pooling_nchw_sum.py
sharktank/sharktank/kernels/templates/batch_matmul_transpose_b.mlir
sharktank/sharktank/kernels/templates/conv_2d_nchw_fchw.mlir
sharktank/sharktank/kernels/templates/pooling_nchw_sum.mlir
sharktank/tests/kernels/batch_matmul_transpose_b_test.py

This produces precise specializations based on the level of dynamism in use vs punning everything to fully dynamic. As a byproduct, this fixes a bug where some conv/sum kernels did not have a function signature that was sufficiently specialized, resulting in aliasing and bad kernel selection.

[quant] Dedynamize the integer kernels.

---

sharktank/integration/models/punet/integration_test.py
sharktank/sharktank/kernels/conv_2d_nchw_fchw.py
sharktank/sharktank/kernels/templates/conv_2d_nchw_fchw.mlir
sharktank/sharktank/ops/qconv_impls.py
sharktank/sharktank/utils/testing.py
sharktank/tests/kernels/conv_2d_nchw_fchw_test.py
sharktank/tests/ops/qconv_test.py

This requires less reconstruction by fusion on the compiler side and allows us to better enforce the exact type signatures that are supported.

[quant] Convert custom conv op to mixed precision.

---

sharktank/sharktank/models/punet/layers.py
sharktank/sharktank/models/punet/sharding.py
sharktank/sharktank/models/punet/testing.py
sharktank/sharktank/ops/_registry.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/sharding.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/types/theta.py
sharktank/sharktank/utils/tree.py
sharktank/tests/models/punet/resnet_test.py
sharktank/tests/models/punet/up_down_block_test.py
sharktank/tests/ops/sharded_test.py

Add sharded cat with inefficient implementation.
Allow for overriding based on a general boolean type expression in SignatureDispatcher. This is used in the cat signature dispatch where we have a collection of tensors.
Add some tree structure utilities.

Add sharding of Punet's up/down block

---

sharktank/sharktank/kernels/templates/conv_2d_nchw_fchw.mlir

This is a non-canonical form of linalg.generic because elementwise generics completely overwrite their output contents. By using an empty this removes a use of the conv and improves the ability for the compiler to optimize it.

Update the bias outs to use  for the conv_nchw template

---

docs/model_cookbook.md
sharktank/sharktank/utils/cli.py

in cli.py, `data_files` is initialized as a set, but its use makes it look like its intended to be a dict.  Also I edited the model_cookbook.md as convert.py was replaced by convert_hf_to_gguf.py

Fixed bug in cli.py

---

sharktank/sharktank/models/punet/layers.py
sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py
sharktank/sharktank/types/theta.py

This patch enables quantization activation fusion of either qkv (for MHA) or kv (for MCHA) attention layers.
In the model, this is selected based on the presence of either a `to_kv` or `to_qkv` theta on each attention layer. Normally, a LinearLayer handles all quantization inside of itself, but in this case, we decompose what the LinearLayer usually does by explicitly performing activation quantization using either qkv or kv shared input conditioning, then proceed with the normal computation and dequant.
The Brevitas import is a bit finnicky in this case because the current version of it concats the kv or qkv weights/scales/bias/zp in an attempt to only have one set of each. However, it is a more natural representation (and leaves less room for optimization failures) to simply populate …

[punet] Implement QKV quantization fusion and adapt to Brevitas mechanism.

---

docs/model_cookbook.md
sharktank/sharktank/models/llama/tools/data_utils.py
sharktank/sharktank/models/llama/tools/generate_data.py

Progress on https://github.com/nod-ai/sharktank/issues/103. Sending early for design feedback.
I want something lighter weight than https://github.com/nod-ai/sharktank/blob/main/shortfin/shortfin/llm/impl/service_v1_cli.py and https://github.com/nod-ai/sharktank/blob/main/shortfin/shortfin/llm/impl/service_v1.py to use that can generate real inputs using a tokenizer and the provided hyperparameters (e.g. batch sizes, max sequence length), for use in offline tests and benchmarks. What I'm not sure about is the state tracking in the cache. That's probably easiest to just dump from the service, but I think for prefill at least we should be able to generate something sensible here.
Anyways, this is part learning exercise for me and part useful tool for others. Looking for feedback!

Start on llama/tools/generate_data.py.

---

sharktank/integration/models/punet/integration_test.py
sharktank/sharktank/ops/attention_impls.py
sharktank/sharktank/ops/qconv_impls.py
sharktank/sharktank/ops/qlinear_impls.py
sharktank/sharktank/utils/debugging.py

Gates integer mm/conv and custom attention impl.
Subsumes the individual use_custom_int_conv_kernel and use_custom_int_mm_kernel flags.
I would like to remove this flag entirely as it is unsound, but also we are still working out bugs in our eager interop and need to have an escape hatch.

Add flag use_custom_iree_kernels (default True).

---

sharktank/sharktank/ops/attention_impls.py

`iree-compile` needs to still catch up on compilation path. Reverting on
`f16` tensors until the feature fixes.

Disable FA kernel for unquantized

---

sharktank/sharktank/types/tensors.py
sharktank/sharktank/types/theta.py

Adds flattening and unflattening of our tensor types according to torch requirements.
This allows us to pass and return such tensors when exporting functions.
Add function to populate names of tensors in a theta with the natural name corresponding to its path in the theta.
When exporting a dataset each tensor must have a unique name.
Make name a property in InferenceTensor.
Renaming of sharded tensors needs to rename the shards as well.

Allow sharktank tensors to be part of export function signatures

---

.github/workflows/ci_linux_x64-libshortfin.yml

This adds a very basic GitHub action to
* Build the IREE runtime from source (no caching, not using any of
IREE's `build_tools/cmake/*.sh` scripts yet)
* Build libshortfin
* Run libshortfin tests via CMake

Add GH workflow to test libshortfin

---

libshortfin/examples/python/http/http_server.py

This is just demonstrating with an example for the moment but we can bake out the FastAPIResponder to a helper class.
The basic idea is that the shortfin world is one of devices, topologies, light-weight processes and queues, while the web server world is (mostly) single-threaded I/O loops. By letting us package a FastAPI (i.e. starlette/uvicorn) request/response as a message on a queue and disconnect it from the request/response cycle, we can perform arbitrary workflows on it and respond either one-shot or streaming as we go without worrying overly much about the different threading models, etc.

[shortfin] Bridge shortfin processes to FastAPI.

---

.github/workflows/ci_linux_x64-libshortfin.yml
libshortfin/CMakeLists.txt
libshortfin/bindings/python/lib_ext.cc
libshortfin/src/CMakeLists.txt

Introduces an `SHORTFIN_SYSTEMS_AMDGPU` option to allow building
libshortfin for host-only systems. The option defaults to ON.

[libshortfin] Introduce `SHORTFIN_SYSTEMS_AMDGPU`

---

.github/workflows/ci_linux_x64-libshortfin.yml
libshortfin/tests/amdgpu_system_test.py
libshortfin/tests/examples/fastapi_test.py

With the Python tests are executed in the CI via pytest. Tests that are
not capable to run due to missing hardware are not executed whereas
failing test that are expected to pass in the future are currently
marked xfail.

Execute Python tests in CI

---

.github/workflows/ci_linux_x64-libshortfin.yml
libshortfin/CMakeLists.txt

Only get shallow copies of all repositories cloned as bundeled dep or in the CI. For `actions/checkout` the fetch depth defaults to `1`.

[libshortfin] Shallow clone git repositories

---

sharktank/sharktank/types/gguf_interop/base.py

All numpy arrays are automatically converted to fake tensors. To support reshape constants we need to ensure that they are cast to integers first.

[quant] Prevent faketensoring shape values

---

.github/workflows/ci_linux_x64_asan-libshortfin.yml
libshortfin/CMakeLists.txt
libshortfin/requirements-tests.txt

This adds a GitHub action to build a debug/asan version of libshortfin. Shallow cloning of dependencies obtained via FetchContent is reverted as the dependencies cannot be fetched in the CI.
Depends on #148

[libshortfin] Build debug/asan

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/layers/causal_llm.py
sharktank/sharktank/layers/rotary_embedding.py
sharktank/sharktank/models/llama/llama.py

When exporting, it is better to leave table construction to be dynamic and let the compiler move things to initialization time (versus materializing large tables, which can be max_context_length^2). We set static_tables=False unconditionally on export while leaving it True for eager use.
Contains a workaround for #156.

[llama] Explicit option to use static tables.

---

.github/workflows/ci_linux_x64-libshortfin.yml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
libshortfin/CMakeLists.txt
libshortfin/bindings/python/array_binding.cc
libshortfin/examples/python/mobilenet_server/inference_system.py
libshortfin/src/shortfin/array/array.h
libshortfin/src/shortfin/array/storage.cc
libshortfin/src/shortfin/array/storage.h
libshortfin/src/shortfin/local/scheduler.cc
libshortfin/src/shortfin/local/scheduler.h
libshortfin/src/shortfin/local/scope.cc
libshortfin/src/shortfin/local/scope.h
libshortfin/src/shortfin/local/system.cc
libshortfin/src/shortfin/support/blocking_executor.cc
libshortfin/src/shortfin/support/blocking_executor_test.cc
libshortfin/src/shortfin/support/iree_concurrency.h
libshortfin/src/shortfin/support/iree_helpers.cc
libshortfin/src/shortfin/support/iree_helpers.h
libshortfin/src/shortfin/support/iree_helpers_test.cc
libshortfin/src/shortfin/support/logging.h

Prior to this, TimelineResource held a raw C++ reference to the scope but did not hold a shared_ptr ref to it. The storage class, which holds buffers alive, was keeping the raw IREE buffer and device alive but not the shortfin object hierarchy. On the happy path, this does not cause issues, but during abnormal termination and other race conditions, it can cause lifetime problems.
Here we:
* Make TimelineResource hold a std::shared_ptr<Scope>, which transitively keeps everything alive that can be accessed.
* Clean up incorrect ordering of fields in key classes, which could cause dependent objects to be destroyed out of order.
* Remove cases in iree::object_ptr which could have resulted in incorrect accounting in certain scenarios.
* Adds compile-time flags to perform verbose shortfin …

[shortfin] Make TimelineResource hold scopes alive.

---

.github/workflows/ci_linux_x64-libshortfin.yml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
libshortfin/CMakeLists.txt
libshortfin/bindings/python/CMakeLists.txt
libshortfin/build_tools/cmake/shortfin_library.cmake
libshortfin/build_tools/python_lsan_suppressions.txt
libshortfin/pyproject.toml
libshortfin/requirements-tests.txt

* Disables ASAN ODR check properly (had syntax error in env var).
* Builds non-debug Python.
* Sets up LSAN suppressions to account for non-debug Python intentional leaks.
* Has CMake fetch the correct nanobind vs relying on pip (had another incident of mismatched version).
* Added options SHORTFIN_BUILD_STATIC=OFF, SHORTFIN_BUILD_DYNAMIC=ON, and SHORTFIN_LINK_DYNAMIC to control variants of libraries produced and linked to (disabling static in most configs saves a lot of build time).
* Run pytest with `-s` (stream output) option. For some reason, some of the subprocess tests are otherwise not working right on GHA runners. It looks like there may be some malformed I/O somewhere that gets less reliable with redirection. This isn't solved but does increase the chance of passing.

[libshortfin] Clean up a few CI related items.

---

.github/workflows/ci_linux_x64-libshortfin.yml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
libshortfin/CMakeLists.txt
libshortfin/requirements-iree-compiler.txt

Pins IREE checkout in the CI or obtained via FetchContent to the same specified version. Furthermore, installs the iree-compiler in the CI.

Pin IREE to specific version

---

sharktank/sharktank/types/gguf_interop/base.py

Using `torch.as_tensor` we can alias the tensor rather than copy during gguf file loading. This avoids duplicating the entire tensor contents when tracing torch programs which substrantially decreases memory usage on large models.
e.g. LLaMa 70b decreased memory allocation from 60+GB to 2 GB for tensors.

Alias gguf tensors instead of copy

---

sharktank/sharktank/examples/export_paged_llm_v1.py

Strictness validates correctness but this results in loading the tensors to memory. Disabling helps with export speed.

Disable strictness for export of llama

---

.github/workflows/ci_linux_x64-libshortfin.yml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
libshortfin/README.md
libshortfin/build_tools/python_lsan_suppressions.txt
libshortfin/pyproject.toml
libshortfin/requirements-tests.txt
libshortfin/src/shortfin/local/system.cc
libshortfin/src/shortfin/local/system.h
libshortfin/tests/amdgpu_system_test.py
libshortfin/tests/conftest.py
libshortfin/tests/invocation/conftest.py
libshortfin/tests/invocation/mobilenet_program_test.py

This test is not particularly inspired (and the API needs to be simplified) but it represents the first full system test in the repo.
In order to run the test, it is downloading a mobilenet onnx file from the zoo, upgrading it, and compiling. In the future, I'd like to switch this to a simpler model like MNIST for basic functionality, but I had some issues getting that to work via ONNX import and punted. While a bit inefficient (it will fetch on each pytest run), this will keep things held together until we can do something more comprehensive. Note that my experience here prompted me to file https://github.com/iree-org/iree/issues/18289, as this is way too much code and sharp edges to compile from ONNX (but it does work). Verifies numerics against a silly test image.
Includes some fixes: …

[libshortfin] Add simple invocation test.

---

.github/workflows/ci_linux_x64_asan-libshortfin.yml

With the change to call ctest directly, `--output-on-failure` was added as a command line argument.

[libshortfin] Remove env var

---

sharktank/sharktank/ops/_registry.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/ops_test.py
sharktank/tests/ops/sharded_test.py

We are encoding the device/shard information in the flow.tensor.transfer/transfer_to_logical_device
operation. Then if we do an all-gather or an all-reduce, CSE is happy to collapse the expressions into one. This would result in the all-gather/all-reduce being performed on one device and then the result is copied to the rest. We want each device to do the all-gather/all-reduce.
There is no easy way to test the desired effect, but at least we test for correctness on the PyTorch level.
This change adds the all_reduce op that is currently not used anywhere.
Here is expanded the elementwise op to support a variable number of tensor arguments.

Place args for all gather/reduce on devices before the op to avoid CSE and excessive copying

---

libshortfin/CMakeLists.txt

https://github.com/nod-ai/sharktank/pull/177 broke building iree as a bundled dep. This is due to differences between `FetchContent_MakeAvailable` and `FetchContent_Populate`, where the former does `add_subdirectory` on the downloaded target while the latter doesnt. This patch sets IREE flags before the call to `FetchContent_MakeAvailable`, so we have the right flags enabled for `add_subdirectory`.

[libshortfin] Fix CMake bundled iree build

---

sharktank/sharktank/examples/export_paged_llm_v1.py

We need to set the `use_hf` attribute for LlamaModelConfig when exporting the IR's because the params from gguf do not include the `use_hf` attribute. Fixes the export error below:
```
Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/avsharma/sharktank/sharktank/sharktank/examples/export_paged_llm_v1.py", line 226, in <module>
main()
File "/home/avsharma/sharktank/sharktank/sharktank/examples/export_paged_llm_v1.py", line 64, in main
model = PagedLlamaModelV1(dataset.root_theta, llama_config)
File "/home/avsharma/sharktank/sharktank/sharktank/models/llama/llama.py", line 130, in __init__ …
```

Set use_hf attribute in LlamaConfig of `export_paged_llm_v1` to fix export error

---

libshortfin/build_tools/cmake/shortfin_library.cmake
libshortfin/src/CMakeLists.txt

With this the static as well as the dynamic library can be build at the same time. However, the version / so version should only be set on the dynamic library and only if that library is build.
Supersedes #187.

[libshortfin] Only set (so)version on dynamic libs

---

sharktank/sharktank/types/tensors.py

Fixes this error from `dump_gguf` when converting gguf to irpa for llama3 8B Q4_1. Currently the to_planar function returns a PlanarQuantizedTensor without keyword arguments, but the PlanarQuantizedTensor __init__ method expects only keyword arguments.
```
Saving to: ../llama8b_q4_1.irpa
Save: Add PrimitiveTensor(rope_freqs.weight, [64], torch.float32)
Save: Add Q4_1(token_embd.weight, [128256, 4096])
Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/avsharma/sharktank/sharktank/sharktank/tools/dump_gguf.py", line 91, in <module>
main()
File …
```

Fixes TypeError in `dump_gguf` when converting Q4_1 gguf to irpa

---

libshortfin/CMakeLists.txt
libshortfin/python/lib_ext.cc
libshortfin/src/shortfin/local/async.h
libshortfin/src/shortfin/local/messaging.cc
libshortfin/src/shortfin/local/messaging.h
libshortfin/src/shortfin/local/system.cc
libshortfin/src/shortfin/local/system.h
libshortfin/src/shortfin/support/iree_concurrency.h

* When Message instances had lifetime management transferred to Python, destruction of the mutex would happen while it was held, causing an assert. I believe this was only happening in some process level GC scenarios before and was being masked. But it is also possible that it is the cause of our spurious crashes.
* While this fix made sense once I found it, I also took the change to get clang `-Wthread-safety` analysis working and wired up to a few of the trickiest pieces of thread safety code.
* This revealed real bugs and design issues that are now fixed.

[libshortfin] Fix illegal nested lock access in Message destruction.

---

libshortfin/python/CMakeLists.txt
libshortfin/python/_shortfin/__init__.py

This brings pylance back to life for the native bindings. It was giving confusing error squiggles about not being able to use types that were variables, but the root cause was that the backing stubs were not generated properly for all of the module.
Includes a couple of other typing tweaks that were found to be helpful.

[libshortfin] Fix python stub generation.

---

libshortfin/python/array_binding.cc
libshortfin/tests/api/array_test.py

This patch adds device_array.items. Also updates tests to use device_array.items instead of str().

[libshortfin] Add device_array.items

---

libshortfin/examples/python/async/queue.py
libshortfin/examples/python/fastapi/server.py
libshortfin/python/_shortfin/asyncio_bridge.py
libshortfin/python/array_binding.cc
libshortfin/python/lib_ext.cc
libshortfin/python/lib_ext.h
libshortfin/python/shortfin/__init__.py
libshortfin/python/shortfin/interop/fastapi/__init__.py
libshortfin/python/shortfin/support/deps.py
libshortfin/python/shortfin/support/logging_setup.py
libshortfin/src/shortfin/array/array.cc
libshortfin/src/shortfin/local/CMakeLists.txt
libshortfin/src/shortfin/local/async.h
libshortfin/src/shortfin/local/messaging.cc
libshortfin/src/shortfin/local/messaging.h
libshortfin/src/shortfin/local/process.cc
libshortfin/src/shortfin/local/process.h
libshortfin/src/shortfin/local/program.cc
libshortfin/src/shortfin/local/program.h
libshortfin/src/shortfin/local/scheduler.cc
libshortfin/src/shortfin/local/scheduler.h
libshortfin/src/shortfin/local/scope.cc
libshortfin/src/shortfin/local/scope.h
libshortfin/src/shortfin/local/system.cc
libshortfin/src/shortfin/local/system.h
libshortfin/src/shortfin/support/CMakeLists.txt
libshortfin/src/shortfin/support/iree_helpers.h
libshortfin/src/shortfin/support/logging.h
libshortfin/tests/examples/async_test.py
libshortfin/tests/local_scope_test.py

Core:
* Convert Queue to shared ownership.
* Allow creation of anonymous Queues.
* Adds asyncio loop support for `call_at`
* Fixes `VoidFuture::set_success` to also signal callbacks
* Adds `StaticProgramParameters` and ability to construct a `ParameterProvider`
* Fixes the hacky `Account::OnSync()` to return a `VoidFuture` and use it to route any wait error (instead of aborting)
Bindings:
* Adds `name` and `compute_dense_nd_size` bindings to `DType`
* Makes `Process` subclassing more natural by supporting split new/init (allows arbitrary arguments to the subclass constructor)
* Disables nanobind leak detector in debug builds of CPython (it seems to rely on immortalization of certain identifiers which are properly cleaned up in debug builds but left allocated forever in release builds)
* …

[libshortfin] Rollup of API changes and fixes to support the LLM server.

---

libshortfin/src/shortfin/local/scheduler.cc
libshortfin/src/shortfin/local/systems/host.cc
libshortfin/tests/examples/async_test.py

As written, command buffers could be scheduled out of order (with signal < deps). We need a more enlightened scheduler soon, but for the moment, this makes it correct.
Also sets the IREE runtime IREE_TASK_SCOPE_FLAG_ABORT_ON_FAILURE in debug builds, which will cause an eager assert-like crash. Since in our usage, this is always a critical error, it makes sense to treat it like an assert (and I would like to add finer grained control in the future). In release builds, it will propagate as a soft error, but it is basically fatal as it will lock the accounting structures into a persistent error state.
Fixes #178

[libshortfin] Add missing scheduler dependency.

---

libshortfin/python/array_binding.cc
libshortfin/tests/api/array_storage_test.py
libshortfin/tests/api/array_test.py
libshortfin/tests/invocation/mobilenet_program_test.py

After a bit of use, I decided that some of the array API around fill and mappings needed some rework:
* Clarified that device_array.fill is asynchronous.
* Implemented `fill` and `items` on `mapping`, which matches the semantics of what they do (i.e. accessing mappable contents in a synchronous fashion).
* Implemented `mapping.fill` to operate either on a buffer pattern or primitive types.
* Made `device_array.items` an alias for `mapping.items`, mainly for convenience.

[libshortfin] Rework array mapping python bindings.

---

libshortfin/python/array_binding.cc
libshortfin/src/shortfin/array/array.cc
libshortfin/tests/api/array_test.py

We were incorrectly truncating the view on inner index access. Used the newer APIs for data manipulation to construct a test which better validates. Kept the original test, even though it is not comprehensive.
Also adds arg names to the array constructor.

[shortfin] Fix nd array view indexing bug.

---

sharktank/sharktank/kernels/templates/flash_attention.mlir

With this patch for masked attention in iree (https://github.com/iree-org/iree/commit/9ee061d2ec366e955f2a348225b4051a31f8f244), the attention's scale also requires an indexing map. This commit adds the appropriate indexing map to the template IR for flash attention.

Update Flash Attention Custom Op Template MLIR

---

libshortfin/python/CMakeLists.txt
libshortfin/python/array_binding.cc
libshortfin/python/array_host_ops.cc
libshortfin/python/lib_ext.h
libshortfin/python/shortfin/array.py
libshortfin/src/shortfin/array/array.cc
libshortfin/src/shortfin/array/array.h
libshortfin/src/shortfin/array/dims.h
libshortfin/src/shortfin/array/dtype.h
libshortfin/src/shortfin/array/storage.cc
libshortfin/src/shortfin/array/storage.h
libshortfin/tests/api/array_ops.py
libshortfin/tests/api/array_ops_test.py

Adds `shortfin.array.argmax`, following closely to numpy conventions.
In the C++ implementation, this forced completion of some APIs around accessing shortfin arrays via xtensor. 
C++ based users will just use the `device_array::map_xtensor*` helpers to access xtensor expressions directly.
For Python, we export select eager op kernels to match common situations. The intent here is to just be able to do some lightweight algebra and data manipulation common in host-side ML (without deps).

[shortfin] Add argmax host op.

---

libshortfin/CMakeLists.txt

This is a workaround for https://github.com/nod-ai/SHARK-Platform/issues/211 while I/we find a way to enable dynamic linking builds on Windows.
With this and https://github.com/nod-ai/SHARK-Platform/pull/210, I can configure and build libshortfin on Windows using default CMake options and the CMake that `pip install -v -e .` runs internally. The local package build passes an initial smoketest too (can run `import shortfin` and poke around in the python interpreter).

Set linking mode to static by default on Windows.

---

libshortfin/python/lib_ext.cc
libshortfin/src/shortfin/local/device.cc
libshortfin/src/shortfin/local/device.h
libshortfin/src/shortfin/local/system.h
libshortfin/src/shortfin/local/systems/amdgpu.cc
libshortfin/src/shortfin/local/systems/host.cc
libshortfin/src/shortfin/local/systems/host.h
libshortfin/src/shortfin/support/CMakeLists.txt
libshortfin/src/shortfin/support/config.cc
libshortfin/src/shortfin/support/config.h
libshortfin/src/shortfin/support/iree_helpers.h
libshortfin/tests/conftest.py
libshortfin/tests/host_cpu_system_test.py
libshortfin/tests/local_scope_test.py

On NUMA systems, a NUMA node maps to a device queue, which manifests as a Shortfin Device. On non-NUMA systems, options can be used to control the concurrency.
Also drops the `Device::node_locked` field and replaces it with `capabilities`, which is needed in order to create better data transfer APIs.

[libshortfin] Implement multi-device CPU system config.

---

.github/workflows/ci_linux_x64_nogil-libshortfin.yml
libshortfin/requirements-tests-nogil.txt

This adds a seperate, and therefore temporary, workflow to run with a free-threaded Python which should be embedded into a matrix strategy.
To fully enable testing without the GIL, it is required to declare that `_shortfin_default.lib` can either be safley run without it or to run with `PYTHON_GIL=0`.

[libshortfin] Add a workflow with disabled GIL

---

libshortfin/src/shortfin/local/messaging.h
libshortfin/src/shortfin/local/systems/host.cc

Fixes https://github.com/nod-ai/SHARK-Platform/issues/215

[libshortfin] Build fixes for gcc 12.3.0 and 13.2.0.

---

libshortfin/README.md
libshortfin/setup.py

Progress on https://github.com/nod-ai/SHARK-Platform/issues/130
Reference: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

[libshortfin] Fix standalone Python package build to include subpackages.

---

libshortfin/README.md
libshortfin/setup.py

Reverts nod-ai/SHARK-Platform#223
This broke a build: https://github.com/nod-ai/SHARK-Platform/actions/runs/11058808130/job/30725674259#step:9:86
```
ImportError while loading conftest '/home/runner/work/SHARK-Platform/SHARK-Platform/libshortfin/tests/conftest.py'.
tests/conftest.py:10: in <module>
import shortfin as sf
E   ModuleNotFoundError: No module named 'shortfin'
```

Revert "[libshortfin] Fix standalone Python package build to include subpackages."

---

.github/workflows/ci_linux_x64_nogil-libshortfin.yml
libshortfin/README.md
libshortfin/build_tools/python_lsan_suppressions.txt
libshortfin/python/CMakeLists.txt
libshortfin/python/_shortfin/asyncio_bridge.py
libshortfin/tests/examples/fastapi_test.py

* Fixes a method signature issue that manifested on 3.13 generally (not FT related).
* Bumps nanobind to a recent HEAD commit to pick up free threaded support.
* Adds nanobind option to enable free threading if building for a CPython with it enabled.
* Adds a README stanza advising on how to acquire a free threaded CPython.
* Makes fastapi tests skip if deps not met (not yet available / hard to install).
* Adds an LSAN exclusion for something unrelated that has snuck in.
* Sets FT CMAKE_BUILD_TYPE=Debug in the CI.
Note that on the large NUMA system I was testing on, the CPU test which creates an executor on each NUMA node for all processes exceeded the default file handle ulimit, requiring it to be increased. I assume that the FT CPython internally uses more synchronization handles and it …

[shortfin] Fix issues with free threaded Python builds.

---

libshortfin/setup.py

Now the log messages match what is actually checked.

[libshortfin] Fix `SHORTFIN_ENABLE_TRACING` typo.

---

libshortfin/README.md
libshortfin/setup.py

Progress on https://github.com/nod-ai/SHARK-Platform/issues/130.
This reverts https://github.com/nod-ai/SHARK-Platform/pull/224 to re-land https://github.com/nod-ai/SHARK-Platform/pull/223.
This now uses `SOURCE_DIR` instead of `SETUPPY_DIR` to fix package discovery when running in pre-built mode, which will fix the errors reported on CI:
```
ImportError while loading conftest '/home/runner/work/SHARK-Platform/SHARK-Platform/libshortfin/tests/conftest.py'.
tests/conftest.py:10: in <module>
import shortfin as sf
E   ModuleNotFoundError: No module named 'shortfin'
```
Logs from a failed build:
```
setup.py running in pre-built mode:
SOURCE_DIR = /home/runner/work/SHARK-Platform/SHARK-Platform/libshortfin
BINARY_DIR = /home/runner/work/SHARK-Platform/SHARK-Platform/libshortfin/build
Found …
```

[libshortfin] Re-land "Fix standalone Python package build to include subpackages."

---

sharktank/sharktank/layers/rotary_embedding.py

Fixes are in so we no longer require static tables. We can now respect the construction param.

Disable static rotary tables

---

libshortfin/CMakeLists.txt
libshortfin/build_tools/cmake/shortfin_library.cmake
libshortfin/python/lib_ext.cc
libshortfin/src/CMakeLists.txt
libshortfin/src/shortfin/local/system.h
libshortfin/src/shortfin/local/systems/CMakeLists.txt
libshortfin/src/shortfin/local/systems/factory.cc
libshortfin/src/shortfin/support/config.cc
libshortfin/src/shortfin/support/config.h
libshortfin/tests/amdgpu_system_test.py
libshortfin/tests/host_cpu_system_test.py

Prior usage required callers to switch to know which SystemBuilder class to create. That option of construction is still available and has more explicitness.
This patch adds C++ APIs for construction of a SystemBuilder by type_name and a shorthand on the System class to have a one line create. Also reworks the config undef checking to be consistent and make it possible to warn instead of throw an exception.
In Python, this is exposed by the System class getting a constructor, so now a one-liner like `with sf.System("hostcpu", option1="value", ...):` is possible. This should compose well with flags and application code.

[shortfin] Make system construction selectable by type name.

---

shortfin/README.md

Updates the native C++ build instructions (`pip install` finishes "successfully" even if the project was only configured and no libs were built) and simplifies the instructions on how to get a free-threaded Python.

[shortfin] Update README

---

.github/workflows/ci_linux_x64-libshortfin.yml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
.github/workflows/ci_linux_x64_nogil-libshortfin.yml

Instead of changing into the directories, the working directories are now set in the jobs.

[shortfin] Refactor to avoid changing directories

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/types/tensors.py
sharktank/tests/models/llama/sharded_llama_test.py

Add test that exports to MLIR a small sharded Llama model
The decode step requires exporting in non-strict torch mode due to
https://github.com/pytorch/pytorch/issues/135061
This export required to extend the registration functionality of our custom
tensor types by provinding `flatten_with_keys_fn`. This is also required
to bump the PyTorch version to >=2.4 for other export tests.
The export to MLIR fails with
TypeError: Unsupported torch type conversion for !torch.vtensor<[3,1,7],complex<f32>>
Needs further debugging.
Detailed error [here](https://github.com/user-attachments/files/17163454/sharded-llama-export-to-mlir-failure.txt).

Add test that exports to MLIR a small sharded Llama model

---

sharktank/tests/models/llama/sharded_llama_test.py

https://github.com/iree-org/iree-turbine/pull/175
solves the failing export.

Remove xfail from sharded Llama export to MLIR test

---

shortfin/README.md
shortfin/build_tools/build_linux_package.sh

Progress on https://github.com/nod-ai/SHARK-Platform/issues/130
This is forked from
* https://github.com/llvm/torch-mlir/blob/main/build_tools/python_deploy/build_linux_packages.sh
* https://github.com/iree-org/iree/blob/main/build_tools/python_deploy/build_linux_packages.sh
TODO (future PRs?):

[libshortfin] Add package build script for Linux using manylinux.

---

tuner/examples/dispatch/.gitignore
tuner/examples/dispatch/README.md
tuner/examples/dispatch/__init__.py
tuner/examples/dispatch/__main__.py
tuner/examples/dispatch/compile_dispatch.sh
tuner/examples/dispatch/config_epilog.mlir
tuner/examples/dispatch/config_prolog.mlir
tuner/examples/dispatch/dispatch_tuner.py
tuner/examples/dispatch/mmt.mlir
tuner/tuner/libtuner.py

The new example can be used to tune a single dispatch in isolation and does not require setting up model build/execution scripts.
Dispatch tuner is designed to be self-contained and does not require any extra input-specific scripts or files.
This is stacked on top of https://github.com/nod-ai/SHARK-Platform/pull/251

[tuner] Add single dispatch tuner example

---

sharktank/conftest.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/utils/iree.py
sharktank/tests/models/llama/sharded_llama_test.py

Add pytest CLI option for overriding the temporary test directory. If the option is provided dump MLIR, VMFB, function call arguments and results. Move numerical checks at the end of the test.
Add some basic functionality to run multi-device IREE functions with tracing.

Add dumping of reproducer for toy sharded llama test

---

sharktank/tests/layers/sharded_conv2d_with_iree_test.py
sharktank/tests/models/punet/sharded_resnet_block_with_iree_test.py

The fix https://github.com/iree-org/iree-turbine/pull/205 solves the issue with this test.
Xfail the Unet Resnet block test with maybe low accuracy.

Enable check for sharded Conv2D test

---

tuner/examples/dispatch/dispatch_tuner.py
tuner/examples/punet/punet_autotune.py
tuner/tuner/libtuner.py
tuner/tuner/libtuner_test.py

- Adds `extract_benchmark_from_run_result` method to help in fetching the "benchmarks" data
- Updates `IREEBenchmarkResult` model to reflect that the result is no longer stored as string but as a list of benchmarks
- Updates the parsing of dispatches and models to read from Json
- Updates tests to verify that `get_mean_time` functions as expected
- Updates tests to verify that Json data is properly parsed and processed

[tuner] Use JSON for benchmark output

---

.github/workflows/ci-tuner.yml

Updates the checkout action as this uses a deprecated Node.js version and the old version will therefore be forced to run on node20. Further pins actions as suggested byt OpenSSF Scorecard, see https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies.

Pin (and update) actions

---

sharktank/tests/layers/sharded_rotary_embedding_test.py

We should be able to validate the sharded rotary table via comparison with the unsharded version. This runs the sharded and unsharded implementations, asserting near identical results.

[sharktank] Add test for sharded rotary table

---

sharktank/sharktank/layers/rotary_embedding.py

Some minor changes to the rotary embedding can better support fusion and avoid using a lookup table. Depending on backend one version may provide better overall performance.

Rework RotaryEmbedding for dynamic computation

---

.github/workflows/ci_windows_x64-libshortfin.yml

Adds a Windows CI for shortfin. Building passes (with several warnings) but not all ctests and pytests do. As soon as we have passing tests, the CI configuration should be merged with the Linux CI into a matrix configuration.

Add ci_windows_x64-libshortfin.yml

---

sharktank/sharktank/export_layer/export_moe.py
sharktank/sharktank/layers/__init__.py
sharktank/sharktank/layers/ffn_moe_block.py
sharktank/sharktank/layers/llama_attention_block.py
sharktank/sharktank/layers/mixture_of_experts_block.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/grok/grok.py
sharktank/sharktank/models/llama/llama.py
sharktank/sharktank/models/llama/llama_ref.py
sharktank/sharktank/models/mixtral/mixtral.py
sharktank/sharktank/models/mixtral/mixtral_ref.py
sharktank/sharktank/utils/tokenizer.py
sharktank/tests/models/llama/moe_block_test.py

Many of these features can toggle between depending on architecture. Replumbing the configurations separately allows better reuse and understanding of how models vary between eachother.
grok uses a softcap, plumbing a value enables `sc * tanh( v / sc)` grok has some hardcoded values that have better representations, e.g. `sqrt(6144)` and `sqrt(3)`.
output normalization is optional but used by mixtral. Presence of the tensor is sufficient for performing the normalization.

Refactor llama / mixtral / grok for shared features

---

shortfin/tests/api/array_storage_test.py

Follow-up to https://github.com/nod-ai/SHARK-Platform/pull/269.
Something about this error handling is crashing the process without useful logs: https://github.com/nod-ai/SHARK-Platform/actions/runs/11373400662/job/31639876327?pr=288#step:9:131
Until we can debug that further, skip the affected tests on Windows.

Skip crashing shortfin python tests on Windows.

---

shortfin/src/shortfin/support/iree_helpers_test.cc

Follow-up to https://github.com/nod-ai/SHARK-Platform/pull/269.
When using a debug build on Windows, status messages contain callstacks. These tests were assuming that the messages would be less helpful ;)
https://github.com/nod-ai/SHARK-Platform/actions/runs/11372553655/job/31637136796#step:9:104
```
21/32 Test #21: iree_error.user_message ......................***Failed    0.46 sec
Running main() from D:\a\SHARK-Platform\SHARK-Platform\iree\third_party\googletest\googletest\src\gtest_main.cc
Note: Google Test filter = iree_error.user_message
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from iree_error
[ RUN      ] iree_error.user_message
D:\a\SHARK-Platform\SHARK-Platform\shortfin\src\shortfin\support\iree_helpers_test.cc …
```

Fix iree_helpers_test on Windows with callstacks (debug build).

---

sharktank/sharktank/kernels/batch_matmul_transpose_b.py
sharktank/sharktank/kernels/conv_2d_nchw_fchw.py
sharktank/sharktank/kernels/templates/batch_matmul_transpose_b.mlir
sharktank/sharktank/models/punet/tools/import_brevitas_dataset.py
sharktank/sharktank/ops/qconv_impls.py
sharktank/sharktank/ops/qlinear_impls.py
sharktank/tests/ops/qconv_test.py

This is a follow-up to (https://github.com/nod-ai/SHARK-Platform/pull/202) which injects fp8 linear and convolution kernels in punet.

Add fp8 quantization for conv and linear layers

---

shortfin/tests/host_cpu_system_test.py

Not sure about `test_create_host_cpu_system_topology_nodes_all`. That crashes on my system without any helpful logs.
Error logs from `test_create_host_cpu_system_env_vars`: https://github.com/nod-ai/SHARK-Platform/actions/runs/11387733742/job/31683030188#step:9:1610

Skip failing host_cpu_system_test tests on Windows.

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/utils/misc.py
sharktank/tests/ops/sharded_test.py

Some cases of inserting dimensions of size 1 were buggy. Added some more tests.

Fix reshaping of split sharded tensor

---

.github/workflows/ci_eval.yaml

Update default CI timeout from 6 to 10 hrs

[sharktank] Evaluation - Update timeout for Perplexity CI test

---

shortfin/python/array_host_ops.cc
shortfin/python/shortfin/array.py
shortfin/tests/api/array_ops_test.py

For this, I opted to only support in-place variants since in shortfin, we generally operate directly on arrays vs forcing copies or having a lot of options in constructors for managing the device assignment. Otherwise, the definition of randn matches torch.randn.
Fixes #261.

[shortfin] Implements RandomGenerator and fill_randn.

---

sharktank/sharktank/examples/sharding/export_ffn_net.py
sharktank/sharktank/types/tensors.py

We should only invoke `flow.tensor.transfer` manually or when 100% required. Invoking during each construction can result in transferring from device_0 to device_0 needlessly. It also assumes that sharding always occurs on devices 0...n when sharding + pipelining could shard across differing devices.
export_ffn_net.py shows how the replication should be defined on input and not inferred.

Fix `flow.tensor.transfer` placement

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/sharded_test.py

This makes the code compatible with the change
https://github.com/iree-org/iree-turbine/pull/239
Avoid transfers in all gather/reduce for same shard/device tensors. This removes one unnecessary transfer per device.

Harmonize ops/tests with non-in-place transfer even for eager

---

sharktank/sharktank/export.py
sharktank/sharktank/utils/misc.py
sharktank/sharktank/utils/testing.py
sharktank/tests/export_test.py

We don't have handling of device affinties for our sharded tensor types when they are the arguments of exported functions. Although, they can be specified explicitly when exporting, this change adds the ability to hide this and deduces the affinties from the tensor types.

Add exporting with argument device affinities

---

.github/workflows/ci-llama.yaml
sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/tests/models/llama/benchmark_amdgpu_tests.py

This PR changes the benchmarking CI machine from the `A30F` machine to the `SharkMi300X` machine for Llama 8b, 70b, and 405b decomposed and non-decomposed sdpa. It also changes the schedule of the CI run from 2:00 AM PT to 10:00 PM PT and fixes the `argument_device_affinities` keyword to `arg_device` instead.

Update Llama Benchmarking CI machine, test paths, and schedule

---

sharktank/tests/models/llama/sharded_llama_test.py

When strict it fails due to having the UnreducedTensor not being registered in torch.

Make toy-sized Llama export non-strict

---

sharktank/sharktank/export.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/utils/iree.py
sharktank/sharktank/utils/testing.py
sharktank/tests/models/llama/sharded_llama_test.py

Make export function also accept kwargs, not just args.
Add test skip decorator that uses an env var to disable test skipping.
Circumvent the problem that iree.runtime.DeviceArray.to_host() caches its result.
Register the UnreducedTensor type in torch.
Add replicate for split sharded tensor.
Make shared_cat transfer to device 0 before doing the cat.

Fix conversion to stream issues and make toy-sized sharded Llama compile and run

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/types/tensors.py
sharktank/tests/types/tensors_test.py

This adds some default device affinities to loaded sharded tensors. This still needs to be updated for a configurable allocation but enables our current models to run on per-tensor parallelism.

Add device affinity to sharded tensors

---

.github/workflows/ci-llama.yaml

Forgot to remove llama benchmarking CI on pull_request for testing purposes.

Remove llama benchmarking CI on pull_request

---

sharktank/sharktank/layers/causal_llm.py

Addition of booleans is performing xor which breaks causal mapping.

Addition of booleans is currently wrong in iree-compile

---

sharktank/sharktank/examples/export_paged_llm_v1.py

Before work on unifying the cache interfaces there are some differences between sharded, direct and paged caches.
The direct cache uses a list of tensors for each transformer block while paged cache has on slab and paged sharded expect a list of shards.

Fix difference of LLM export for the direct vs paged cache

---

.github/workflows/ci-sharktank.yml
.github/workflows/ci_eval.yaml
requirements-dev.txt
requirements.txt
sharktank/requirements-tests.txt
sharktank/requirements.txt
sharktank/setup.py

Moves dependencies defined in the root `requirements.txt` to `sharktank/` and splits out test only deps to `requirements-tests.txt` file. Dependencies only used for development / in the CI are moved to `requirements-dev.txt` and the root requirements file is now used to pull in all the deps. Furthermore, some no longer used dependencies are removed.

Revise and split requirements files

---

shortfin/python/lib_ext.cc
shortfin/src/shortfin/local/fiber.h
shortfin/src/shortfin/local/program.cc
shortfin/src/shortfin/local/program.h
shortfin/tests/invocation/conftest.py
shortfin/tests/invocation/mobilenet_program_test.py

API changes:
* sf.Program(..., fiber=) no longer takes a fiber. The fiber is now moved to the invocation (i.e. function(..., fiber=)
* sf.Program now requires an explicit devices= (as opposed to implicitly inferring this from the fiber). The prior behavior can be achieved by sf.Program(, devices=fiber.raw_devices).
Semantic changes:
* Programs are now created with an isolation level (NONE, PER_FIBER, PER_CALL), defaulting to PER_FIBER. The prior behavior was like NONE.
* In PER_FIBER mode, only one in-flight call to a program can happen at a time on a single fiber. When a program is used across fibers, each fiber will get their own context fork (which is a light-weight clone of the context that shares immutable data).
* In PER_CALL mode, backing contexts are pooled on each calling fiber …

[shortfin] Implement fiber local program forking.

---

sharktank/sharktank/layers/kv_cache.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/types/tensors.py
sharktank/tests/layers/kv_cache_test.py
sharktank/tests/layers/sharded_paged_kv_cache_test.py

Made the interfaces of both caches line up. This allows us to interface with the caches via their utility functions instead of modifying the model behavior. Some roughness still exists in their parameters but the irrelevant details are ignored for each implementation.
Need to still add some slicing / ignoring on the page ids to make more flexible.

[llama] Update kv cache to have read/write functions

---

shortfin/src/shortfin/support/iree_helpers.cc
shortfin/src/shortfin/support/iree_helpers.h

* Just eagerly serializes the exception. Trying to defer this makes the type non copyable and is a dubious optimization given that we never use this type for flow control.
* Should fix MSVC warnings and ill-defined behavior there.

[shortfin] Make error copyable.

---

sharktank/sharktank/layers/kv_cache.py

Needed to materialize the batch index write dimension to write for timestep.

[sharktank] Fix `write_timestep` for direct cache

---

.github/workflows/ci-sdxl.yaml
.github/workflows/ci_linux_x64-libshortfin.yml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
.github/workflows/ci_linux_x64_nogil-libshortfin.yml
shortfin/CMakeLists.txt

Received following error when attempting to build shortfin after latest changes:
```text
[1/9] Performing download step (git clone) for 'shortfin_iree-populate'
Cloning into 'shortfin_iree-src'...
fatal: reference is not a tree: 67ba1c45424d5cedc7baf7bfe8a998ee86e510af
CMake Error at shortfin_iree-subbuild/shortfin_iree-populate-prefix/tmp/shortfin_iree-populate-gitclone.cmake:61 (message):
Failed to checkout tag: '67ba1c45424d5cedc7baf7bfe8a998ee86e510af'
```
This [PR](https://github.com/stbaione/SHARK-Platform/commit/e465c8331e78920ceadf9ea700c9487340628771#diff-35cb57ca809622770dcb077453d2d0982ba69588484a1ef6310b7450cc8568f4R186) seemed to introduce the bug by switching from `release candidate` tag to a `commit hash`.
Switched back to using release-candidate tag, which fixed shortfin …

Replace commit hash with latest release candidate

---

shortfin/python/shortfin_apps/llm/components/service.py
shortfin/requirements-tests.txt
shortfin/tests/apps/llm/cpu_llm_server_test.py

- Add test for shortfin llm server
- Add `sentencepiece` to requirements-tests.txt for `shortfin`
- Fix args for Program instantiation and invocation for `shortfin` llm service
Co-Authored by: @renxida

Add Back LLM Server Test

---

shortfin/requirements-tests.txt
shortfin/tests/invocation/simple_kvcache_access_test.py

This test file closely mimics the kvcache indexing, reading, and writing for open-llama-3b-v2-f16.gguf.
It's a simple test to verify that shortfin can:
- Create device arrays
- Map and fill them
- Invoke a VMFB and pass arguments to it
- Properly retain changes made by the VMFB to device arrays provided as arguments

Simple KV Cache Access Tests

---

.github/workflows/ci_linux_x64-libshortfin.yml
shortfin/setup.py

Further replaces `PurePath.relative_to` as the `walk_up` parameter was added with Python 3.12 and the old behavior defaults to `False`.
Progress on https://github.com/nod-ai/SHARK-Platform/issues/357

Expand testing to cover Python 3.11

---

shortfin/python/shortfin_apps/llm/components/service.py

Small patch reflecting some recent changes in `sf.Program` and `sf.ProgramFunction`.
Was originally included as part of this PR, which adds an integration test to shortfin llm serving: https://github.com/nod-ai/SHARK-Platform/pull/373
But, parsing it out, since that may take a little more time to make adjustments/add workflow file.
Without it, you get the following error when trying to launch the server:
```text
[2024-10-30 11:59:09.939] [info] [manager.py:40] System manager command processor stopped
[2024-10-30 11:59:09.991] [error] [on.py:121] Traceback (most recent call last):
File "/home/amd/stephen/repos/forks/SHARK-Platform/.venv/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
async with self.lifespan_context(app) as maybe_state:
File …
```

Add Patch for LLM Server

---

.github/workflows/ci-llama.yaml
sharktank/conftest.py
sharktank/requirements-tests.txt
sharktank/sharktank/utils/export_artifacts.py
sharktank/tests/models/llama/benchmark_amdgpu_test.py

This commit generates reports for the llama testing. Every time it runs it in CI, it will deploy to github pages (https://nod-ai.github.io/SHARK-Platform). @aviator19941 is working on getting the rest of the tests properly implemented. Only the llama8b fp16 tests are working as intended at the moment.

Add reporting for llama testing and improve error handling

---

sharktank/sharktank/examples/export_paged_llm_v1.py

Symbolic dynamic shapes are required for some of the linalg_ext tiling behavior. Added them within the symbolic shape support.

Add symbolic dynamic shapes to export

---

sharktank/pyproject.toml
sharktank/setup.py

Progress on https://github.com/nod-ai/SHARK-Platform/issues/294
Moves over the project metadata and most parts of the build configuration to the `pyproject.toml`, see [1, 2]. The `setup.py` is kept to allow handling `version_info.json` files in a similar manner across all our project.
[1] https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
[2] https://packaging.python.org/en/latest/guides/modernize-setup-py-project/

[sharktank] Modernize `setup.py` based project

---

.github/workflows/ci-llama.yaml

Comments out deploying to GH pages as this breaks the CI for PRs from forks, see #395.

Deactivate deploying to GH pages

---

.github/workflows/ci_eval.yaml

Partly reverts changes pushed with commit b7fa50c. The workflow seems to take hour and is not suitable to run on every PR.

Don't run on workflow on PR

---

sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/tests/ops/sharded_test.py

Existing implementation invokes the `torch` sdpa operator directly. Rewired to invoke via the `ops` system for a sharded sdpa operation. This includes a sharded implementation that compares the two versions.

[ops] Add a sharded attention operation for SDPA

---

.github/workflows/build_packages.yml
sharktank/README.md
sharktank/build_tools/build_linux_package.sh
shortfin/build_tools/build_linux_package.sh

Progress on https://github.com/nod-ai/SHARK-Platform/issues/294. Once this is merged the nightly package builds will start pushing `sharktank-{VERSION}-py3-none-any.whl` to https://github.com/nod-ai/SHARK-Platform/releases/tag/dev-wheels alongside the existing shortfin wheels.
Tested at https://github.com/ScottTodd/SHARK-Platform/actions/runs/11621153296/job/32364368882 (ignore the push failure at the end, missing a token).
---
Note that the 250KB Python wheel can be _installed_ standalone, but actually _using_ it will need version bumps across projects and more work. In particular, I hit
1. Using iree-turbine from pypi:
```
from sharktank import ops
...
ImportError: cannot import name 'dynamic_dim' from 'torch.export' (/home/nod/dev/scratch/shark-platform/3.11.venv/lib/python3.11/site-pac …
```

Build sharktank packages nightly.

---

sharktank/sharktank/examples/export_paged_llm_v1.py

Some tests for toy-sized sharded Llama that I want to adapt to use this script have non-default values. The export chokes on them.

In LLM export make dynamic dims compatible with non-defaults

---

shortfin/README.md
shortfin/python/array_binding.cc
shortfin/python/lib_ext.cc
shortfin/tests/api/array_ops_test.py
shortfin/tests/api/array_storage_test.py
shortfin/tests/api/array_test.py
shortfin/tests/api/nputils_test.py
shortfin/tests/conftest.py
shortfin/tests/invocation/conftest.py
shortfin/tests/invocation/mobilenet_program_test.py
shortfin/tests/invocation/vmfb_buffer_access_test.py

* Now `shortfin.SystemBuilder` (which was an abstract class) has a constructor. When used (vs one of the concrete subclasses), the `system_type=` keyword (or SHORTFIN_SYSTEM_TYPE env var, or `SystemBuilder.default_system_type` property) is used to drive subclass selection.
* This feature was already in the C++ API: this patch merely exposes it to Python in an ergonomic way.
* Pytest configuration and fixtures were updated to support configurable system independence where possible/straightforward. The result is that some tests now run for `--system amdgpu`.
* Pytest `--compile-flags=` is now available to also provide explicit compilation flags for tests that need to compile a binary.
* Both such tests are currently non functional on amdgpu, which needs further triage. This is ok to land …

[shortfin] Make SystemBuilder fully configuration/environment driven.

---

sharktank/sharktank/serving_poc/framework/session.py
sharktank/sharktank/serving_poc/llm/impl/service_v1.py

The sharktank CI has been failing since the latest IREE nightly was automatically picked up: https://github.com/nod-ai/SHARK-Platform/actions/workflows/ci-sharktank.yml. We have version pins in many parts of this repository but apparently not here.
This fixes the failing test by adapting to the changes in https://github.com/iree-org/iree/pull/19000 that switched the low level `queue_execute` API from taking a list of command buffers to taking a single command buffer.

Adapt sharktank/serving_poc to latest IREE runtime changes.

---

sharktank/conftest.py

Running
pytest sharktank/tests
would result in error
INTERNALERROR> pluggy._manager.PluginValidationError: unknown hook 'pytest_html_results_table_header' in plugin <module 'conftest' from ...
This makes the hooks optional.

Make some pytest hooks optional to avoid unknown hook errors

---

shortfin/python/lib_ext.cc
shortfin/src/shortfin/local/systems/amdgpu.cc
shortfin/src/shortfin/local/systems/amdgpu.h
shortfin/src/shortfin/support/config.cc
shortfin/tests/amdgpu_system_test.py
shortfin/tests/conftest.py

* Corresponds to IREE runtime `--hip_tracing` flag.
* Adds `amdgpu_tracing_level=<int>` with a default of 2 to match IREE.
* Verified that the default produces traces with GPU zones and that both the Python level setting and the env var (`SHORTFIN_AMDGPU_TRACING_LEVEL`) works.
* Not a good way to automate this kind of test, so I just did manual verification.

[shortfin] Plumb through `amdgpu_tracing_level` config option.

---

sharktank/sharktank/types/tensors.py

The __repr__ for large tensors is way too slow and the debugger takes forever to access them stalling for minutes at a time. This gives the option to replace it.

Add env var option to override torch.Tensor.__repr__

---

sharktank/sharktank/layers/configs/llm_configs.py
sharktank/tests/layers/configs_test.py

Some upcoming tests use this to construct a dataset file with a config.

Add method to_gguf_props in LlamaHParams

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
.github/workflows/ci-sdxl.yaml
.github/workflows/ci_linux_x64-libshortfin.yml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
.github/workflows/ci_linux_x64_nogil-libshortfin.yml
.github/workflows/ci_windows_x64-libshortfin.yml
shortfin/CMakeLists.txt
shortfin/requirements-iree-compiler.txt
shortfin/src/shortfin/array/storage.cc
shortfin/src/shortfin/local/scheduler.cc

Updates IREE usage in shortfin to match iree-org/iree@44adc3a and candidate-20241106.1070, respectively. Further bumps to the new version in the workflows that are pinned to a specific version.

Integrate IREE at iree-org/iree@44adc3a

---

shortfin/examples/python/mobilenet_server/build_model.sh
shortfin/examples/python/mobilenet_server/inference_system.py
shortfin/python/lib_ext.cc
shortfin/src/shortfin/local/CMakeLists.txt
shortfin/src/shortfin/local/system.cc
shortfin/src/shortfin/local/system.h
shortfin/src/shortfin/local/systems/amdgpu.cc
shortfin/src/shortfin/local/systems/amdgpu.h
shortfin/src/shortfin/local/systems/host.cc
shortfin/src/shortfin/local/systems/host.h
shortfin/tests/amdgpu_system_test.py
shortfin/tests/conftest.py
shortfin/tests/host_cpu_system_test.py

* `allocators=`, `amdgpu_allocators=` and `hostcpu_allocators=` keywords control application of allocator decorators. Adding specifically to enable `caching`.
* `amdgpu_logical_devices_per_physical_device=n` will create `n` logical HAL devices per physical/visible AMDGPU device. This is used for some forms of multi-device distribution.
Filed #443 with a disabled test which seems to tickle an IREE memory leak in `iree_hal_configure_allocator_from_specs`.

[shortfin] Add options to set allocators and logical devices per physical.

---

sharktank/version_info.json
shortfin/version_info.json

Progress on https://github.com/nod-ai/SHARK-Platform/issues/400.
Switching the versions to be earlier than the planned 3.0.0 will let us publish a 2.9.0 test release to PyPI and then increment the major version once we are comfortable with the new release process. I plan on deleting the existing 3.0.0 binaries that have been pushed to the "dev-wheels" release.
(Yes, pre-releases are a thing: https://packaging.python.org/en/latest/specifications/version-specifiers/#pre-releases, but we want to trial the full release process)

Decrement sharktank and shortfin versions to 2.9.0.

---

shortfin/CMakeLists.txt
shortfin/build_tools/cmake/shortfin_library.cmake
shortfin/setup.py
shortfin/src/CMakeLists.txt
shortfin/src/shortfin.ld
shortfin/src/shortfin/support/logging.h

* When bundling deps, sets visibility and export control options.
* Re-export versioned spdlog symbols so that clients share registry, etc.
* Forces inline hidden visibility.
* Enables IREE default visibility so that the API is re-exported.
* Applies a version script on Linux so that all symbols get versioned.
* Makes it possible to use IREE tracing macros in binaries that depend on the dylib.
* Enables (thin) LTO by default.
* Removes the obsolete find_package() method of depending on IREE. It is incompatible with how we have been doing runtime source builds for a long time.
Requires an IREE version bump to pick up https://github.com/iree-org/iree/pull/19068

[shortfin] A number of tweaks for dylib builds.

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/layers/kv_cache.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/types/tensors.py
sharktank/tests/layers/kv_cache_test.py
sharktank/tests/layers/sharded_paged_kv_cache_test.py

We should avoid reshaping the kv cache as much as possible. This change reduces the shape manipulations on the cache. KV cache test changes are only to update for arg rename, all observable behaviour should be the same.

Rework kv cache to avoid needless reshaping

---

shortfin/src/shortfin/local/systems/amdgpu.cc
shortfin/src/shortfin/local/systems/host.cc
shortfin/src/shortfin/support/CMakeLists.txt
shortfin/src/shortfin/support/sysconfig.cc
shortfin/src/shortfin/support/sysconfig.h

Without this, on very large systems (i.e. 64 GPU / 192 Core), it was not possible to open all devices without manual tweaks to file handle descriptor limits. The result were various forms of RESOURCE_EXHAUSTED errors. This may require more tweaking in the future, and for fully robust setups, production installations should explicitly configure high limits. However, these heuristics remove a significant barrier to entry and provide some feedback in terms of logs.
Progress on #463

[shortfin] Add heuristics for adjusting file descriptor limits on Linux.

---

shortfin/pyproject.toml

Adds `typing-extensions` as a build time dependency as it required by nanobind, see https://github.com/nod-ai/SHARK-Platform/actions/runs/11777270868/job/32801349583#step:5:744

[shortfin] Add missing build time dependency

---

build_tools/promote_whl_from_rc_to_final.py
build_tools/requirements-pypi-deploy.txt

Progress on https://github.com/nod-ai/SHARK-Platform/issues/400
This lets us take a release from https://github.com/nod-ai/SHARK-Platform/releases/tag/dev-wheels and "promote it" for publishing to https://pypi.org/ by turning the version from `X.Y.ZrcYYYYMMDD` to simply `X.Y.Z`. The script is forked from the one in IREE I added last week: https://github.com/iree-org/iree/pull/19067.
More steps like https://iree.dev/developers/general/release-management/#promoting-a-candidate-to-stable and scripting like https://github.com/iree-org/iree/blob/main/build_tools/python_deploy/pypi_deploy.sh will follow.

Add script to drop `rcYYYYMMDD` suffix from packages for PyPI deploy.

---

sharktank/version_info.json
shortfin/version_info.json

To match with X.Y of `iree-{base-compiler,base-runtime,turbine}`, the patch level is increased instead of the minor version.

Increment package version to 2.9.1

---

shortfin/python/array_binding.cc
shortfin/python/array_host_ops.cc
shortfin/python/lib_ext.cc
shortfin/src/shortfin/array/array.cc
shortfin/src/shortfin/array/storage.cc
shortfin/src/shortfin/array/xtensor_bridge.cc
shortfin/src/shortfin/local/program.cc
shortfin/src/shortfin/local/scheduler.cc
shortfin/src/shortfin/local/system.cc
shortfin/src/shortfin/local/systems/amdgpu.cc
shortfin/src/shortfin/local/systems/host.cc
shortfin/src/shortfin/local/worker.cc
shortfin/src/shortfin/support/logging.h

* Manually chose a number of things that would be interesting to see in a trace and added annotations.
* QC'd with some unit test traces.

[shortfin] Adds C++ tracing scopes.

---

shortfin/python/array_host_ops.cc
shortfin/python/shortfin/array/__init__.py
shortfin/tests/api/array_ops_test.py

Ops added: `convert`, `round`, `ceil`, `floor`, `trunc`
All ops were implemented to the same pattern, supporting fused conversion and output array.
Fixes #315

[shortfin] Add conversion host ops.

---

.github/workflows/ci-sharktank.yml

The packages were recently renamed from `iree-compiler` and `iree-runtime` to `iree-base-compiler` and `iree-base-compiler`, respectively.

Adapt to package rename

---

shortfin/README.md
shortfin/pyproject.toml
shortfin/setup.py

Similar to #489, this adds mertadata to the shortfin Python package but does so by extending the `pyproject.toml` file instead of adding metadata to the `setup.py` file.

Add metadata to shortfin Python package

---

.github/workflows/ci-shark-platform.yml
.github/workflows/ci-sharktank.yml
.github/workflows/ci-tuner.yml
.github/workflows/ci_eval.yaml
docs/nightly_releases.md

Pip will only install "pre-release" versions if `--pre` is set or the version is set explicitly: https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions. The `rc` part of our `rcYYYYMMDD` suffix used in the nightly IREE packages is considered a "Pre-release segment" in the version string: https://packaging.python.org/en/latest/specifications/version-specifiers/#public-version-identifiers.
This should change workflow jobs like https://github.com/nod-ai/SHARK-Platform/actions/runs/11827078971/job/32954462017#step:5:163 that have been downloading `iree-base-compiler-2.9.0 iree-base-runtime-2.9.0` to downloading the latest nightly versions instead, as they intend: https://github.com/nod-ai/SHARK-Platform/blob/51cf2f45139f67e15434990173b49375998db9f3/.github/workflows/ci-sharktank.y …

Fix workflows installing nightly IREE packages to use `--pre`.

---

build_tools/python_deploy/write_requirements.py

This drops the strict dependency to sharktank which otherwise always gets pulled in when installing the shark-ai package.

[shark-ai] Temporarily drop sharktank dependency

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/layers/kv_cache.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/types/tensors.py
sharktank/tests/layers/kv_cache_test.py
sharktank/tests/layers/sharded_paged_kv_cache_test.py

This reverts commit b36ddf7842e7124926b5f99d89e504bcbef93753.
The beginning of the fix to the brand new November KV cache issue

Revert "Rework kv cache to avoid needless reshaping (#450)"

---

sharktank/sharktank/examples/paged_llm_v1.py
sharktank/sharktank/kernels/__init__.py
sharktank/sharktank/kernels/bitcast.py
sharktank/sharktank/layers/rotary_embedding.py
sharktank/sharktank/models/llama/llama.py
sharktank/sharktank/ops/custom_impls.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py

It appears the change away from complex numbers triggered a downstream iree failure. An inflight work to use `flow.tensor.bitcast` and restore to complex numbers appears to fix the issue. Fixing forward as we wanted to revert part of this change anyway.

Restore RotaryEmbedding use complex numbers

---

build_tools/integration_tests/llm/cpu_llm_server_test.py

Remove `xfail` from CPU LLM Server Integration test. Shortfin server is back in a good spot, and this should be left on anyways

Restore CPU LLM Server integration test

---

sharktank/version.json
shortfin/version.json
tuner/version.json

We just published version 2.9.1 to PyPI, so update the version to 3.0.0 ahead of the next nightly build.
Note: updating the version and rebuilding a release is relatively cheap in this project, since the release build action only takes 5 minutes. We can reduce the version if we want, or update it after a nightly build. That is _not_ the case in https://github.com/iree-org/iree, where the release build takes over 4 hours.

Update package versions to 3.0.0.

---

shortfin/pyproject.toml

Update pyproject to include missing SDXL app deps. These were discovered while testing shortfin apps flow by only pre-installing the shark meta pkg

Update pyproject to include missing SDXL app deps

---

shark-ai/README.md

`sharktank` is currently not pulled in via the meta package.

[shark-ai] Update README

---

tuner/tuner/candidate_gen.py
tuner/tuner/candidate_gen_test.py
tuner/tuner/common.py
tuner/tuner/common_test.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_constraints_test.py
tuner/tuner/dispatch_parser.py
tuner/tuner/dispatch_parser_test.py

This follows the general goal of using the IREE/MLIR bindings instead of working with textual IR.

[tuner] Use `ir.(Integer|Float)Type` for element types

---

docs/user_guide.md

Remove 3.13t from "python supported versions" in user guide, as some release deps have critical issues on python3.13 free-threaded.

Update supported python versions in user guide.

---

docs/user_guide.md

The default `torch` install pulls in multiple gigabytes of packages (mostly CUDA), which are not needed.
We'll eventually
* Remove the implicit dep on default-torch in https://github.com/iree-org/iree-turbine
* Rework shortfin_apps to not depend on torch
For now, suggest that users install the torch package of their choosing before installing any of our packages.

Recommend installing torch cpu ahead of shark-ai.

---

shortfin/python/shortfin_apps/sd/components/builders.py

This commit introduces simple filesize/content-length comparison for a simple validation of downloaded artifacts. 
While I'm not sold on this as a long-term validation solution, it is certainly better than nothing.

(shortfin-sd) Validate size of downloaded artifacts.

---

shortfin/src/shortfin/local/worker.cc

This is a relatively arbitrary limit that we increase to allow more traffic on server at a given time.

(shortfin) Increase loop queue/wait limit for workers.

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
.github/workflows/ci-sdxl.yaml
.github/workflows/ci-sglang-benchmark.yml
.github/workflows/ci_linux_x64-libshortfin.yml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
.github/workflows/ci_linux_x64_nogil-libshortfin.yml
.github/workflows/ci_windows_x64-libshortfin.yml
shortfin/CMakeLists.txt
shortfin/requirements-iree-compiler.txt

Bumps the IREE version (which is among other things used to build shortfin) to the latest release candidate / nightly version.

Bump IREE version to 3.0.0rc20241118

---

sharktank/version.json
shortfin/version.json
tuner/version.json

Reverts nod-ai/shark-ai#547
We'll want to merge this prior to kicking off a stable release build. We can use either a regularly scheduled nightly release or `workflow_dispatch` of https://github.com/nod-ai/shark-ai/actions/workflows/build_packages.yml.

Update version back to 3.0.0 for stable release.

---

.github/workflows/ci-shark-ai.yml
app_tests/integration_tests/llm/conftest.py
app_tests/integration_tests/llm/cpu_llm_server_test.py
app_tests/integration_tests/llm/utils.py

Use the ::group:: [GitHub Workflow Command](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions) to make it easier to navigate integration logs.
Also adds a summary to easily look at what the generation results are.

Group llm integration test output using github ::group::

---

sharktank/sharktank/kernels/templates/flash_attention.mlir

Flash Attention transpose_V variant is significantly faster than the non transpose_V variant. This is due to many MM intrinsics being mmtb by default. Hence, doing FA transpose_V will allow for better/more contiguous reads from shared memory to register, improving the attention performance vastly. This also makes FP8 faster than FP16. I have tested that it indeed improves SDXL performance on FP8, making FP8 faster than our FP16 model.
I have also tested/confirmed that, if we do not find any producers that we can fuse with, it seem to re-fuse back into the attention. Hence, the worst performance it will get is same as before we un-split the transpose.
For some data on a microbenchmark with real size from SDXL:
```
(B0, B1, M, K1, K2, N): (2, 10, 4096, 64, 4096, 64)
Over 100 runs:
FP16 non …
```

[kernel] Refactor FA kernel to be FA_transV when possible.

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
sharktank/conftest.py
sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/utils/cli.py
sharktank/sharktank/utils/export_artifacts.py
sharktank/tests/models/llama/README.md
sharktank/tests/models/llama/benchmark_amdgpu_test.py

1. Update tests with compile flags and tp flags, with nightly iree.
2. Only use 8b f16 decomposed test to decrease the CI wait time.

Add prefill 8B f16 torch sdpa test, update tests with compile flags and tp flags, with nightly iree

---

sharktank/sharktank/examples/export_paged_llm_v1.py

It is illegal to have ops with some arguments having affinties and some not. Operands will be considered on different devices and this is not allowed right now.
With recent enough version of IREE during compilation this will result in
```
failure.mlir:1:1: error: affinity analysis failed to converge (input program may have invalid affinities assigned); use`--iree-stream-annotate-input-affinities` to help identify the invalid affinities
```
This change makes it so that we do not add any affinities when not sharding.

In paged LLM exporting do not add any argument affinities when not sharding

---

tuner/tuner/candidate_gen.py

Module does not support context management

[tuner] Fix module management

---

tuner/tuner/candidate_gen.py

`ir.*` types don't support pickling. Disabling this for now until we get a proper fix.

[tuner] Temporarily disable candidate pickling

---

docs/developer_guide.md

[skip ci]
There are some apt packages needed before it would work.

Add Linux prep instructions to developer guide

---

shortfin/python/array_binding.cc
shortfin/python/array_host_ops.cc
shortfin/python/shortfin/array/__init__.py
shortfin/src/shortfin/array/dtype.h
shortfin/tests/api/array_ops_test.py
shortfin/tests/api/array_use_case_test.py
shortfin/tests/apps/sd/e2e_test.py

* Adds `sfnp.transpose`, `sfnp.add`, `sfnp.divide`, `sfnp.multiply`, `sfnp.subtract`
* Adds a use case test showing how to convert planar fp images to interleaved RGB pixel values
Fixes #314

[shortfin] Implement transpose and elementwise host ops.

---

.github/workflows/ci-llama-large-tests.yaml

Accidentally added as part of https://github.com/nod-ai/shark-ai/pull/580

remove presubmit for large llama tests

---

tuner/tuner/candidate_gen.py
tuner/tuner/common.py
tuner/tuner/common_test.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_constraints_test.py

This PR is relevant to the task in https://github.com/nod-ai/shark-ai/issues/453: " Use IREE attributes for MFMA intrinsics in the tuner".

[tuner]: use python binding to select mma intrinsics

---

shortfin/requirements-tests-nogil.txt

This removes fastapi as a requirements as it pulls in pydantic which depends on pydantic-core. The latter cannot be build for a free-threaded Python and as part of the 0.27.1 release bumped PyO3 to 0.22.6 to prevent accidental installs on free-threaded Python.
Supersedes and closes #595.

[shortfin] Remove fastapi from 3.13t requirements

---

sharktank/conftest.py
sharktank/requirements.txt
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/layers/token_embedding.py
sharktank/sharktank/models/t5/export.py
sharktank/sharktank/models/t5/t5.py
sharktank/sharktank/transforms/dataset/__init__.py
sharktank/sharktank/transforms/dataset/dataset.py
sharktank/sharktank/types/gguf_interop/base.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/utils/iree.py
sharktank/sharktank/utils/testing.py
sharktank/tests/models/t5/t5_test.py

Adds various tests for verifying bfloat16 execution.
The bfloat16 eager execution matches Flux's output. One test verifies this against golden values from the Flux pipeline.
I would say that the eager numerical error is still quite high. My initial idea was to compare the numerical error in IREE bfloat16 vs eager float32. It should match the error profile as the one we get between eager bfloat16 compared against eager float32. The problem is that the bfloat16 eager has a high error that needs further investigation.
Due to this some tests are marked as xfail as we don't have a good metric to evaluate the IREE results.

Add T5 encoder bfloat16 support

---

shortfin/CMakeLists.txt
shortfin/build_tools/cmake/shortfin_library.cmake
shortfin/build_tools/cmake/shortfin_testing.cmake
shortfin/setup.py
shortfin/src/shortfin/CMakeLists.txt
shortfin/src/shortfin/components/tokenizers/CMakeLists.txt
shortfin/src/shortfin/components/tokenizers/tokenizers.cc
shortfin/src/shortfin/components/tokenizers/tokenizers.h
shortfin/src/shortfin/components/tokenizers/tokenizers_test.cc

* This is gated by SHORTFIN_ENABLE_TOKENIZERS (presently off).
* I'd like to either take over the wrapper or get https://github.com/mlc-ai/tokenizers-cpp/issues/50 before putting much weight on this.
* There is no great C++ option for this component, so we go to the trouble of integrating a Rust component. We will need to do a bit of prep on our CI systems to enable this by default.
* Python API will be added in a subsequent commit. This should be more efficient than the tokenizers Python API since we will allow direct access to the tokens vs doing a lot of conversions.
* Size analysis: Prior to this patch, libshortfin was 1.8MB, which gave us an entire GPU and CPU runtime stack. After this patch (stripped) it is 8.4MB. Given how important the use case is, I'm willing to tolerate this for …

[shortfin] Add C++ tokenizer wrapper library.

---

sharktank/sharktank/ops/attention_impls.py

This commit updates the flash attention op to adhere to the addition of is_causal and scale args added by this commit: https://github.com/nod-ai/SHARK-Platform/commit/2d46caaa932fe41f765315752665e87718aef5b3. Without this, we are seeing a fp8 attention export failure

Update flash attention op

---

sharktank/sharktank/kernels/templates/flash_attention.mlir

Now that we have landed
https://github.com/iree-org/iree/commit/41115bba05960e563791ce6ed1af26093f4fab1e on top of main, we should not need explicit transpose as part of kernel anymore. Although this PR still maintains the order that reduction dim is the fastest dim per which is done in https://github.com/nod-ai/shark-ai/commit/a7feae8bce788f865548f7f5fda547050f3097a1

[kernel] remove transposeV in favor of generic method in iree compile

---

.github/workflows/ci-sharktank.yml

Partial revert of https://github.com/nod-ai/shark-ai/pull/613.
This job takes over an hour to run (specifically `test_punet_eager_fp16_validation `) and is not suitable for presubmit.
This is likely also not the right file for such tests, and if it was then the specialized tests should go under the generic `test` job, not at the top of the file.

Remove test_punet job from ci-sharktank.yml.

---

tuner/tuner/candidate_gen_test.py
tuner/tuner/common.py
tuner/tuner/common_test.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_parser_test.py

This PR is relevant to task:  Use IREE bindings for compilation info (incl., lowering_config and translation_info) in https://github.com/nod-ai/shark-ai/issues/453. 
Retire data class GPUPipelineOptions, use python binding iree_gpu.PipelineOptionsAttr instead.

[tuner]: retire data class GPUPipelineOptions, use iree_gpu.PipelineOptionsAttr. 

---

shortfin/build_tools/build_linux_package.sh

Progress on https://github.com/nod-ai/shark-ai/issues/130.
The manylinux2014 image includes gcc 10.2.1 by default while manylinux_2_28 includes gcc 12.2.1. At one point we had warnings/errors building on the newer gcc version, but that is no longer the case.
With the new Rust dependency coming from https://github.com/nod-ai/shark-ai/pull/610, we will likely want to revive https://github.com/nod-ai/base-docker-images/blob/main/dockerfiles/manylinux_x86_64.Dockerfile, add more dependencies there, then switch from the upstream `quay.io/...` image to that `ghcr.io/nod-ai/...` image.
Tested locally with `OUTPUT_DIR="/tmp/wheelhouse" sudo -E ./build_tools/build_linux_package.sh`. If the nightly package build fails for some reason we can easily revert this.

[shortfin] Upgrade package build dockerfile to manylinux_2_28.

---

sharktank/tests/types/quantizers_test.py

Forcibly assigns type to avoid test flake when it selects bfloat16 for unknown reasons.

[sharktank] Fix flaxy quantizer test 

---

shortfin/python/shortfin_apps/llm/components/kvcache/base_attention_cache.py
shortfin/python/shortfin_apps/llm/components/messages.py
shortfin/python/shortfin_apps/llm/components/service.py
shortfin/tests/apps/llm/components/kvcache/base_attention_cache_test.py

Deinitialization looks wonky for now. Will test extensively to get deinit right once I merge #600
Closes #607

Implement PageAllocation as a handle into a PagedAttentionCache, allowing publishing and releasing an allocation via handle rather than cache

---

.github/workflows/ci-sharktank.yml
sharktank/integration/models/punet/integration_test.py

Adds back punet export test to the CI to run on pre-commit. Takes about ~15 minutes for the tests to run

[CI] Add punet export test

---

tuner/tuner/candidate_gen.py
tuner/tuner/candidate_gen_test.py
tuner/tuner/common.py
tuner/tuner/common_test.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_constraints_test.py
tuner/tuner/dispatch_parser.py
tuner/tuner/dispatch_parser_test.py

This PR is relevant to the task in https://github.com/nod-ai/shark-ai/issues/453 : use IREE bindings for compilation info (incl., lowering_config and translation_info).  
Remove data class `ReorderWorkgroupsStrategy`, and use lowering_config binding.

[tuner]: use lowering config binding

---

sharktank/tests/types/quantizers_test.py

Follow-up to https://github.com/nod-ai/shark-ai/pull/631.
The test is flaking at this line too: https://github.com/nod-ai/shark-ai/actions/runs/12148591430/job/33877368151?pr=639#step:6:25
```
=================================== FAILURES ===================================
________________ StaticScaledQuantizerTest.testPerAxisRoundtrip ________________
[gw0] linux -- Python 3.11.10 /opt/hostedtoolcache/Python/3.11.10/x64/bin/python
self = <tests.types.quantizers_test.StaticScaledQuantizerTest testMethod=testPerAxisRoundtrip>
def testPerAxisRoundtrip(self):
ssq = StaticScaledQuantizer(
name="poodoo",
axis=1,
scale=torch.tensor([0.2, 0.4, 0.8], dtype=torch.float32),
dtype=torch.float16,
)
ssq = self._roundtrip(ssq, "_ssq")
self.assertEqual(ssq.axis, 1)
torch.testing.assert_close(
ssq.scale, …
```

[sharktank] Fix flaxy quantizer test (attempt 2).

---

.github/workflows/build_packages.yml
.github/workflows/ci-libshortfin.yml
.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
.github/workflows/ci-sdxl.yaml
.github/workflows/ci-sglang-benchmark.yml
.github/workflows/ci-sglang-integration-tests.yml
.github/workflows/ci-shark-ai.yml
.github/workflows/ci-sharktank.yml
.github/workflows/ci-tuner.yml
.github/workflows/ci_eval.yaml
.github/workflows/ci_eval_short.yaml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
.github/workflows/ci_linux_x64_nogil-libshortfin.yml

Cutting down on boilerplate and standardizing some workflow syntax before deeper refactoring work.
* Move `users: actions/checkout` to the start of each job (for consistency, since all workflows use the source code but not all workflows need dependencies or python setup, etc.)
* Per https://github.com/actions/checkout, `submodules: false` is the default
* Step names can be omitted with `uses` (docs: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iduses) . Our [`pre-commit.yml`](https://github.com/nod-ai/shark-ai/blob/main/.github/workflows/pre-commit.yaml) workflow does this already: https://github.com/nod-ai/shark-ai/blob/c0ca2e2788ea09a890ffe347dfbffe57606670b8/.github/workflows/pre-commit.yaml#L11-L14
* Remove copy/pasted `Get Current …

Workflow cleanup: move checkout to start, prune unused steps+vars.

---

app_tests/integration_tests/llm/shortfin/conftest.py
app_tests/integration_tests/llm/shortfin/cpu_llm_server_test.py
shortfin/python/shortfin_apps/llm/components/config_struct.py
shortfin/python/shortfin_apps/llm/components/kvcache/base_attention_cache.py
shortfin/python/shortfin_apps/llm/components/kvcache/page_pool.py
shortfin/python/shortfin_apps/llm/components/kvcache/trie_attention_cache.py
shortfin/python/shortfin_apps/llm/components/messages.py
shortfin/python/shortfin_apps/llm/components/service.py
shortfin/tests/apps/llm/components/kvcache/base_attention_cache_test.py
shortfin/tests/apps/llm/components/kvcache/trie_attention_cache_test.py

feat: Add TriePagedAttentionCache with initial implementation
Added TriePagedAttentionCache as an optional prefix sharing algorithm, selectable via:
`config["paged_kv_cache"]["prefix_sharing_algorithm"] = "trie"`
Current Status:
- Basic implementation and unit tests complete
- Integration test cases for both Base and Trie implementations, with trie implementation xfailed due to pending cache allocation improvements
- BasePagedAttentionCache remains the default
Next Steps:
To achieve full functionality, we need to support cache re-allocations to extend the associated tokens & pages.

TriePagedAttentionCache

---

shortfin/setup.py

Progress on https://github.com/nod-ai/shark-ai/issues/584.
This is expected to save around 10-20 seconds when building packages on standard GitHub-hosted runners:
```
Tue, 03 Dec 2024 11:07:18 GMT   [372/380] Linking CXX shared library src/libshortfin.so.3.1.0
Tue, 03 Dec 2024 11:07:18 GMT   [373/380] Creating library symlink src/libshortfin.so.1 src/libshortfin.so
Tue, 03 Dec 2024 11:07:23 GMT   [374/380] Linking CXX executable src/shortfin/support/shortfin_support_test
Tue, 03 Dec 2024 11:07:23 GMT   [375/380] Linking CXX executable src/shortfin/array/shortfin_array_test
Tue, 03 Dec 2024 11:07:36 GMT   [376/380] Building CXX object python/CMakeFiles/shortfin_python_extension.dir/array_host_ops.cc.o
Tue, 03 Dec 2024 11:07:45 GMT   [377/380] Linking CXX shared module …
```

[shortfin] Disable C++ tests in package builds.

---

.github/workflows/ci-libshortfin.yml
.github/workflows/ci-sdxl.yaml
.github/workflows/ci-sglang-benchmark.yml
.github/workflows/ci_linux_x64_asan-libshortfin.yml
.github/workflows/ci_linux_x64_nogil-libshortfin.yml
shortfin/CMakeLists.txt
shortfin/requirements-iree-compiler.txt

Diff: https://github.com/iree-org/iree/compare/iree-3.0.0rc20241118...iree-3.1.0rc20241204
Notable changes that could affect shortfin:
* https://github.com/iree-org/iree/commit/cd4aa72a15cf9467a33a36bca87fbd45e29974b1 "[runtime][python] Fix device array deepcopy when not mappable"
* https://github.com/iree-org/iree/commit/ef4ecf3b7111cead7bf29f630965c36395e515e9 "[iree.build] Wire up out of process concurrency."
* https://github.com/iree-org/iree/commit/516ff10aae2abd37529f673b27ce20648ce59fc9 "[python] Overhaul iree.build console output and error handling."
* https://github.com/iree-org/iree/commit/978943859418d160ac3c7b32f6917e13fc240a97 "[iree.build] Make the fetch_http action more robust."
* https://github.com/iree-org/iree/commit/006c5d8dcb638b0abfc704fb8c89cb6dc43377f5 "Avoid …

[shortfin] Bump IREE dep to iree-3.1.0rc20241204.

---

.github/workflows/ci-sdxl.yaml

The `mi300-sdxl-kernel` runner has been offline for a few weeks, so runs of this workflow have been queued: https://github.com/nod-ai/shark-ai/actions/workflows/ci-sdxl.yaml. This `mi300x-4` runner is probably fit to run this workflow.
Also refactored the workflow to not use explicit build steps, which loosens the requirements on installed software and helps make progress on https://github.com/nod-ai/shark-ai/issues/584.

Switch ci-sdxl github runner and refactor workflow.

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
.github/workflows/ci-sglang-benchmark.yml
.github/workflows/ci-sglang-integration-tests.yml
.github/workflows/ci-shark-ai.yml
.github/workflows/ci-sharktank.yml
.github/workflows/ci_eval.yaml
.github/workflows/ci_eval_short.yaml

Many of these workflows are using persistent self-hosted runners, so it looks like they have been reusing the same system-wide Python environment between workflow runs (plus layer of caching on top). This switches to using venvs at `${{ github.workspace }}/.venv` that should be ephemeral, giving us more explicit control over which packages are installed.
More work is planned as part of https://github.com/nod-ai/shark-ai/issues/584 to refactor these workflows further - replacing the package installs code like `pip install --no-compile -r requirements.txt -r sharktank/requirements-tests.txt -e sharktank/` with a `setup_venv.py` script that uses dev/nightly/stable packages (from an appropriate source).
This also disables pip caching, since that is not directly compatible with using venvs. As …

Install python packages into venvs across workflows.

---

shortfin/build_tools/build_linux_package.sh

Splitting this off from https://github.com/nod-ai/shark-ai/pull/589 to make progress on https://github.com/nod-ai/shark-ai/issues/584.
Tested with
```
CACHE_DIR=/tmp/shortfin/ sudo -E ./shortfin/build_tools/build_linux_package.sh
+ ccache --show-stats
Cacheable calls:   626 / 636 (98.43%)
Hits:              2 / 626 ( 0.32%)
Direct:          2 /   2 (100.0%)
Preprocessed:    0 /   2 ( 0.00%)
Misses:          624 / 626 (99.68%)
Uncacheable calls:  10 / 636 ( 1.57%)
Local storage:
Cache size (GB): 0.1 / 2.0 ( 3.10%)
Hits:              2 / 626 ( 0.32%)
Misses:          624 / 626 (99.68%)
+ ccache --show-stats
ccache stats:
Cacheable calls:   1252 / 1272 (98.43%)
Hits:             550 / 1252 (43.93%)
Direct:         550 /  550 (100.0%)
Preprocessed:     0 /  550 ( 0.00%)
Misses:           702 …
```

[shortfin] Support ccache in package builds and make tracing optional.

---

.github/workflows/ci-llama-large-tests.yaml
sharktank/tests/models/llama/benchmark_amdgpu_test.py

Uses args for input len 2048 llama test instead of args for input len 128 llama test.

Use correct args for input len 2048 llama test

---

app_tests/integration_tests/llm/shortfin/conftest.py
app_tests/integration_tests/llm/shortfin/cpu_llm_server_test.py

There are two things that get added in this PR:
1. Reuse model artifacts when multiple tests in the same module request export/compilation of the same artifacts
2. Add concurrency tests for `2, 4, and 8` requests at the same time.
Currently, our `cpu_llm_server_integration_tests` generate new model artifacts for each tests, even when they are requesting the exact same artifacts. This causes the tests to take much longer to run than they should, and makes it harder to add more tests without drastically increasing overall test time.
We add a static `MODEL_DIR_CACHE`, which is just a hashmap that stores `{ request.params_hash: temporary_dir }`. If a test requests the same artifacts as a previous test, we reuse the already existing artifacts, instead of generating new ones.
We recenly found a …

Concurrent CPU Integration Tests + Reuse Model Artifacts

---

sharktank/sharktank/layers/rotary_embedding.py
sharktank/sharktank/models/grok/testing.py
sharktank/sharktank/models/grok/toy_grok.py

The `hf` layout for rotary embedding was broken during a previous refactor. Readding the layout changes fixes this. This also includes a toy grok model for testing. It was validated to produce the same results for prefill and decode.

Fix grok and add ToyGrok model

---

shortfin/python/shortfin_apps/llm/components/kvcache/trie_attention_cache.py
shortfin/tests/apps/llm/components/kvcache/trie_attention_cache_test.py

Context: https://github.com/nod-ai/shark-ai/pull/632#discussion_r1869981637

Fix/skip trie_attention_cache_test on Windows.

---

.github/workflows/ci-sglang-benchmark.yml
app_tests/benchmark_tests/llm/sglang_benchmarks/conftest.py
app_tests/benchmark_tests/llm/sglang_benchmarks/sglang_benchmark_test.py
app_tests/benchmark_tests/llm/sglang_benchmarks/shortfin_benchmark_test.py
app_tests/benchmark_tests/llm/sglang_benchmarks/utils.py

Previously we were only benchmarking against the `base` caching algorithm when we run our SGLang benchmark tests. This PR allows us to benchmark against both the `base` and `trie` caching algorithms.
Along with that, it adds the same trick from #655 to be able to reuse model artifacts instead of generating new ones each time, which drastically decreases the overall time required to run the benchmark test.
It also includes a patch to run the benchmark script after syncing SGLang repo today, and ensures that an error is raised when one occurs

Use Trie and Base Caching in SGL Benchmark

---

.github/workflows/ci-sharktank.yml
sharktank/conftest.py
sharktank/sharktank/layers/__init__.py
sharktank/sharktank/layers/activations.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/layers/norm.py
sharktank/sharktank/models/clip/__init__.py
sharktank/sharktank/models/clip/clip.py
sharktank/sharktank/models/clip/export.py
sharktank/sharktank/models/t5/t5.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/types/theta.py
sharktank/sharktank/utils/hf_datasets.py
sharktank/sharktank/utils/math.py
sharktank/sharktank/utils/testing.py
sharktank/tests/models/clip/clip_test.py
sharktank/tests/models/t5/t5_test.py

Ports the CLIP text model from Hugging Face. This is the first iteration so not much is changed from the original model. Things like dropout and checkpointing are removed.
Add numeric verification tests for the various components of the stack when executing in eager mode. Verifications are made for float32 and bfloat16. There are tests for toy-sized components and the whole model as well as the Large pretrained variant.
These tests does not include testing with IREE.
Functionalities for mask creation are not yet ported.

Add CLIP text model

---

.github/workflows/ci-libshortfin.yml

Sets up Rust to build shortfin with `SHORTFIN_ENABLE_TOKENIZERS` set to
`ON` on Linux. At the moment, building with Rust is limited to Linux as
there are build failures on Windows (see issue #620).

[shortfin] Enable building Rust deps on Linux

---

sharktank/requirements-dev-turbine.txt

This requirements file pointing to iree-turbine is not used in any workflow or referred to in the documentation. If needed, we can re-add one pointing to the new package entry later again.

Delete unused requirements file

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
.github/workflows/ci-sglang-benchmark.yml
.github/workflows/ci-sglang-integration-tests.yml
.github/workflows/ci-shark-ai.yml
.github/workflows/ci-sharktank.yml
.github/workflows/ci_eval.yaml
.github/workflows/ci_eval_short.yaml
docs/nightly_releases.md

This simplification will help with https://github.com/nod-ai/shark-ai/issues/584.
Nightly releases of iree-turbine are now being built thanks to https://github.com/iree-org/iree-turbine/pull/314 and published at the same index as the other IREE packages thanks to https://github.com/iree-org/iree/pull/19391.

Switch workflows to use new nightly iree-turbine packages.

---

sharktank/requirements.txt

Instead of pinning specific versions for `fastapi` and `uvicorn`, only a minimum version is set now instead.

Relax restrictions on explicit versions

---

tuner/tuner/candidate_gen.py
tuner/tuner/candidate_gen_test.py
tuner/tuner/common.py
tuner/tuner/common_test.py
tuner/tuner/dispatch_parser.py
tuner/tuner/dispatch_parser_test.py

After landing https://github.com/iree-org/iree/pull/19376, all helper functions related to lowering configuration can be removed. Instead, we can directly utilize property functions from the LoweringConfig Python bindings.
This PR is still relevant to the task in https://github.com/nod-ai/shark-ai/issues/453: use IREE bindings for compilation info (incl., lowering_config and translation_info).

[tuner]: use property function from iree lowering config python binding

---

.github/workflows/build_packages.yml

Tested here: https://github.com/ScottTodd/shark-ai/actions/runs/12244417956 and confirmed that the `METADATA` embedded within `shark_ai.*.whl` has `Requires-Dist: shortfin==3.1.0rc20241209` as expected, compared to the baseline of `Requires-Dist: shortfin==3.1.0`.
I then also ran
```bash
pip install --pre --find-links https://github.com/ScottTodd/shark-ai/releases/expanded_assets/dev-wheels shark-ai
pip freeze | grep sh
```
Compared to the baseline of
```bash
pip install --pre --find-links https://github.com/nod-ai/shark-ai/releases/expanded_assets/dev-wheels shark-ai
pip freeze | grep sh
```

Fix version_suffix for nighly shark-ai packages in build_packages.yml.

---

.github/workflows/build_packages.yml

Progress on https://github.com/nod-ai/shark-ai/issues/584. ~~Depends on https://github.com/nod-ai/shark-ai/pull/666 (the first commit).~~
This is refactors the `build_packages.yml` workflow so it can be used via `workflow_call` as part of a "pkgci" setup, as an alternative to creating a new `pkgci_build_packages.yml` workflow as originally proposed in https://github.com/nod-ai/shark-ai/pull/589. This lets us reuse the same workflow for building stable, nightly, and dev packages, all across the same matrix of Python versions and operating systems. Package builds take about 2 minutes (wall time) across the full matrix, so we might as well build them all, instead of artificially constraining ourselves to a subset like only Linux on Python 3.11.
Triggers for the workflow are now this:
Trigger …

Add dev package support to build_packages.yml.

---

tuner/tuner/__init__.py
tuner/tuner/common_test.py
tuner/tuner/libtuner_test.py

Hack/patch to workaround overlapping `AttrBuilder` registrations. Needed until https://github.com/iree-org/iree/pull/19324 and https://github.com/llvm/llvm-project/pull/117918 get resolved.

[enums] monkey patch `register_attribute_builder`

---

shortfin/python/shortfin_apps/llm/components/service.py

There are 2 problems fixed by 2 code changes in this PR.
This is a small problem that causes us to over-allocate cache pages in the KV cache. This will require further work to get service.py and {Base,Trie}PagedAttentionCache to allocate a precise & consistent amout of cache, but is sufficient to solve the problem at hand.
For unused requests in a batch, seq_len and start_position are usually filled with 0. This injects NaNs that are written to page 0.
Page index 0 serves a special padding role in our batching system. It's used to fill unused pages for shorter requests and to pad unused requests within a batch.
Under normal circumstances, NaNs in page 0 wouldn't be problematic since our masking system is designed to ignore values beyond the current token. For example, when generating …

Initial fix for token corruption when batching

---

app_tests/benchmark_tests/llm/sglang_benchmarks/conftest.py
app_tests/integration_tests/llm/sglang/conftest.py
app_tests/integration_tests/llm/shortfin/conftest.py
sharktank/sharktank/examples/export_paged_llm_v1.py
shortfin/python/shortfin_apps/llm/components/config_struct.py

And remove the adaption layer in buidl_tools/integration_tests/llm/conftest.py

Make config.json consistent between shortfin and sharktank

---

docs/nightly_releases.md

Without `--pre`, stable releases get pulled.

Fix install instructions for nightly releases

---

.github/workflows/ci-sharktank.yml
.github/workflows/ci-tuner.yml
.github/workflows/pre-commit.yaml

With this, runner images are pinned to specific versions instead of referring to `latest`. This allows to have a controlled upgrade path instead instead of just waiting for when a change in the reference affects the workflows.

Pin OS to specific versions

---

.github/workflows/build_packages.yml
build_tools/python_deploy/compute_common_version.py
build_tools/python_deploy/compute_local_version.py

Harmonizes the scripts to compute the versions. JSON files are only written if `--write-json` is passed. Furthermore, `--version-suffix` can no longer be combined with other release types and gives full control over defining a suffix to the user. Similar changes are applied to the scripts used in IREE.

Harmonize scripts to compute versions

---

tuner/tuner/candidate_gen.py
tuner/tuner/candidate_gen_test.py
tuner/tuner/common.py
tuner/tuner/common_test.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_parser_test.py

This PR is relevant to the task in https://github.com/nod-ai/shark-ai/issues/453 : use IREE bindings for compilation info (incl., lowering_config and translation_info).
Use translation_info from IREE  python binding.

[tuner]: use translation_info binding

---

tuner/tuner/candidate_gen.py
tuner/tuner/candidate_gen_test.py
tuner/tuner/common.py
tuner/tuner/common_test.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_parser.py
tuner/tuner/dispatch_parser_test.py
tuner/tuner/libtuner.py

This PR is relevant to the task in https://github.com/nod-ai/shark-ai/issues/453 : use IREE bindings for compilation info (incl., lowering_config and translation_info).
Retire data class `configuration` and use the `compilation_info` from IREE python binding.

[tuner]: use compilation_info binding

---

docs/shortfin/llm/user/e2e_llama8b_mi300x.md
sharktank/requirements.txt

Did a pass through and made updates + fixes to the user docs for `e2e_llama8b_mi300x.md`.
1. Update install instructions for `shark-ai`
2. Update nightly install instructions for `shortfin` and `sharktank`
3. Update paths for model artifacts to ensure they work with `llama3.1-8b-fp16-instruct`
4. Remove steps to `write edited config`. No longer needed after #487 
Added back `sentencepiece` as a requirement for `sharktank`. Not having it caused `export_paged_llm_v1` to break when installing nightly:
```text
ModuleNotFoundError: No module named 'sentencepiece'
```
This was obfuscated when building from source, because `shortfin` includes `sentencepiece` in `requirements-tests.txt`.

Update user docs for running `llm server` + upgrade `gguf` to `0.11.0`

---

sharktank/tests/export_test.py
sharktank/tests/layers/paged_llama_attention_block_test.py
sharktank/tests/layers/sharded_conv2d_with_iree_test.py
sharktank/tests/models/punet/sharded_resnet_block_with_iree_test.py

Marks tests that fail with `torch==2.{4.0,4.1,5.0,5.1}+cpu` as expected to fail:
* `test_sharded_conv2d_with_iree`
* `test_sharded_resnet_block_with_iree`
* `testExportNondecomposed`
* `testExportWithArgumentDeviceAffinities`

[sharktank] Mark tests as expected to fail

---

sharktank/sharktank/layers/mmdit.py

Fixes `RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.` by using `reshape` which occurs when running `tests/layers/mmdit_test.py` with Python 3.11.10 and `torch==2.5.1+cpu`.

[sharktank] Use reshape instead of view

---

.github/workflows/ci-sharktank.yml
sharktank/tests/layers/paged_llama_attention_block_test.py

Progress on https://github.com/nod-ai/shark-ai/issues/357
Extends to test with Python 3.12 and newer `torch` versions on Linux.
For `torch.compile` support on Python 3.12, torch ge 2.4.0 is required. Testing with torch 2.3.0 is therefore skipped when running Python 3.12. To limit the number of jobs, tests are currently only expanded for Linux, whereas Windows (and unpinning NumPy) should be handled in a follow up.
The error logged for `testExportNondecomposed` when failing with torch 2.5.1 slows down the CI by more than 20 minutes, therefore the test is now skipped instead of marked xfail.

[sharktank] Extend to test with Python 3.12

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
.github/workflows/ci-sglang-integration-tests.yml
.github/workflows/ci-shark-ai.yml
.github/workflows/ci-sharktank.yml
.github/workflows/ci_eval.yaml
.github/workflows/ci_eval_short.yaml

As `iree-turbine` is specified in `sharktank/requirements.txt`, the
dependency is already fulfilled and nightlies don't get installed. One
option would be to enforce to `--upgrade` but instead the packages get
not installed before stable releases get pulled in via sharktank's
requirements file. For workflow running on non-GH hosted runners,
`--upgrade` is passed additionaly to avoid using an eventually cached
version on the self-hosted runners.

Explicitly install nightlies

---

.github/workflows/ci-sharktank.yml
sharktank/requirements.txt

`numpy<2.0` is required for Windows with `torch<2.4`. Expanding testing on Windows with Python 3.12 and torch 2.4.1.

[sharktank] Unpin NumPy

---

tuner/examples/test/__init__.py
tuner/examples/test/__main__.py
tuner/examples/test/tuner_test.py
tuner/tuner/candidate_gen.py
tuner/tuner/candidate_gen_test.py
tuner/tuner/common.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_parser.py
tuner/tuner/dispatch_parser_test.py
tuner/tuner/libtuner.py
tuner/tuner/op_matchers.py
tuner/tuner/spec_builder.py

This PR adds direct transform dialect spec generation for candidate configurations. This is the first part of the large refactoring described in https://github.com/nod-ai/shark-ai/pull/577. The way TD specs are generated is by matching against certain types of operations, and then creating a named sequence with `transform.iree.match.cast_compatible_dag_from_root` based on the matched operation. This is done for each configuration found, and the specs are saved to the temporary tuning directory to be used later in tuning.
One main difference in the flow of candidate generation is that state is no longer tracked by saving files to a temporary directory. Instead, ir modules are passed to each function, and only at the very end of candidate generation are the transform dialect specs written …

[tuner] Add direct TD spec generation for candidates

---

.github/workflows/ci-libshortfin.yml
.github/workflows/ci-sharktank.yml

Progress on https://github.com/nod-ai/shark-ai/issues/357.
This gives us a single job in each unit test workflow to set as a "required check" that will block merging, replacing the current single `Unit Tests (3.11, 2.3.0, ubuntu-24.04)` check: 
I'm also switching ci-libshortfin.yml to run on all changes, which is a requirement for making a check required. We could still conditionally skip jobs based on paths modified... just not using GitHub's built in path filtering.

Add unit test summary jobs to sharktank and shortfin workflows.

---

docs/user_guide.md
sharktank/requirements.txt
sharktank/sharktank/__init__.py

Instead of enforcing the installation for 'torch' as a dependency, error if 'torch' cannot be imported and point the user to how to install.

[sharktank] Remove 'torch' from deps and warn instead

---

.github/workflows/ci-sharktank.yml
sharktank/conftest.py
sharktank/integration/models/punet/integration_test.py
sharktank/sharktank/export.py
sharktank/sharktank/layers/base.py
sharktank/sharktank/layers/mmdit.py
sharktank/sharktank/layers/testing.py
sharktank/sharktank/models/flux/export.py
sharktank/sharktank/models/flux/flux.py
sharktank/sharktank/tools/import_hf_dataset.py
sharktank/sharktank/utils/cli.py
sharktank/sharktank/utils/hf_datasets.py
sharktank/tests/models/flux/flux_test.py
sharktank/tests/models/llama/prefill_tests.py

Adapt the model to accept parameters as structured in the HF repo.
Make Punet parameters importation from HF more general to serve other models as well.
When downloading a dataset from Hugging Face make it return the local location of all downloaded files including extras, not just the "leading" file.
Add sample_inputs method to the BaseLayer interface to help standardize exportation.
Introduce a standard export function for static-sized models.

Add Flux transformer export for easier use outside of tests

---

shortfin/build_tools/build_linux_package.sh

Package builds started failing last night when the `latest` upstream manylinux dockerfile switched to gcc 14: https://github.com/nod-ai/shark-ai/actions/runs/12371699664/job/34528374484
```
Running command Building wheel for shortfin (pyproject.toml)
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
...
[325/365] Building CXX object src/shortfin/local/CMakeFiles/shortfin_local.dylib.objects.dir/device.cc.o
FAILED: src/shortfin/local/CMakeFiles/shortfin_local.dylib.objects.dir/device.cc.o
/opt/rh/gcc-toolset-14/root/usr/bin/c++ -DCPUINFO_SUPPORTED_PLATFORM=1 -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -D_SHORTFIN_BUILDING_DYLIB -Dspdlog_EXPORTS -I/home/runner/work/shark-ai/shark-ai/c/shortfin/src …
```

[shortfin] Use custom manylinux dockerfile in build_linux_package.sh.

---

.github/workflows/ci-libshortfin.yml
shortfin/CMakeLists.txt
shortfin/src/shortfin/array/array.cc
shortfin/src/shortfin/local/device.cc
shortfin/src/shortfin/local/fiber.cc
shortfin/src/shortfin/local/program.cc
shortfin/src/shortfin/local/system.cc
shortfin/src/shortfin/local/systems/amdgpu.cc
shortfin/src/shortfin/local/systems/factory.cc
shortfin/src/shortfin/support/config.cc

Bumps libftm to 11.0.2 to mitigate a build error with occurring with
gcc 14. Bumping spdlog to 1.15.0 (which bundles libfmt 11.0.2)
accordingly to keep the libs in sync. Furthermore expands testing
with gcc 14.

[shortfin] Bump fmt and spdlog and test with gcc 14

---

tuner/examples/dispatch/dispatch_tuner.py
tuner/examples/punet/punet_autotune.py
tuner/examples/test/README.md
tuner/examples/test/double_mmt.mlir
tuner/examples/test/tuner_test.py
tuner/tuner/candidate_gen.py
tuner/tuner/dispatch_parser.py
tuner/tuner/libtuner.py
tuner/tuner/op_matchers.py
tuner/tuner/spec_builder.py

This PR adds `benchmark()` and `compile()` functions to the tuner that can be used for both model and dispatch tuning. The new functions will replace the split benchmark/compile_models and benchmark/compile_dispatches functions. The new benchmarking and compilation functions now use the iree_runtime/iree_compiler python bindings which makes much of the code simpler. Particularly, benchmark results are now mostly parsed by the bindings, and the parse_*_benchmark_results functions are no longer needed. The new compilation and benchmarking flows are described below.
1. Populate each CandidateTracker with the input and output filepaths. The input filepaths can be overridden by an optional function argument to the compile() function. This argument can be used for model tuning, passing the …

[tuner] Add unified benchmarking and compilation for models + dispatches

---

.github/workflows/ci-sharktank.yml

Drops passing `--pre` to avoid that pre-releases of torch get installed and switch to stable channel.

[sharktank] Avoid torch pre-releases

---

.gitignore
docs/shortfin/llm/user/e2e_llama8b_mi300x.md
docs/user_guide.md

Progress on https://github.com/nod-ai/shark-ai/issues/691, trying to simplify a few steps before putting this into release notes for 3.1.0.
* Add suggested `export/` directory to `.gitignore` (I'd prefer for the tools to default to a path in the user's homedir, but this is a less invasive change)
* Remove `sharktank` from install instructions as it is included in `shark-ai` nightly releases now
* Rework "Verify server" section to start with a health check then use `curl`. Keep the Python sample code for now, though similar projects usually also have a Python API for interfacing with LLMs. We also don't use a standardized HTTP API yet (like the OpenAI API). Maybe the SGLang integration will be more natural for users.

Iterate on llama user guide.

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/kernels/__init__.py
sharktank/sharktank/kernels/rotary.py
sharktank/sharktank/kernels/templates/rotary_embedding.mlir
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/layers/rotary_embedding.py
sharktank/sharktank/models/llama/llama.py
sharktank/tests/kernels/rotary.py

Reworked rotary embedding application to be performed via a custom kernel. This includes dropping `static_table` for the sake of maintenance (it was largely unused). It includes a simple numerical test however under the hood no numerical change should occur.
Existing baseline vs hugging face remained unchanged.

[llama] Added the fused rotary embedding kernel

---

sharktank/sharktank/kernels/base.py

FlatSymbolRefAttr creation was failing when exporting with `iree` at head due to LLVM changes.

Fix FlatSymbolRefAttr 

---

sharktank/sharktank/models/clip/export.py
sharktank/sharktank/models/clip/export_toy_text_model_iree_test_data.py
sharktank/sharktank/models/clip/testing.py
sharktank/sharktank/utils/io.py
sharktank/tests/models/clip/clip_test.py

This is required to have an easy way of exporting test data that will be
used in IREE to guard against regressions.
E.g.
```
python -m sharktank.models.clip.export_toy_text_model_iree_test_data \
--output-dir=clip_toy_text_model
```
Refactor some of the existing tests to reuse the new export logic.

Add CLI script exporting CLIP Toy model IREE test data

---

sharktank/pyproject.toml
sharktank/requirements-dev.txt
sharktank/requirements.txt
sharktank/sharktank/models/flux/export.py
sharktank/sharktank/models/flux/flux.py
sharktank/sharktank/models/flux/testing.py
sharktank/sharktank/tools/upload_all_models_to_azure.py
sharktank/sharktank/types/theta.py
sharktank/sharktank/utils/azure.py
sharktank/sharktank/utils/hf_datasets.py
sharktank/tests/models/flux/flux_test.py

There was a slight difference in the Flux schnell and dev variants. Namely, dev has a guidance layer and schenll does not.
Fixed some tensor argument element value types as they were always passed as f32 while some of them should use the model's dtype.
Refactored a bit the Flux transformer export boilerplate.
Added a script that uploads models to Azure. Right now it uploads the Flux transformer models.
This can become a part of the CI jobs at some point.

Add export of Flux-dev transformer and uploading to Azure

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
.github/workflows/ci_eval.yaml
.github/workflows/ci_eval_short.yaml

Some of these workflows have been failing with
```
>           hal_device_id = haldriver.query_available_devices()[device_idx]["device_id"]
E           IndexError: list index out of range
sharktank/sharktank/utils/vmfb_runner.py:38: IndexError
```
Example logs: https://github.com/nod-ai/shark-ai/actions/workflows/ci_eval_short.yaml?query=branch%3Amain
Rather than assume that self-hosted runners will have multiple GPUs available and having each workflow use a specific device index, we can use the default device and have the runners themselves choose which devices to make visible.

Switch eval and llama tests to use the default hip device.

---

sharktank/sharktank/models/flux/flux.py
sharktank/sharktank/models/flux/testing.py
sharktank/sharktank/utils/iree.py
sharktank/tests/models/flux/flux_test.py

The test accuracy is not of sufficient quality and needs further investigation.
The tests compare IREE bf16 and f32 against Torch f32.
Refactor the sample input generation and make it produce noise images for final size of 1024x1024 instead of 512x512.
Remove unused duplicated function for random Theta generation.

Add xfail tests for single layer Flux transformer that verify IREE results against Torch

---

sharktank/tests/models/flux/flux_test.py

Tests introuced by https://github.com/nod-ai/shark-ai/pull/741 would actually hang during IREE compilation without one pending fix.

Disable Flux transformer tests that hang

---

.github/workflows/ci-sglang-benchmark.yml
app_tests/benchmark_tests/llm/sglang_benchmarks/shortfin_benchmark_test.py

[SGLang Benchmark Test](https://github.com/nod-ai/shark-ai/actions/workflows/ci-sglang-benchmark.yml) has been failing at the compilation step. Bumping IREE version to the stable versions pushed in #721 fixes the issue.

Bump stable IREE version for sgl-benchmark

---

sharktank/requirements.txt

These are included in shortfin now: https://github.com/nod-ai/shark-ai/blob/5f08cb2354c928476ace3cfdcda3b835dd13cd61/shortfin/pyproject.toml#L42-L43

Remove serving deps from sharktank/requirements.txt.

---

.github/workflows/ci-shark-ai.yml
app_tests/benchmark_tests/llm/sglang_benchmarks/shortfin_benchmark_test.py
app_tests/integration_tests/llm/sglang/conftest.py
app_tests/integration_tests/llm/sglang/sglang_frontend_test.py
app_tests/integration_tests/llm/shortfin/conftest.py
app_tests/integration_tests/llm/shortfin/cpu_llm_server_test.py
app_tests/integration_tests/llm/utils.py

The available_ports fixture seems to rely on the servers booting very quickly to work. Merging it into the llm_server & increasing the server startup timeout fixes the remaining CI failures caused by updating IREE to 1220.

Merge fixtures: available_port into llm_server

---

shortfin/python/shortfin_apps/sd/components/config_artifacts.py

This is a band-aid patch.
We encountered a regression in under-load behavior (tracked by https://github.com/nod-ai/shark-ai/issues/753)
This effectively uses a different allocator that, while less efficient at multi-device inference execution, is more stable.

(sdxl) Updates server configurations to run with caching allocator by default.

---

docs/shortfin/llm/user/llama_serving.md
docs/user_guide.md

Adds a note to [llama_serving.md](https://github.com/nod-ai/shark-ai/blob/main/docs/shortfin/llm/user/llama_serving.md) that instructs the user how to convert a collection of `.safetensor` weight files to a single `.gguf` file that can be used in the instructions that follow.

Add user instructions for converting safetensors to gguf

---

shortfin/tests/invocation/conftest.py

This option was added in https://github.com/iree-org/iree/commit/d4975713a0aa3ba872807fc16585fb4b5a04e41d.

Use --opset-version provided by iree-import-onnx.

---

.github/workflows/ci_linux_x64_asan-libshortfin.yml
.github/workflows/ci_linux_x64_nogil-libshortfin.yml
requirements-iree-pinned.txt
shortfin/tests/invocation/mobilenet_program_test.py

Note that the mobilenet program being tested was miscompiling and producing different output compared to onnxruntime prior to https://github.com/iree-org/iree/commit/d48071df356eec533554699ac1e658f6809aacbe.

Bump pinned IREE version to 20241206.

---

tuner/tuner/candidate_gen.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_constraints_test.py

The `test_generate_tile_and_fuse_constraints*` tests have a long run time due to the complex constraint problem they are solving. This PR reduces the complexity of the problem to improve the run time of the test.

[tuner] Tweak tile and fuse constraints and test to reduce run time

---

tuner/examples/simple/simple_tuner.py
tuner/tuner/candidate_gen_test.py
tuner/tuner/common.py
tuner/tuner/common_test.py
tuner/tuner/dispatch_constraints_test.py
tuner/tuner/dispatch_parser_test.py
tuner/tuner/libtuner.py
tuner/tuner/op_matchers.py

This PR is about addressing the MLIR context management issue in the tuner detailed in https://github.com/nod-ai/shark-ai/issues/764.
Although this is a work in progress, I am sending it to gather feedback and ensure I am heading in the right direction.

[Tuner] Fix context management

---

.github/workflows/ci_linux_x64_asan-libshortfin.yml
docs/developer_guide.md

Updates python to 2.5.0 and sets the Python version to 3.12.8. Furthermore, follows the recommendation in the v2.5.0 release notes to use `pyenv init - <shell>` instead of `pyenv init -` as this should show better performance.

Update pyenv to 2.5.0 and Python version

---

tuner/examples/simple/simple_tuner.py

This PR addresses the TODO in `tuner/examples/simple/simple_tuner.py` to remove the unused abstract function implementations in the tuner client. The PR also renames some variables to be more consistent with the name of the example.

[tuner] Clean up simple tuner example script

---

sharktank/requirements-tests.txt

Fixes https://github.com/nod-ai/shark-ai/issues/787. See the workflow passing now: https://github.com/nod-ai/shark-ai/actions/runs/12676783895/job/35330696315?pr=788.
We could also install another package that transitively includes `protobuf`, like `transformers[sentencepiece]` or `onnx`. I'm also not sure if this should be a test requirement or a release requirement, given how limited and indirect the usage is, so just starting simple and explicit.

Add missing requirements for sharktank t5 tests.

---

build_tools/python_deploy/pypi_deploy.sh

Adding `-stable` fixes
```
Computing local versions for sharktank and shortfin...
usage: compute_local_version.py [-h] [--write-json] (-stable | -rc | -dev | --version-suffix VERSION_SUFFIX) path
compute_local_version.py: error: one of the arguments -stable/--stable-release -rc/--nightly-release -dev/--development-release --version-suffix is required
```
Adding `--write-json` fixes the `write_requirements.py` step from either
* using previously written JSON files if present (resulting in old version pins in the meta package, oops!)
* failing to open files that don't exist (failing to release, but at least not using the wrong versions)
Future changes should put more logging in place and add a confirmation step. I only caught this because I ran _part_ of the script and paused to verify …

Patch version computations in pypi_deploy.sh.

---

docs/developer_guide.md

Advise to install the latest nightly release instead of cloning and installing and editable version of iree-turbine.

Point to iree-turbine nightly releases

---

sharktank/version.json
shortfin/version.json
tuner/version.json

We just published version 3.1.0: https://github.com/nod-ai/shark-ai/releases/tag/v3.1.0.

Bump version to 3.2.0 after releasing 3.1.0.

---

tuner/tuner/candidate_gen.py
tuner/tuner/common.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_constraints_test.py
tuner/tuner/libtuner.py

This PR adds some command line arguments to tune pipeline options. The new flags are `--prefetch-shared-memory-options`, `--no-reduce-shared-memory-bank-conflicts-options`, and `--waves-per-eu-options`. The flags take a comma separated list of values (bool or int), representing the possible values that the corresponding pipeline options can take in tuning.
This PR also adds `promote_operands = [0, 1]` to the TileAndFuse tuning configurations. This could potentially be a tuned parameter in the future, but for now it is typically good to promote the lhs and rhs operands.

[tuner] Allow tuning of pipeline options

---

tuner/tuner/candidate_gen.py
tuner/tuner/libtuner.py

This PR changes the format of generated TD specs to inline the compilation info into the matcher function. This makes splitting the TD spec and combining with others after tuning much easier.

[tuner] Write candidate specs with local scope

---

tuner/examples/simple/simple_tuner.py
tuner/tuner/libtuner.py

This PR adds a timeout for compilation to prevent the tuner from hanging when iree-compile hangs. The `iree.compiler.compile_file` binding is no longer used, since it does not support a timeout. Instead, the command is run as a regular subprocess.

[tuner] Add timeout for compilation in TuningClient

---

requirements-iree-pinned.txt

See https://github.com/nod-ai/shark-ai/issues/760 for context. We want to stay close to the latest versions while still pinning versions for predictability. Updating version pins is currently a manual process but we plan on automating it in the future.
We can decide how noisy we want these dependency updates to be:
* new PRs daily or less frequently
* do or don't reuse existing PRs
* merge ASAP or let them sit for multiple days

Bump IREE version pins to 3.2.0rc20250109.

---

.github/workflows/ci-sglang-benchmark.yml
pytorch-cpu-requirements.txt
requirements-iree-pinned.txt

Drops `--pre` and `--upgrade` where dependencies are pinned to specific versions. Further switches to unstall torch cpu form the stable release channel.

Drop unneeded pip flags and switch torch channel

---

tuner/examples/simple/simple_tuner.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/libtuner.py

* Add model-specific benchmark timeout
* Fix benchmark argument parsing to allow for `=` in command line argument values
* Don't print candidate trackers at the very end (too much noise)
* Always promote operands

[Tuner] Fix large model benchmarking

---

tuner/tuner/candidate_gen.py
tuner/tuner/libtuner.py

This PR aims to the log size detailed in: https://github.com/nod-ai/shark-ai/issues/806
- Avoid printing the stdout and stderr of running the command 
- Reduce the precision of fp constants printed

[tuner] reduce log file size

---

shortfin/CMakeLists.txt

This updates to https://github.com/iree-org/iree/commit/9055c9d1f6342a061a6747ef9b385816b96a0a8f. Diff: https://github.com/iree-org/iree/compare/iree-3.1.0rc20241220...9055c9d1f6342a061a6747ef9b385816b96a0a8f. Notably, this pulls in many performance improvements and bug fixes to https://github.com/iree-org/iree/tree/main/runtime/src/iree/hal/drivers/hip.
See discussion on https://github.com/nod-ai/shark-ai/pull/773 and https://github.com/nod-ai/shark-ai/pull/802 .

Bump IREE runtime pin used in shortfin close to latest.

---

.github/workflows/ci-libshortfin.yml
shortfin/CMakeLists.txt

Also update the pinned IREE commit used for building shortfin now that a fix for Tracy on gcc has landed.

[shortfin] Add a tracing enabled CI job.

---

tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_constraints_test.py

This PR adds support for tuning IGEMM with TileAndFuse convolutions. The PR sets the lowering pipeline options for convolutions on the TileAndFuse pipeline to be the IGEMM options, and adjusts the problem size accordingly when generating candidate constraints.

[Tuner] Use IGEMM for TileAndFuse conv tuning

---

requirements-iree-pinned.txt
shortfin/CMakeLists.txt

Changes: https://github.com/iree-org/iree/compare/iree-3.2.0rc20250109...iree-3.2.0rc20250113
Still working on automating these version updates.

Bump pinned IREE versions to 3.2.0rc20250113.

---

app_tests/integration_tests/llm/device_settings.py
app_tests/integration_tests/llm/model_management.py
app_tests/integration_tests/llm/server_management.py
app_tests/integration_tests/llm/shortfin/conftest.py
app_tests/integration_tests/llm/shortfin/cpu_llm_server_test.py

Bundled up loose parameter passing in the testing infra to support support easily adding models from HF, Azure, and local like:
```python
TEST_MODELS = {
"open_llama_3b": ModelConfig(
source=ModelSource.HUGGINGFACE,
repo_id="SlyEcho/open_llama_3b_v2_gguf",
model_file="open-llama-3b-v2-f16.gguf",
tokenizer_id="openlm-research/open_llama_3b_v2",
batch_sizes=(1, 4),
device_settings=device_settings.CPU,
),
"llama3.1_8b": ModelConfig(
source=ModelSource.LOCAL,
local_path=Path("/data/llama3.1/8b/llama8b_f16.irpa"),
model_file="llama8b_f16.irpa",
tokenizer_id="NousResearch/Meta-Llama-3.1-8B",
batch_sizes=(1, 4),
device_settings=device_settings.CPU,
),
"azure_llama": ModelConfig(
source=ModelSource.AZURE,
azure_config=AzureConfig(
account_name="sharkblobs",
container_name="halo-models", …
```

Refactor `app_tests/integration_tests/llm` for easy addition of more models for testing

---

tuner/examples/simple/simple_tuner.py
tuner/tuner/candidate_gen.py
tuner/tuner/common.py
tuner/tuner/dispatch_constraints.py
tuner/tuner/dispatch_parser.py
tuner/tuner/libtuner.py
tuner/tuner/libtuner_test.py

This PR addresses the task described in https://github.com/nod-ai/shark-ai/issues/806.
It adds a separate output file to the tuner to summarize the most important information, such as the top candidates (dispatch and model) and paths to their specifications.
Also, it fixes the issue with incorrect reporting of the compilation success rate in the log.

[tuner] add the output file

---

sharktank/tests/models/vae/vae_test.py

Reverts nod-ai/shark-ai#775: failing tests fixed by changing CI system to stable rocm version

Revert "Mark sharktank vae iree test as xfail"

---

sharktank/sharktank/models/vae/README.md
sharktank/sharktank/models/vae/tools/diffuser_ref.py
sharktank/sharktank/models/vae/tools/run_vae.py
sharktank/tests/models/vae/vae_test.py

Merges the diffusers reference models for sdxl and flux vae models. 
Also renames the exported function to decode from forward to avoid confusion with vae encode to be added in the future

Some cleanup on flux integration

---

.github/workflows/update_iree_requirement_pins.yml

This allows the created pull requests to run checks based on the `pull_request` trigger. See the documentation here:
* https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
* https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
Tested here:
* https://github.com/nod-ai/shark-ai/actions/runs/12819231996/job/35746461928
* https://github.com/nod-ai/shark-ai/pull/835

Generate token for create-pull-request action using an app.

---

shortfin/python/shortfin_apps/llm/components/kvcache/page_pool.py
shortfin/python/shortfin_apps/llm/components/kvcache/trie_attention_cache.py
shortfin/tests/apps/llm/components/kvcache/base_attention_cache_test.py

Added them when I first implemented page_pool for some concurrency related tracking, but we should get rid of them until we actually need to use them.

Remove some unused variables in page_pool

---

shortfin/python/lib_ext.cc
shortfin/src/shortfin/local/program.cc
shortfin/src/shortfin/local/program.h

Currently, when we load model parameter files, we load the entire contents of the files into memory, then mmap that data to the devices. This would cause very long server startup times. For example, 70b (~130 GB) took me 10 minutes to start the server, and 405b (~750 GB) took me over `5 hours` to start the server.
As an alternative, this PR uses `iree_io_file_handle_open` to obtain a handle to the parameter files, then streams that data to the devices, insteading of mmaping it. After this change, we are able to start the server for `70b` and `405b` within seconds.
We default to the new method and add a private function `LoadMmap` for cases where `mmap == true`. This should improve the startup time for both `LLM` and `SDXL`, especially when loading large files.

Fast server startup, using file_handle to load model param files

---

shortfin/python/shortfin_apps/sd/components/messages.py
shortfin/python/shortfin_apps/sd/components/service.py

`sd.server` currently performs tokenization irrespective of whether the request has `input_ids` attached to it.
This patch adds a check to skip tokenization if the request has tokenized inputs attached to it, and adds `input_ids` to `gen_inputs` so that such requests can be created from `InferenceExecRequests.from_batch()`.

[shortfin][python] Skip tokenization in sd.server if request holds `input_ids`

---

shortfin/CMakeLists.txt
shortfin/src/shortfin/support/blocking_executor.cc

The C++ bit solves a data race reported by TSan, see #847.
The CMake bit mimics what exists for ASAN and removes an incorrect `# Enable more ASAN checks` comment. The `IREE_SANITIZER_` are used in core logic to check against mismatches between the IREE runtime and the libraries it loads.
https://github.com/iree-org/iree/blob/db129e500f35ead4debc363eb15ebfb929ee512b/runtime/src/iree/hal/local/loaders/system_library_loader.c#L168-L178
Fixes #847

Fix a data race and add a CMake TSan option.

---

sharktank/sharktank/export_layer/export_paged_attention.py
sharktank/sharktank/layers/kv_cache.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/grok/grok.py
sharktank/sharktank/models/llama/llama.py
sharktank/sharktank/models/mixtral/mixtral.py
sharktank/tests/layers/kv_cache_test.py
sharktank/tests/layers/sharded_paged_kv_cache_test.py

The in-place read for KVCache doesn't seem to be used and is just used to tell the KVCache number of partitions to read from. The number of partitions for KVCache is in reality fixed (as from the name, K/V cache) and we are adding overhead by passing this parameter.

[Llama] Remove inplace read for KVCache

---

app_tests/integration_tests/llm/shortfin/conftest.py
app_tests/integration_tests/llm/shortfin/cpu_llm_server_test.py
shortfin/python/shortfin_apps/llm/components/generate.py

The mlperf harness that I'm building sends over input_ids instead of text. We had the option to send input_ids in a request, but never actually implemented it. This makes it so that you can either send a string prompt or a pre-tokenized prompt.

Accept token_ids in Shortfin LLM Server

---

docs/debug_flags.md
sharktank/requirements-tests.txt
sharktank/sharktank/layers/base.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/flux/flux.py
sharktank/sharktank/models/flux/testing.py
sharktank/sharktank/models/punet/model.py
sharktank/sharktank/models/vae/model.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/utils/debugging.py
sharktank/sharktank/utils/iree.py
sharktank/sharktank/utils/testing.py
sharktank/tests/ops/ops_test.py

We don't have an op that dispatches to the underlying iree.turbine.ops.iree.trace_tensor.
With this change we can trace into safetensors files when executing both in eager and with IREE.
Routes all tracing through the new tracing op. The user can set a desired sink.
Added some functionality to prefix trace keys based on the module structure.
Something that I could not preserve is the tensor trace counter. It is a global variable and when exporting we pass multiple times through the traced function, which makes the counter inconsistent. The only way to distinguish traced tensors is through the trace keys.
The distinction between tensor tracing and goldens tracing has been remove at the point of issuing a trace. If the user needs different treatment they can customize the trace sink.

Add trace_tensor op and refactor tensor tracing

---

.github/workflows/ci-sharktank.yml
sharktank/requirements-tests.txt

Some of these jobs have been taking the full [6 hour default timeout](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) before failing. Example stalls:
* https://github.com/nod-ai/shark-ai/actions/runs/12875057753/job/35895676842
* https://github.com/nod-ai/shark-ai/actions/runs/12948380437/job/36116930181
* https://github.com/nod-ai/shark-ai/actions/runs/12939601933/job/36092205910
Introducing timeouts in the test runner gives us a chance of seeing a callstack when a test case is stalled and not burning CI time. Sample output from using a shorter timeout:
Job name | Logs
-- | --
Data-dependent Tests | https://github.com/nod-ai/shark-ai/actions/runs/12953817421/job/36134335605
Model Integration Tests | …

[sharktank] Use pytest-timeout in ci-sharktank.yml.

---

app_tests/integration_tests/llm/shortfin/cpu_llm_server_test.py
shortfin/python/shortfin_apps/llm/components/service.py

Earlier, I changed the generation requests to store the whole token history instead of just the most recent token.
Missed a spot, which caused seq_len to be a lot longer than it should be, which caused the kvcache read to be wrong.

Fix Masking-related token corruption issue that oddly only manifests when trie is enabled

---

app_tests/integration_tests/llm/shortfin/conftest.py
app_tests/integration_tests/llm/shortfin/cpu_llm_server_test.py

By temporarily skipping local model tests.
Working on removing all local-model tests because we want CI machines to be interchangeable and want to not have to depend on local files.

Fix LLM CI by temporarily skipping local model tests.

---

sharktank/sharktank/examples/paged_llm_v1.py
sharktank/sharktank/kernels/bitcast.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/layers/ffn_block.py
sharktank/sharktank/layers/linear.py
sharktank/sharktank/layers/norm.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/llama/llama.py
sharktank/sharktank/models/llama/tools/import_quark_dataset.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/qlinear_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/utils/export_artifacts.py
sharktank/sharktank/utils/patching.py
sharktank/tests/models/llama/benchmark_amdgpu_test.py
sharktank/tests/models/llama/quark_parity_test.py
sharktank/tests/ops/ops_test.py

This patch enables the use of quark quantized models of the latest generation. Many changes were required to enable parity with the source model which is very sensitive to any numerical fluctuations. There is a test added to maintain this parity but is disabled until I can get the relevant data set up on the ci machine.

[Sharktank][Llama][FP8] Minimal changes for numerically correct fp8

---

requirements-iree-pinned.txt
shortfin/CMakeLists.txt

Reverts nod-ai/shark-ai#867
This might have regressed something in the "Data-dependent Tests" job. Seeing more jobs hitting 6 hour timeouts :/

Revert "Bump IREE requirement pins to their latest versions."

---

sharktank/sharktank/utils/iree.py
sharktank/tests/models/clip/clip_test.py
sharktank/tests/models/flux/flux_test.py
sharktank/tests/models/llama/sharded_llama_test.py
sharktank/tests/models/t5/t5_test.py
sharktank/tests/models/vae/vae_test.py
sharktank/tests/ops/ops_test.py

It did not sit right that run_iree_module_function would create a HAL device just to make iree.runtime.FunctionInvoker happy.

Change run_iree_module_function to accept HAL device instead of driver name

---

sharktank/tests/models/llama/benchmark_amdgpu_test.py

Benchmarking test for fp8 was failing the Export phase, but was expected to fail for the Benchmarking phase and was getting killed.

Fix llama 8b fp8 benchmarking test

---

sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/layers/mixture_of_experts_block.py
sharktank/sharktank/layers/testing.py
sharktank/sharktank/models/deepseek/__init__.py
sharktank/sharktank/models/deepseek/deepseek.py
sharktank/sharktank/models/deepseek/run_deepseek.py
sharktank/sharktank/models/deepseek/testing.py
sharktank/sharktank/models/deepseek/toy_deepseek.py
sharktank/sharktank/models/grok/grok.py
sharktank/sharktank/models/mixtral/mixtral.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/tools/import_deepseek.py
sharktank/tests/models/deepseek/test_deepseek.py
sharktank/tests/models/llama/moe_block_test.py

This adds an e2e implementation of deepseek for prefill. Additional features were required by the MoE block, specifically surrounding how gate scores are computed and including mixture of experts.
A latent attention implementation is also included though this is a reference implementation that does not take advantage of the latent space during decode.

Add deepseek v3 model support

---

docs/shortfin/llm/user/llama_serving.md

This PR adds a support table to our `llama_serving.md` guide, specifying our supported variants of `llama3.1-8b, llama3.1-70b, llama3.1-405b`. 
I used [vLLM Supported Models](https://docs.vllm.ai/en/v0.4.2/models/supported_models.html#supported-models) as a reference. I changed the structure a bit to make more sense for our server, but it's relatively similar to how they set their table up.
For sharding instructions, I added a section at the end of our doc. I debated between creating a separate `md` file for it, but I think it actually makes sense where it is. It gives our doc a flow where we give detailed descriptions of what's going on while the user gets setup with the lowest-barrier model. Following that, you get to the more advanced sharding section. The details aren't as specific …

Llama support table + sharding docs

---

.github/workflows/ci-sharktank.yml
sharktank/sharktank/tools/import_hf_dataset.py
sharktank/tests/models/clip/clip_test.py
sharktank/tests/models/flux/flux_test.py
sharktank/tests/models/t5/t5_test.py

Logging more information as tests run will help with the triage process for issues like https://github.com/nod-ai/shark-ai/issues/888.
Logs before: https://github.com/nod-ai/shark-ai/actions/runs/13150995160/job/36698277502#step:6:27
Logs after: https://github.com/nod-ai/shark-ai/actions/runs/13168068091/job/36752792808?pr=917#step:6:29

Add more logging to sharktank data tests.

---

shortfin/python/shortfin_apps/llm/components/service_debug_dumper.py

Value currently being read from incorrect object, causing debug mode to fail with an AttributeError.

Fix wrong reference to prefix_sharing_algorithm

---

docs/shortfin/llm/user/llama_serving.md

Add a warning for sharded llama accuracy until https://github.com/iree-org/iree/issues/19948 is resolved.

Add a warning for sharded llama accuracy

---

sharktank/sharktank/utils/testing.py
sharktank/tests/models/t5/t5_test.py

There were several xfail tests with bad metric. Cosine similarity is a better metric for language embeddings.
The comparison between bf16 and f32 exhibits a small fraction of outliers that have a higher per-token numerical error than the majority of tokens. To account for that the testing metric is expanded to test for inlier and outlier absolute tolerance.

Make the T5 model tests use cosine similarity

---

sharktank/version.json
shortfin/version.json
tuner/version.json

See the 3.2.0 release tracker at https://github.com/iree-org/iree/issues/19641 and published release at https://github.com/nod-ai/shark-ai/releases/tag/v3.2.0.

Bump version to 3.3.0 after releasing 3.2.0.

---

docs/shortfin/llm/user/llama_serving.md

Use llama chat tags in example requests.
More details on this can be found [here](https://github.com/nod-ai/shark-ai/issues/934#issuecomment-2649718739)

Use llama chat tags in example requests

---

sharktank/sharktank/utils/hf_datasets.py

The tokenizers specified for this dataset are for `llama3_8b_fp16`, while the model is `llama3_8b_fp16_instruct`. The `eos_token` for `8b` and `8b-instruct` are different:
```text
8b:
<|begin_of_text|> {generated_text} <|end_of_text|>
<|end_of_text|> - 128001
8b-Instruct:
<|begin_of_text|> {generated_text} <|eot_id|>
<|eot_id|> - 128009
```
Using the wrong config causes Llama to output text forever. Our model generated `128009`s, but the server doesn't recognize it as the proper stop token and keeps calling for generations.
More details [here](https://github.com/nod-ai/shark-ai/issues/934#issuecomment-2649718739)

Use llama-8b-instruct tokenizer.json and tokenizer_config.json for `llama3_8b_fp16` dataset

---

shortfin/python/shortfin_apps/sd/components/service.py

Added logging via `@measure` (and other metrics.py functions) for the individual phases of SDXL to the sdxl shortfin server, including an average for the step portion of unet.

Add metrics to sdxl phases

---

docs/shortfin/llm/user/llama_serving.md

Update shortfin user instructions to use up to the supported torch version of 2.5.1+cpu. The exported IR using torch2.6.0+cpu fails to compile and needs further investigating.

Update shortfin user instructions to use up to the supported torch version of 2.5.1+cpu

---

shortfin/python/array_binding.cc
shortfin/python/array_host_ops.cc
shortfin/tests/api/array_ops_test.py

I don't fully understand the surrounding code, but I made this thin wrapper and it seems to mostly work. Let me know if you see any glaring issues, because I'm debugging Flux BF16 on top of this and can't pinpoint the issue.
It probably makes sense to move the type definition to another file, I was just hacking on it. Trying to figure out where things belong too.
(For reference I tried working with the __bf16 clang type, but it didn't have enough support so I decided to make this from scratch/uint16 instead)

Add a bf16 datatype to sfnp

---

shortfin/python/shortfin_apps/llm/application.py
shortfin/python/shortfin_apps/llm/lifecycle_hooks.py
shortfin/python/shortfin_apps/llm/routes/__init__.py
shortfin/python/shortfin_apps/llm/routes/application.py
shortfin/python/shortfin_apps/llm/routes/generate.py
shortfin/python/shortfin_apps/llm/server.py

From an application standpoint, the code that we have to startup our server, add routes, add lifecycle hooks, etc. is very tightly-coupled and doesn't provide room for scale. It also makes it a bit difficult to debug and write unit tests for the individual components.
This separates the logic for starting the server, creating the FastAPI application, registering lifecycle hooks, and adding new routes.
It should make it pretty quick to expand upon each component individually, and will allow us to add more features to the server cleanly.
As a manual validation step (along with our CI), I ran my script that sends 30 requests concurrently, results for that [here](https://gist.github.com/stbaione/23673f7a8945b9b18eb7ffcfcebed8bc)

Decouple code for server startup, lifecycle hooks, FastAPI app, and routes

---

shortfin/python/shortfin_apps/llm/components/config_struct.py

These were accidentally introduced and never used.

[shortfin llm] Remove unused ServerParams fields

---

shortfin/python/shortfin_apps/llm/application.py
shortfin/python/shortfin_apps/sd/server.py

We need to add the `CORSMiddleware` to our server in order to receive requests from [shark-ui](https://github.com/nod-ai/shark-ui), otherwise they get denied.
Here's a quick article on [CORS](https://auth0.com/blog/cors-tutorial-a-guide-to-cross-origin-resource-sharing/).
@bjacobgordon and I would like to hear your thoughts on if we need further restrictions or not. Specifically, if the origins need to be restricted.
What the origin settings does, is disallow requests from clients, unless those clients either belong to some specific ip address or ip subnet, or belong to some specified domain. So, for example, if we had a top-secret govt project, we'd say, only these 4 ip addresses are allowed to send requests to our server.
Normally, in a commercial deployment scenario, this is a …

Add CORSMiddleware to shortfin servers

---

shortfin/python/shortfin_apps/sd/components/config_struct.py
shortfin/python/shortfin_apps/sd/components/generate.py
shortfin/python/shortfin_apps/sd/components/messages.py
shortfin/python/shortfin_apps/sd/components/service.py
shortfin/python/shortfin_apps/sd/python_pipe.py

This PR non-trivially restructures the SDXL inference process to interface with reusable command buffers.
At service startup, we attach to each fiber a set of reusable command buffers (a set of empty device arrays to be reused throughout the inference process), and upon assigning each exec request a fiber (now the "meta_fiber" equipped with command buffers), we pop an appropriate command buffer from the meta fiber, mount the command buffer on the request, and return the command buffer to the meta_fiber for reuse.
Each meta_fiber is equipped with an explicit number of command buffers, and if this count is exceeded by the number of InferenceExecProcesses assigned to the fiber, a new command buffer will be initialized ad-hoc. This _shouldn't_ happen if service is managed properly, as we …

[shortfin-sd] Reusable service command buffers

---

.github/workflows/pkgci_shark_ai.yml
app_tests/benchmark_tests/llm/sglang_benchmarks/conftest.py
app_tests/integration_tests/llm/model_management.py
app_tests/integration_tests/llm/sglang/conftest.py
app_tests/integration_tests/llm/shortfin/conftest.py
app_tests/integration_tests/llm/shortfin/tinystories_llama2_25m_test.py

This is a tiny model that would take less than a minute to download / export / compile.
The smoke test is intended to run before we run the full integration CI suite. This would give us early visibility into shortfin failures & save CI resources. 
This PR adds an integration_tests function to:
- download hf repo with `model.safetensors`
- convert to gguf 
- convert to irpa
Closes #933

[shortfin llm integration tests] Add tinystories llama2 25m model as a smoke test

---

shortfin/python/shortfin_apps/llm/components/messages.py
shortfin/tests/apps/llm/components/messages_test.py

In the cycle leading up to the 3.2.0 release, we had some trouble triaging CI error reports / routing bugs to the appropriate teams / people. This and #917 are part of that.
The plan is to make shortfin's llm server log all relevant InferenceExecRequests when something (e.g. kvcache allocations / nans in logits) doesn't check out.

Add InferenceExecRequest.__repr__() for debug logging

---

sharktank/sharktank/layers/paged_llama_attention_block.py

This assumes the `qkv` matrices are square which is not a requirement for the attention block. Moving / updating the assertion enables architectures that do not impose this restriction.

Move attention block assertion for shape

---

shortfin/python/shortfin_apps/sd/components/service.py

The output array was coming out empty.  We discovered that the `await device` needs to be moved after the transfer to host but before the device array's `items` is read.

SDXL app: move await device to fix empty results

---

shortfin/python/lib_ext.cc
shortfin/src/shortfin/array/array.cc
shortfin/src/shortfin/array/array.h
shortfin/src/shortfin/array/storage.cc
shortfin/src/shortfin/array/storage.h
shortfin/src/shortfin/local/fiber.h
shortfin/src/shortfin/local/program.cc
shortfin/src/shortfin/local/program.h
shortfin/src/shortfin/local/program_interfaces.h
shortfin/src/shortfin/local/scheduler.cc
shortfin/src/shortfin/local/scheduler.h
shortfin/src/shortfin/support/iree_helpers.cc
shortfin/src/shortfin/support/iree_helpers.h
shortfin/tests/invocation/mobilenet_program_test.py

* Device allocations are now async, queue ordered alloc/dealloc.
* Program invocations asynchronously deallocate function call results if it can. If it ever cannot, then a small tracy zone `SyncImportTimelineResource` will be emitted per result that cannot be async deallocated.
* Adds `ProgramInvocation.assume_no_alias` instance boolean to disable the assumption which allows async deallocation to work.
* Adds global `ProgramIncovation.global_no_alias` property to control process-wide.
This is a very fiddly optimization which requires (esp in multi-device cases) a number of things to line up. Tested on amdgpu and CPU with a number of sample workloads (with logging enabled and visually confirmed).
See #980 for detailed analysis and further work required.

[shortfin] Implement async alloc/dealloc of buffers.

---

sharktank/sharktank/examples/export_paged_llm_v1.py

When you attempt to implicitly null-check the attention_mask, you hit a torch error:
```bash
RuntimeError: Cannot call numel() on tensor with symbolic sizes/strides
```
Simply adding an explicit check for null fixes it, and the `--use-attention-mask` export path for prefill

Explicitly check for None when using prefill `attn_mask`

---

sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/models/t5/export.py
sharktank/sharktank/models/t5/t5.py
sharktank/sharktank/utils/iree.py
sharktank/tests/models/t5/t5_test.py

We don't want the stack to depend on the conversion tool from the lamma.cpp repo. Also the conversion to GGUF would not convert all tensors to bf16, but leave some in f32. We would like to control that ourselves if needed.
This change makes any previously generated IRPA files obsolete.

Don't use GGUF but convert T5 directly from Hugging Face

---

shortfin/python/shortfin_apps/sd/server.py
shortfin/python/shortfin_apps/sd/simple_client.py

Check that specified ports are valid. Otherwise the server and the client will hang forever without any errors or warnings.

[Shortfin][SD] Error out on invalid ports

---

sharktank/sharktank/layers/kv_cache.py

Slices can merge efficiently with with the attention / GQA kernels so its more computationally efficient single gather until gather fusion is better.

Make kv_cache read operation perform a single gather

---

.github/workflows/ci-sglang-benchmark.yml
.github/workflows/pkgci_shark_ai.yml

Pins some not yet pinned actions, as recommended by the OpenSSF scorecard project:
https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
Further adds comments to point to the tags that the hashes are associated with.

Pin actions (and add missing tags)

---

.github/workflows/pkgci_shark_ai.yml
app_tests/integration_tests/llm/shortfin/meta_llama31_8b_llm_server_test.py
app_tests/integration_tests/llm/shortfin/open_llama_3b_llm_server_test.py
app_tests/integration_tests/llm/shortfin/tinystories_llama2_25m_test.py

Had to do this because the cpu integration tests were flaking out.
Also moves the cpu smoke test to standard github runner `azure-cpubuilder-linux-scale` because it's small enough mem-wise.
Issue created to add these back after we fix the problem in #1030

Resolve CPU llm smoke / integration test hangs by temporarily removing 8-request testcases

---

tuner/tuner/spec_builder.py

This PR adds the default attribute `iree_codegen.tuning_spec_with_default_entrypoint` to the generated tuning spec. 
fixes #816

[tuner] add default attribute to tuning spec

---

shortfin/python/lib_ext.cc

Fixes typo from 'amgdpu' to 'amdgpu' in the docstring

Fixes typo from 'amgdpu' to 'amdgpu' in the docstring

---

sharktank/sharktank/utils/iree.py

This allows to inject what exact IREE device(s) are to be used without propagating all the way to program arguments.
Example:
```
IREE_DEVICE=hip://5,hip://3 pytest sharktank/tests
```

Make get_iree_devices read IREE_DEVICE env var if provided

---

sharktank/sharktank/models/flux/export.py
sharktank/sharktank/models/flux/export_flux_transformer_mlir.py

E.g.
```
python -m sharktank.models.flux.export_flux_transformer_mlir \
--output-path=model.mlir \
--parameters-path=model.irpa
```

[sharktank] Add a more convenient way to export Flux transformer MLIR

---

sharktank/sharktank/ops/sharded_impls.py

For tensor parallelization (TP) > 1, this reduces buffer copies from (TP-1)*TP copies down to (TP-1)*2. Setup work for future improvements. On its own, it only results in minor speedups since all devices have to wait for the reduction result.

Reduce buffer copying by using one device to reduce and distribute

---

sharktank/tests/models/deepseek/test_deepseek.py
sharktank/tests/models/llama/kv_cache_test.py
sharktank/tests/models/llama/test_llama.py

Other tests are changing the default dtype causing flakes on RNG and KVache tests. Setting to `torch.float32` before initializing data guarantees correct type / value generation.

Fix llm model tests to set dtype

---

.github/workflows/ci-sharktank.yml
sharktank/sharktank/layers/mmdit.py
sharktank/sharktank/layers/testing.py
sharktank/sharktank/models/flux/export.py
sharktank/sharktank/models/flux/flux.py
sharktank/sharktank/models/flux/testing.py
sharktank/sharktank/utils/logging.py
sharktank/sharktank/utils/testing.py
sharktank/tests/evaluate/perplexity_iree_test.py
sharktank/tests/layers/mmdit_test.py
sharktank/tests/models/flux/flux_test.py

We don't have proper tests for a toy size variant of the model, which is desirable for CI tests on every commit.
Some of the tests fail during IREE buffer destruction. Which is a known issue.

[sharktank] Add toy size Flux transformer

---

docs/shortfin/llm/user/llama_serving.md

We missed a spot when we updated the `llama_serving` guide after enabling `prefill` and `decode` to export with different batch sizes

Update sharded export command

---

sharktank/sharktank/evaluate/perplexity_iree.py
sharktank/sharktank/utils/iree.py
sharktank/tests/layers/sharded_conv2d_with_iree_test.py
sharktank/tests/models/clip/clip_test.py
sharktank/tests/models/flux/flux_test.py
sharktank/tests/models/punet/sharded_resnet_block_with_iree_test.py
sharktank/tests/models/t5/t5_test.py
sharktank/tests/models/vae/vae_test.py
sharktank/tests/ops/ops_test.py

There are sporadic occasions where a buffer is destroyed after its corresponding IREE device is destroyed.
See https://github.com/nod-ai/shark-ai/issues/1050
Here is introduced a construct that utilizes function scope to ensures devices outlive local objects.

[sharktank] Ensure buffers are destroyed after devices

---

shortfin/src/shortfin/local/scheduler.cc

Number of timelines was fixed to one, bumped to 8 to support multiple fibers.

Bump semaphore count up

---

sharktank/sharktank/layers/rotary_embedding.py

Outer is missing lowerings in `torch-mlir` right now. To unblock we just explicitly do the unsqueeze and mul operators.

Replace `torch.aten.outer` with corresponding math

---

app_tests/integration_tests/llm/device_settings.py
shortfin/python/shortfin_apps/llm/components/batcher.py
shortfin/python/shortfin_apps/llm/components/generate.py
shortfin/python/shortfin_apps/llm/components/service.py

Prefill and decode should be batched separately as their preferred batch sizes for each piece of hardware.

Split prefill and decode batchers to separate implementations

---

shortfin/python/shortfin/interop/support/device_setup.py
shortfin/python/shortfin_apps/llm/cli.py
shortfin/python/shortfin_apps/llm/components/config_struct.py
shortfin/python/shortfin_apps/llm/components/lifecycle.py
shortfin/python/shortfin_apps/llm/components/manager.py
shortfin/python/shortfin_apps/utils.py
shortfin/src/shortfin/local/systems/amdgpu.cc
shortfin/src/shortfin/local/systems/amdgpu.h

For testing sharding it can be useful to test reusing the same device multiple times. By default this should be set to false but for testing it can be enabled so sharding can be run without multiple devices.

Group system args and add device reuse

---

shortfin/python/shortfin_apps/sd/server.py

Somehow this slipped by when merging RDNA4 changes -- we were defaulting to sdxl_config_i8.json if the path provided via CLI was not found, which was unintended. Now, if the path doesn't exist, we try to match against downloaded configs and error out if unsuccessful.

(shortfin-sd) Fix model config behavior in SDXL server.

---

.github/workflows/ci-sharktank.yml
sharktank/tests/models/t5/t5_test.py

Since https://github.com/nod-ai/shark-ai/issues/888 is fixed we can enable again the T5 tests.
Remove the testV1_1XxlBf16AgainstFluxGolden test. Other tests cover in a
better way.

[sharktank] Reenable T5 tests

---

sharktank/sharktank/models/vae/config.py
sharktank/sharktank/models/vae/model.py
sharktank/sharktank/models/vae/testing.py
sharktank/sharktank/models/vae/tools/diffuser_ref.py
sharktank/sharktank/models/vae/tools/run_vae.py
sharktank/sharktank/models/vae/tools/sample_data.py
sharktank/tests/models/vae/vae_test.py

Add eager and IREE tests for f32 and bf16.
The IREE test fails compilation for the particular model shape. See https://github.com/iree-org/iree/issues/20307

[sharktank] Add toy VAE tests

---

tuner/tuner/libtuner_test.py

The `iree_input` dialect has been removed from IREE according to PR: https://github.com/iree-org/iree/pull/20256, so we update our tuner code and prevent related errors during pytest runs.

[tuner] remove iree_input from the import list of dialects

---

docs/nightly_releases.md
docs/shortfin/llm/user/llama_serving.md

There are three documentation related fixes that were identified through QA testing:
- Specify `use-attention-mask` when running with a sharded model
- There's a special `--use-attention-mask` flag required to be able to run the sharded models. I had forgotten to add that flag to the sharded docs. This is what caused the compilation issue that Dhiraj had seen.
- Context from Rob:
- This is due to some affinity analysis and cloning work that still needs to be worked out. Its the main reason compilation work on iree presubmits. There are plans to get a proper fix in but it will be a while before someone can put hands on the issue.
- Removed deprecated `IREE` flag
- The `--iree-hal-target-backends=rocm` flag has been deprecated for `--iree-hal-target-device=hip`. Removed the old flag in …

Doc fixes for llm server 3.3 release

---

sharktank/sharktank/models/t5/export.py
sharktank/sharktank/pipelines/flux/README.md
sharktank/sharktank/pipelines/flux/export_components.py
sharktank/sharktank/pipelines/flux/export_from_hf.sh
sharktank/sharktank/pipelines/flux/export_parameters.py
sharktank/tests/models/t5/t5_test.py
shortfin/python/shortfin_apps/flux/components/builders.py

export_components.py and export_parameters.py had some artifact file
naming discrepancies.
Make T5 model exportable from Flux repo.
The T5 model needs to get loaded into the transformers.T5EncoderModel
before parameters can be exported.
There is a special function for that as the original parameters from
google/t5-v1_1-xxl are not in safetensors format. This is what the
original modeling work was based on.
It also populates some config options form the tokenizer like max
context length so that the MLIR model can get exported just from an
IRPA.

Fix exporting of Flux pipeline artifacts

---

requirements-iree-unpinned.txt
tuner/tuner/common.py
tuner/tuner/common_test.py

This PR adds the utility functions on the tuner side, which call the LinkTuningSpecsPass (`--iree-codegen-link-tuning-specs`) to merge the default td specs. 
Two helper functions are added:
-  `combine_tuning_specs`:  put two modules in one outer module using Python bindings.
- `link_tuning_specs`: invokes linking/merging pass (`--iree-codegen-link-tuning-specs`) to merge td_specs inside the module.
Issue: #810

[tuner] merge default td specs

---

shortfin/python/shortfin_apps/llm/cli.py
shortfin/python/shortfin_apps/llm/components/batcher.py
shortfin/python/shortfin_apps/llm/components/generate.py

Batching for LLM inference performed immediate dispatches on requests
before attempting to group. This meant that almost immediately things
were split into individual requests (instead of groups of requests).

Improving batching behavior for LLM inference

---

sharktank/sharktank/examples/pipeline/export_ppffn_net.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/pipeline_parallelized_test.py
sharktank/tests/types/tensors_test.py

- Remove .pinned parameter, requiring manually specifying devices and transferring between them with an inter-block callback function.
- Simplify .clone to stop it from transferring shards between devices.

Pipeline parallelism refactor

---

sharktank/sharktank/ops/sharded_impls.py

Avoid creating redundant barriers when the ReplicatedTensor has a single shard.

Special case for all_reduce for single 1 shard

---

sharktank/sharktank/build/__init__.py
sharktank/sharktank/build/actions.py
sharktank/sharktank/export.py
sharktank/sharktank/layers/__init__.py
sharktank/sharktank/layers/base.py
sharktank/sharktank/layers/configs/__init__.py
sharktank/sharktank/layers/configs/config.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/models/clip/clip.py
sharktank/sharktank/models/clip/export.py
sharktank/sharktank/models/clip/export_toy_text_model_iree_test_data.py
sharktank/sharktank/models/clip/testing.py
sharktank/sharktank/models/flux/export.py
sharktank/sharktank/testing/example_builder.py
sharktank/sharktank/types/gguf_interop/base.py
sharktank/sharktank/types/theta.py
sharktank/sharktank/utils/cli.py
sharktank/sharktank/utils/iree.py
sharktank/sharktank/utils/misc.py
sharktank/sharktank/utils/tree.py
sharktank/tests/layers/base_test.py
sharktank/tests/models/clip/clip_test.py

We don't have a standard way to configure, export and compile sharktank models.
Here is introduced such mechanism and for demonstration the CLIP text model is refactored to utilize this new approach.
`config.json`:
```
{
"model_type": "my_package.MyModel",
"mlir_path": "model.mlir",
"parameters_path": "model.irpa",
"iree_module_path": "model.vmfb",
"compile_args": ["--iree-hal-target-device=local"],
"export_functions": [
{
"function": "forward",
"batch_sizes": [1, 2, 3]
}
]
"my_model_arg": 5,
}
```
usage
```
model = create_model("config.json")
model.export()
model.compile()
```

[sharktank] Add common model config, export and compile

---

sharktank/sharktank/models/t5/t5.py

Fix for test failure
```
FAILED sharktank/tests/models/t5/t5_test.py::T5EncoderIreeTest::testCompareToyIreeVsEager_1
AttributeError: property 'config' of 'T5Encoder' object has no setter
```
See https://github.com/nod-ai/shark-ai/actions/runs/14096001030/job/39483353268

[sharktank] Fix T5 init of config parameters

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/tests/ops/pipeline_parallelized_test.py

Follow up to https://github.com/nod-ai/shark-ai/pull/1149
- Add pipeline parallelism support to reshard_split and re-enable CatTest
- Fix an issue with func_wrapper exposed by reshard_split usage.

Further pipeline parallelism support sharded functions

---

sharktank/sharktank/types/tensors.py
sharktank/tests/export_test.py
sharktank/tests/ops/sharded_test.py

SplitTensors should only be used for sharding across multiple devices.
This PR adds asserts to their `__init__` to ensure they are constructed with at least 2 shards.

Limit SplitTensors to >1 shards

---

sharktank/sharktank/types/tensors.py
sharktank/tests/ops/pipeline_parallelized_test.py

- Change how defaults are loaded into kwargs by .clone() so that incorrectly specified kwargs will error out.
- Previously it silently used defaults and not the specified values. E.g. if you provided `shards=...` instead of `ts=...` it would use the tensor's existing shards rather than error out.
- Added tests to verify this behaviour

Change ShardedTensor.clone to error out on wrong args

---

.github/workflows/ci-sharktank-nightly.yml
.github/workflows/ci-sharktank.yml
sharktank/sharktank/models/vae/testing.py
sharktank/tests/models/vae/vae_test.py

Change toy-size model config to circumvent compiler error for HIP. CPU still fails in another way.

[sharktank] Move expensive VAE tests to nightly

---

sharktank/sharktank/export.py
sharktank/sharktank/layers/base.py
sharktank/sharktank/layers/configs/config.py
sharktank/sharktank/models/flux/__init__.py
sharktank/sharktank/models/flux/compile.py
sharktank/sharktank/models/flux/export.py
sharktank/sharktank/models/flux/flux.py
sharktank/sharktank/tools/import_hf_dataset.py
sharktank/sharktank/utils/hf.py
sharktank/tests/models/flux/flux_test.py

With the goal of unifying model export and compile under one interface, here the Flux transformer refactored.
Add model config preset registry.

[sharktank] Refactor Flux transformer export and compile to use the common ModelConfig

---

sharktank/sharktank/utils/testing.py
sharktank/tests/models/clip/clip_test.py
sharktank/tests/models/t5/t5_test.py

The test prompts in sharktank.utils.testing got initialized on every import of the module, which caused excessive downloading/checking of Hugging Face site for the prompt dataset.
Now they get initialized only when used.

[sharktank] Make common test prompts initialize lazily to avoid spamming the HF server

---

shortfin/python/shortfin_apps/llm/cli.py
shortfin/python/shortfin_apps/llm/components/batcher.py
shortfin/python/shortfin_apps/llm/components/generate.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/__init__.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/base_token_selection_strategy.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/greedy_token_selection_strategy.py
shortfin/python/shortfin_apps/utils.py
shortfin/tests/apps/llm/components/token_selection_strategy/greedy_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/multi_greedy_token_selection_strategy_test.py
shortfin/tests/apps/llm/components/token_selection_strategy/token_selection_strategy_test.py

With decode the majority of future steps are known a groupable. Created a basic reservation system so that steps can be reserved and the continuous batcher knows that a future groupable request is coming.
This should be adapted to include grouping multiple responses, and having a "grouping" exist. E.g. multiple parallel requests in flight and grouped together for the multiple hypothesis case.

Rework batcher for a reservation system

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/tests/ops/sharded_test.py

Current behaviour of ops.split for SplitPrimitiveTensor is not consistent with either torch.split nor with its own documentation.
See the added tests, specifically `testExpandSplitAlongSplit` should error since it's splitting along `shard_dim`, but it does not error out. Instead it silently does nothing.
This change attempts to 'fix' the behaviour to be in line with torch.split (i.e. not allow splitting along a non-singular dimension) and with its own doc (i.e. don't allow expanding along the `shard_dim`).

Expand_split fix

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/examples/pipeline/export_ppffn_net.py
sharktank/sharktank/examples/sharding/export_ffn_net.py

These scripts, especially `export_paged_llm_v1` can take several minutes to complete, and to have to have it fail right at the end because of an incorrectly specified path is a bad user experience.

Check output paths before performing computation

---

tuner/examples/simple/simple_tuner.py
tuner/tuner/candidate_gen.py
tuner/tuner/candidate_gen_test.py
tuner/tuner/common.py
tuner/tuner/common_test.py
tuner/tuner/libtuner.py

This PR adds implementation for providing a starter td spec, enabling incremental merging of tuning specs when tuning across different dispatches in a real model. 
Testing has been done from my end and verified that it works by supplying td specs that include matchers for attention ops or identical matmul ops, demonstrating that merging behaves correctly based on matcher overlap.
Issue: #810

[tuner] add the option of providing starter td spec

---

sharktank/sharktank/models/flux/export.py
sharktank/sharktank/models/flux/flux.py
sharktank/tests/models/flux/flux_test.py

We do not import with a shartank dataset name anymore. The repo_id needs to be an actual repo_id in Hugging Face.

[sharktank] Fix nightly Flux transformer tests wrong HF repo id

---

sharktank/sharktank/examples/export_paged_llm_v1.py
shortfin/python/shortfin_apps/llm/components/config_struct.py

For some searches (sampling, beamsearch) it is beneficial to return either the softmax or log softmax of the values.

Export with log-softmax and softmax of logits

---

sharktank/sharktank/layers/base.py
sharktank/sharktank/layers/configs/config.py
sharktank/sharktank/models/__init__.py
sharktank/sharktank/models/dummy/__init__.py
sharktank/sharktank/models/dummy/dummy.py
sharktank/sharktank/tools/trace_model_with_tracy.py
sharktank/sharktank/utils/io.py
sharktank/sharktank/utils/iree.py
sharktank/tests/utils/iree_test.py

Add functions for more convenient tracing of models.
E.g.
```
model = ...
model.export()
model.compile()
trace_model_with_tracy(model.config, function="forward_bs1")
```
```
def my_fn():
...
trace_with_tracy(my_fn, output_trace_path="capture.tracy")
```
Add a dummy model to the registry to server for testing.

[sharktank] Add Tracy utils

---

sharktank/conftest.py
sharktank/sharktank/export.py
sharktank/sharktank/utils/iree.py
sharktank/sharktank/utils/testing.py
sharktank/tests/models/llama/sharded_llama_test.py

Check cosine similarity for the logits and the cache state instead of element-wise comparison.
Make the test respect IREE target test args, allowing it to run not just on CPU.
Make the test CLI accept multiple IREE devices.
Refactor get_iree_devices to accept multiple devices and to allow for repeating devices even when not using "local-task". It will repeat the devices to get to the desired device count. This is useful when you want a test to run on a machine with fewer devices than required.
Allow for specifying device_count even when specifying a list of devices.

[sharktank] Fix and enable sharded toy llama IREE test

---

sharktank/tests/models/llama/benchmark_amdgpu_test.py

`pytest sharktank/tests/models/llama/benchmark_amdgpu_test.py -v -s --iree-hip-target=gfx942 --iree-device=hip://4 -k testBenchmark8B_fp8_attnf8_TP1_Non_Decomposed_Input_Len_128`

Add llama3 fp8 attnf8 sharktank benchmark test

---

sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/sharded_test.py

The previous meaning was not precise and diverged from that of torch:
Compares 2 tensors for equality, such that if one is substituted with the other in sharktank polymorphic calls, the results will be essentially the same. Meaning, they would also compare equal.
We should try to not change the meaning of ops compared to torch. Now the meaning is the same as in torch. They are equal if their dtypes is equal and their elements.
For that we utilize unboxing.
Add parameter to is_deep_equal to not require name equality.

[sharktank] Align the meaning of ops.equal to that of torch.equal

---

sharktank/sharktank/layers/configs/config.py
sharktank/sharktank/models/dummy/dummy.py
sharktank/sharktank/models/flux/export.py
sharktank/sharktank/models/flux/flux.py
sharktank/tests/models/flux/flux_test.py

Add debug and release presets for the model.
Tracing requires some debug info to be inserted into the module.

[sharktank] Add Tracy tracing to Flux transformer artifact exporting

---

tuner/tuner/candidate_gen.py
tuner/tuner/libtuner.py

This PR moves the linking phase, which links the starter transform td spec with candidate specs, to the candidate compilation phase. Since candidate compilation is multithreaded, this change reduces the linking overhead.
Below are the overhead results I observed (the time unit is seconds):
| Number of candidates| Candidate generation  + link       | Candidate compilation  | Total  |
|------------------------|-------------------------------|--------------------|------------ |
|              50                 |        4.85                              |    13.78                 |    18.63      |
|              100               |        5.31                              |    16.31                 |    21.62      |
After deferring the link phase from candidate generation to the compilation …

[tuner] deferring the link phase to multi-threaded compilation phase

---

sharktank/sharktank/utils/export_artifacts.py
sharktank/tests/models/llama/benchmark_amdgpu_test.py

- Fix decode input size.
- Fix attention-kernel sharktank missing in ExportArtifacts utils, this bug make benchmark sharktank flag never set, always use torch kernel.
- Increase the benchmark run time from 3 to 10.

Fix llama3 attnf8 2048 decode input size

---

tuner/tuner/libtuner.py

No need to enumerate as only one worker is there. 
Moved worker_id from out of loop and kept it as 0.

[tuner] Fix review comment from PR: #1265

---

tuner/tuner/dispatch_parser.py
tuner/tuner/dispatch_parser_test.py

Per suggestion from this comment https://github.com/nod-ai/shark-ai/pull/1264#discussion_r2045210709, this PR mainly removes the todo comment and adds tests for named ops.

[tuner] add tests for named ops

---

.github/workflows/ci-llama-large-tests.yaml
sharktank/tests/models/llama/benchmark_amdgpu_test.py

- Fix issue in 0418 llama nightly benchmark test https://github.com/nod-ai/shark-ai/actions/runs/14534130397/job/40779266661#step:7:1036 bring from https://github.com/nod-ai/shark-ai/pull/1172#pullrequestreview-2780139231
- Xfail llama70B codegen issue in 0419 llama70b nightly benchmark test https://github.com/nod-ai/shark-ai/actions/runs/14548496681/job/40816909348#step:7:386534

Fix export_atifcats usage in benchmark test

---

sharktank/sharktank/export_layer/export_kv_cache.py
sharktank/sharktank/layers/paged_attention.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/utils/create_cache.py
sharktank/tests/layers/kv_cache_test.py
sharktank/tests/layers/paged_llama_attention_block_test.py
sharktank/tests/layers/sharded_paged_kv_cache_test.py
sharktank/tests/layers/sharded_paged_llama_attention_block.py
sharktank/tests/models/llama/attention_test.py

Fixes bug in refactor (https://github.com/nod-ai/shark-ai/pull/1098) that removed specifying different dtypes for cache vs attention.

[sharktank] Fix attention dtype

---

tuner/tuner/dispatch_parser.py

As https://github.com/llvm/llvm-project/pull/136054 is landed, the Python binding for `linalgOp.getIndexingMaps` can be used for tuner according to the comment https://github.com/nod-ai/shark-ai/pull/1264#discussion_r2045261109.

[tuner] use python binding to get indexing maps for root op

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/examples/paged_llm_v1.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/layers/paged_attention.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/layers/rotary_embedding.py
sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/types/pipelining.py
sharktank/sharktank/utils/cli.py
sharktank/sharktank/utils/create_cache.py
sharktank/sharktank/utils/load_llm.py
sharktank/tests/layers/pipelined_paged_attention_test.py
sharktank/tests/layers/pipelined_sharded_paged_attention_test.py
sharktank/tests/layers/sharded_paged_llama_attention_block.py
sharktank/tests/models/grok/test_grok.py
sharktank/tests/models/llama/sharded_llama_test.py
sharktank/tests/models/llama/test_llama.py

Requires #1237, developed together, split up to make reviewing easier. They **must** be merged together as both PRs change interfaces for models and the KVCache (PagedAttention).
Parallelism is implemented with an inter-layer callback which checks if transfers are required and performs them there.
Model weights are not changed or tagged when written out, instead they are modified in-place before tracing is performed by `pipeline_parallelize_theta`.
Decode for PP>1 currently does not work, blocked by https://github.com/iree-org/iree/issues/20551

Pipeline Parallellism for LLama

---

tuner/tuner/candidate_gen.py
tuner/tuner/dispatch_parser.py
tuner/tuner/dispatch_parser_test.py

This PR mainly gets the function name from the func.func, which contains the root op in the input module.
Issue: https://github.com/nod-ai/shark-ai/issues/1303

[tuner] get the function name from the func.func in the input module

---

sharktank/sharktank/ops/default_impls.py

Old argument names used after refactor, introduced in #262.

Fix bug in einsum_2args

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/tests/ops/sharded_test.py

Only strange thing about this op that I haven't seen in others is that doing the mean across the `shard_dim` requires us to return a `ReplicatedTensor` rather than a `SplitPrimitiveTensor`, especially when `keepdim == False` since the `shard_dim` stops existing.

Add ops.mean for SplitPrimitiveTensor

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/tests/ops/sharded_test.py

**Changes/Fixes**
- `split_elementwise_binary` was using incorrect shard_dim because of a typo.
- `reshard_like_replicated_to_split` did not correctly work for broadcastable tensors of different dimensions.
- Test coverage

Fix for elementwise binary with broadcasting

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/tests/ops/sharded_test.py

Implement a more general version of ops.view for SplitPrimitiveTensor that supports more than one dim being expanded or collapsed, along with a lot of test of the functionality.
Needed for deepseek.

Change ops.view to support multiple dim expansions and collapses

---

sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/sharded_test.py

- Extend to ShardedTensors
- Fix bug in trampoline (wrong variable used for `find_overrides`)
- Updated pipeline parallelism `func_wrapper` to support multiple returns

ops.topk enhancements

---

sharktank/sharktank/ops/_registry.py
sharktank/sharktank/ops/custom_impls.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/sharded_test.py

Implementing this will clobber the builtin ops function within the ops namespace and anywhere we do `from sharktank.ops import *`.

Implement ops.sum

---

sharktank/tests/ops/sharded_test.py

- Certain passing tests didn't have required asserts in them.
- `testSoftmaxSplit` was not coded correctly.

Minor fixes to tests

---

sharktuner/model_tuner/README.md

Fixing typo introduced in 999826588a17a04d569046039ca8ea3394cbac4d.

[model_tuner] Fixing model tuner trial run arguments

---

sharktuner/model_tuner/model_tuner.py

`model_tuner` now outputs the spec file for the best configuration, with the path configurable using `--output-td-spec`.
This is adapted from changes in https://github.com/Max191/shark-ai/commit/6de0af4971ed1daa016dcbe047a9f4069ef52a73

[model_tuner] Add output of best spec file.

---

sharktuner/sharktuner/common.py
sharktuner/sharktuner/dispatch_constraints.py
sharktuner/sharktuner/dispatch_constraints_test.py

Motivated by bug reported from this [input](https://gist.github.com/rkayaith/0c537b5b917488a890273f7d886791c7) 
**Problem:**
In the current tuner, tile sizes are required to both evenly divide the problem size and be multiples of the intrinsic size. When the problem size is not a multiple of the intrinsic size, the solver fails to find any valid solutions.
**Solution:**
The simplest fix is to round the problem size up to the nearest multiple of the intrinsic size when generating constraints, and then account for the necessary padding in the lowering configuration.
This PR introduces two main changes from Max's local experimental tuning branch into the main tuner branch:
- Change 1: modify the constraint generation to support unaligned problem shapes.
- Change 2: add padding information to …

[tuner] padding support along TileAndFuse pipeline

---

sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/sharded_test.py

`scatter_split_split` has a naive implementation and a more efficient version may be possible.

Ops.zero_like and ops.scatter_

---

docs/nightly_releases.md
sharktuner/README.md
sharktuner/model_tuner/README.md

Update `shark-ai/docs/nightly_releases.md` doc after adding sharktuner to nightly releases and various other nits.

[docs] Update documentation after adding sharktuner nightly releases

---

sharktank/sharktank/kernels/mlir_kernel.py
sharktank/tests/kernels/mlir_kernel_test.py

This patch adds the @mlir_kernel decorator and surrounding infrastructure, the idea of this decorator is to automatically generate custom ops for a simplified input spec, allowing developers to write inline mlir in sharktank models.

Add mlir_kernel for inline mlir kernels

---

shark-ai/pyproject.toml
sharktank/pyproject.toml
sharktuner/pyproject.toml
shortfin/pyproject.toml

This addresses the following warning:
* `project.license`:
```
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
```
* `classifiers`
```
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: Apache Software License
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
```

Update project license and drop classifer

---

.github/workflows/ci_linux_x64_nogil-libshortfin.yml

Starting with v5.5.0 the python-setup actions supports free-threaded Python. Switching over also eases to merge the workflow with `ci-libshortfin.yml` which could follow later.

Switch to `actions/python-setup`

---

.github/workflows/ci-sharktank.yml
docs/shortfin/llm/user/llama_serving.md
pytorch-cpu-requirements.txt
pytorch-rocm-requirements.txt

Torch 2.3 is more than an year old and we don't want to support it. On several occasions it caused problems during model tracing.
Next steps are to support Torch 2.6 and 2.7.
Then we can drop support for 2.4.

Drop support for torch 2.3

---

sharktank/sharktank/export_layer/export_paged_attention.py
sharktank/sharktank/layers/paged_attention.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/tests/layers/kv_cache_test.py
sharktank/tests/layers/pipelined_paged_attention_test.py
sharktank/tests/layers/pipelined_sharded_paged_attention_test.py
sharktank/tests/layers/sharded_paged_kv_cache_test.py

There is no good benefit to use `seq_len` to select a subset from the KV cache reading function. If the user wants a subset it is better to post slice (as thats effectively teh result otherwise).

Remove seq_len parameter from kv cache

---

sharktank/sharktank/evaluate/perplexity_iree.py
sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/layers/paged_attention.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/types/pipelining.py
sharktank/sharktank/utils/create_cache.py
sharktank/tests/layers/pipelined_paged_attention_test.py
sharktank/tests/layers/pipelined_sharded_paged_attention_test.py

Pipeline parallelism had issues with transformer block offset. Updated and cleaned up the block / device mappings to instead use two separate mappings. This allows a cleaner implementation that relies less on replicated behavior.
Included an `unshard` operation for the KV cache as the existing tests replicated the reconstruction which should be part of PagedAttention.

Refactor pipeline parallelism work and fix block offset

---

sharktank/sharktank/ops/__init__.py
sharktank/sharktank/ops/_registry.py
sharktank/sharktank/ops/custom_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/ops/utils.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/utils/tree.py
sharktank/tests/ops/pipeline_parallelized_test.py
sharktank/tests/ops/sharded_test.py
sharktank/tests/utils/tree_test.py

The majority of operations have essentially the same replication mechanism across device. We call the underlying unsharded op with the corresponding shards and then construct a replicated tensor form the resulting shards.
This change solves this in general way to not have to write the same replication pattern for all ops.

[sharktank] General implementation for trivially replicable ops

---

sharktank/sharktank/layers/ffn_moe_block.py
sharktank/sharktank/layers/mixture_of_experts_block.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/sharding.py
sharktank/sharktank/types/tensors.py
sharktank/tests/layers/mixture_of_experts_block_test.py
sharktank/tests/ops/ops_test.py
sharktank/tests/ops/sharded_test.py

Add support for expert-prallel dense mixture of experts block.
This change includes adding support for matmul where the RHS is a 3D tensor split on the batch dimension. This drives some changes like using `.mT` instead of `.T` when `transpose_b=True`.
Made `scatter_` work with non-number source arguments.
Fixed dispatching to trivially replicable to handle if some dispatch args are not tensors, but all tensor args are replicated.

[sharktank] Tensor-parallel MoE block

---

sharktank/sharktank/evaluate/perplexity_iree.py
sharktank/tests/evaluate/perplexity_iree_test.py

- Fixed check on `--tensor-parallelism-size` to ensure that dataset and cli flag agree to avoid hard to debug error messages.
- Re-enable xfailed PPL test
Closes #1306.

Perplexity test for pipeline parallelized Llama 8B

---

sharktank/sharktank/examples/export_paged_llm_v1.py

Without this PR, TP models cannot be compiled because argument affinity is wrong. E.g.
**Expected**
`func.func @prefill_bs1(%arg0: !torch.vtensor<[1,?],si64> {iree.abi.affinity = #hal.device.promise<@__device_0>}`
**Actual**
`func.func @prefill_bs1(%arg0: !torch.vtensor<[1,?],si64> {iree.abi.affinity = #hal.device.promise<@__device_(0, 1)>}`
I think we need some sort of CI test that runs of PRs to export and compile a tiny model with TP and PP in order to catch these kinds of issues.

Fixed missing index

---

sharktuner/sharktuner/candidate_gen.py
sharktuner/sharktuner/common.py
sharktuner/sharktuner/dispatch_constraints.py
sharktuner/sharktuner/dispatch_parser.py
sharktuner/tests/dispatch_constraints_test.py
sharktuner/tests/dispatch_parser_test.py

This improves support for convolutions in the tuner by:
- generalizing `ConvolutionOpInterfaceParser` to support parsing `linalg.generic` ops, as well as additional layouts. However since constraint generation for more layouts is untested, only `nhwc_hwcf` and the generic equivalent are considered valid.
- supporting generating the padding lowering attribute for convolutions

[tuner] Improve support for convolutions

---

requirements-iree-pinned.txt
shortfin/CMakeLists.txt
shortfin/python/shortfin_apps/llm/components/config_struct.py
shortfin/python/shortfin_apps/llm/components/lifecycle.py
shortfin/python/shortfin_apps/llm/components/manager.py
shortfin/python/shortfin_apps/utils.py
shortfin/src/shortfin/local/systems/amdgpu.cc

This allows us to enable or disable the [async_caching flag](https://github.com/iree-org/iree/commit/03f2a52413d482ccb8598bc0c90e8f79e7adceb0) in Shortfin, that was recently added @AWoloszyn.
This fixes the issue or of allocating and not releasing progressively higher values of RAM, as observed in some long running benchmark tests.
Our CLI defaults this value to `false`. It can enabled by passing in `--amdgpu_async_caching` when starting the server

IREE Bump to `3.5.0rc20250509` + Disable/Enable async_caching in Shortfin

---

sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py
sharktank/tests/ops/sharded_test.py

Adds reduce_scatter for an UnreducedTensor, which would be required for tensor-sharding the latent attention preprocessing.
A Split op is also added as it is used in the implementation of reduce_scatter.
The sharded_sum op is augmented with a new root_rank argument. It specifies the rank of the destination device within the sharded tensor. It has the same meaning as in MPI.

[sharktank] Add reduce_scatter and split ops

---

app_tests/integration_tests/llm/shortfin/direct_to_batcher_test.py
shortfin/python/shortfin_apps/llm/cli.py
shortfin/python/shortfin_apps/llm/components/batcher.py
shortfin/python/shortfin_apps/llm/components/generate.py
shortfin/python/shortfin_apps/llm/components/service.py
shortfin/python/shortfin_apps/llm/routes/generate.py

Threading pool actually slowed existing throughput if enabling multiple threads on decode. Simplified to have separate threads between prefill and decode. This should allow pre-work to decouple streams between the two workloads.

Restore separate threads for prefill and decode

---

shortfin/python/shortfin_apps/llm/components/token_selection_strategy/sampler.py

Using numpy.argpartition results in speedup of select_top_k when compared to sfnp.

Use numpy.argpartition instead of sfnp for select_top_k

---

sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/tests/ops/sharded_test.py

Fixes #1396
Implementation of sharded_gather ops
this op is not an override for torch.gather which works based on indexing. It focuses on gathering SplitPrimitiveTensor and ReplicatedTensor shards across devices into a single device.

[shark Tank] Implementation of sharded_gather

---

sharktank/sharktank/models/clip/export_toy_text_model_iree_test_data.py
sharktank/sharktank/models/punet/export_sharded_toy_resnet_block_iree_test_data.py
sharktank/sharktank/models/punet/testing.py
sharktank/tests/models/punet/resnet_test.py
sharktank/tests/models/punet/sharded_resnet_block_with_iree_test.py
sharktank/tests/models/punet/up_down_block_test.py

Export test data to add a test in the IREE test suite.
Refactor the test in sharktank to utilize the shared export function. Make the test not xfail due to numerical precision as the error is around 1e-5 for f32 which should be good enough.
2 other tests required adjusting the numerical tolerance due to a change in random theta generation such that it does not generate in range [0, 1], but in range [-1, 1].

[sharktank] Add exporting of sharded toy sized Resnet block IREE test data

---

sharktank/pyproject.toml
sharktank/requirements.txt
sharktank/sharktank/layers/base.py
sharktank/sharktank/layers/configs/config.py
sharktank/sharktank/tools/sharktank.py
sharktank/tests/tools/sharktank_test.py

To have a convenient generation of model artifacts we would benefit from a CLI tool. The tool here could be used for model, export, compile, tracy_trace. E.g.
```
sharktank list
```
```
sharktank export some-model-config-preset-name
sharktank compile some-model-config-preset-name
```
```
sharktank export /path/to/model/config.json
```

[sharktank] Add CLI tool for operations on models

---

shortfin/python/shortfin_apps/llm/components/batcher.py

`await device0` is extremely expensive so all transfers should be enqueued then awaited on. Doing one big wait will substantially prevent stalling.

Decrease numy of `await device` in Batcher

---

sharktank/tests/tools/sharktank_test.py

Trying to run test locally raises an error:
```
def test_export_compile(dummy_model_path: Path):
with chdir(dummy_model_path):
check_call(["shark", "model", "export", "dummy-model-local-llvm-cpu"])
check_call(["shark", "model", "compile", "dummy-model-local-llvm-cpu"])
>           from .. import models
E           ImportError: attempted relative import with no known parent package
tests/tools/sharktank_test.py:32: ImportError
```
That line also does not appear to be needed as `register_all_models()` right below it does the same thing.

Fix relative import

---

sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/types/tensors.py

Adds an assert and useful error message when trying to shard a tensor into more pieces than possible. E.g. tensor of shape [4, 32] into 8 pieces along dim 0 is impossible. Previously, this would return back 1 shard and then fail on a subsequent assert since `len(ts) != shard_count`, which is correct but harder to trace back to actual issue.

Provide useful error message for invalid sharding

---

sharktank/sharktank/tools/dump_gguf.py

- Fix crash when run without `--save-input-output-blocks` flag
- Decrease verbosity in output
- Add TODO for unsupported tensor types

Bug fix in dump_gguf

---

sharktank/sharktank/layers/paged_attention.py

The KV Cache should have contracting dimensions placed together. Specifically the block sequence stride should be after the KV heads but before the attn_dim.

Reorder KV Cache contraction dimensions

---

shortfin/python/shortfin_apps/llm/components/batcher.py

Copying memory is cheap, it is better to copy the entire decode result then slice the appropriate subsections for CPU analysis. This also avoids doing multiple synchronizations.

Copy all device memory then slice / select

---

sharktank/sharktank/layers/paged_attention.py

Causing current failure of nightly Torch Perplexity.

Fixed missing device param in KVCache

---

shortfin/python/shortfin_apps/llm/components/fiber_pool.py
shortfin/python/shortfin_apps/llm/components/generate.py

The function `FiberPool.return_fiber()` incorrectly pushed the returned fiber into the fibers list, which could make its size grow unintentionally.
This patch removes the extra appends and cleans up the usage of the function in other files.

[shortfin] Fix extra fiber appends in FiberPool.return_fiber

---

sharktank/sharktank/tools/compare_safetensors.py
sharktank/sharktank/utils/patching.py

Also add support for handling of all our tensor types in the module patcher through unboxing.

[sharktank] Fix module patching and safetensors comparison tool

---

sharktank/sharktank/examples/sharding/shard_llm_dataset.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/types/theta.py
sharktank/tests/layers/configs_test.py

We don't record the full range of config options when saving models. This makes available the whole config.

[sharktank] add to/form properties methods in LlamaModelConfig

---

sharktank/sharktank/utils/testing.py
sharktank/tests/utils/testing_test.py

This wraps the pytest.mark.xfail decorator into a new decorator. pytest.mark.xfail does not support matching on the error message, but sometimes we need to be more precise on why we expect a failure. One example is when specifying what compiler error is expected. Just the exception type is not enough.
```
@xfail(raises=MyError, strict=True, match="my message")
@test_something():
raise MyError("my message")
```

[sharktank] xfail with support for regex matching in the error message

---

sharktank/sharktank/utils/iree.py
sharktank/sharktank/utils/testing.py
sharktank/tests/models/flux/flux_test.py
sharktank/tests/models/llama/sharded_llama_test.py
sharktank/tests/models/t5/t5_test.py
sharktank/tests/models/vae/vae_test.py

Rename to get_iree_compiler_flags_from_object for a more descriptive name.

[sharktank] move and rename get_iree_compiler_flags

---

sharktank/sharktank/layers/rotary_embedding.py
sharktank/tests/models/llama/attention_test.py

This reverts commit 6f3f3504d5e4a3e1c259d899316979e867516c4f.
We were seeing an issue in the Shortfin server, while running mistral and tracked it down to a regression in accuracy. Bisecting led to this commit as being the culprit.
Initially, this presented itself as a numpy NaN error in the server:
```bash
/shark-ai/shortfin/src/shortfin/support/iree_helpers.h:315: UNKNOWN; Unhandled exception: Traceback (most recent call last):
File "numpy/random/mtrand.pyx", line 990, in numpy.random.mtrand.RandomState.choice
RuntimeError: Async exception on <Worker 'default-fiber-pool-init-worker-0'>): probabilities contain NaN
```
Was able to track this down to being caused by NaNs in the logits, directly after decode invocation. Those NaNs eventually get passed to the `Sampler.sample_top_p` …

Revert "[RoPE] Cleanup RoPE implementation (#1514)"

---

sharktank/sharktank/layers/causal_llm.py

Current implementation does not respect dtype argument and always returns a float type.

Fix _maximally_negative_value to return correct datatype

---

sharktuner/model_tuner/model_tuner.py
sharktuner/sharktuner/candidate_gen.py
sharktuner/sharktuner/common.py
sharktuner/sharktuner/constraint_generator.py
sharktuner/sharktuner/dispatch_constraints.py
sharktuner/sharktuner/dispatch_parser.py
sharktuner/sharktuner/libtuner.py
sharktuner/sharktuner/merge_td_specs.py
sharktuner/tests/candidate_gen_test.py
sharktuner/tests/common_test.py
sharktuner/tests/constraint_generator_test.py
sharktuner/tests/dispatch_constraints_test.py
sharktuner/tests/dispatch_parser_test.py

This PR creates interface for constrain generation and retire the data class `ProblemSize` fully. More details can be found in #1442.

[tuner]  create interface for constraint generation

---

sharktank/sharktank/kernels/__init__.py
sharktank/sharktank/kernels/templates/topk_dynamic.mlir
sharktank/sharktank/kernels/topk.py
sharktank/sharktank/ops/default_impls.py
sharktank/tests/kernels/topk_test.py
sharktank/tests/ops/ops_test.py

For greater topk we can directly emit a `iree_linalg_ext.topk` operator then rely on codegen for generating the kernel. This avoids having torch accidentally emit `torch.sort` and `torch.slice`.

Hookup `topk` to `iree_linalg_ext.topk`

---

sharktank/tests/kernels/rotary_test.py

Rotary.py was not running as part of the kernels presubmits due to an incorrect name. Corrected the name and signature for rotary development testing.

Re-enable and fix rotary.py

---

sharktank/sharktank/evaluate/perplexity_iree.py
sharktank/sharktank/evaluate/perplexity_torch.py
sharktank/sharktank/utils/evaluate.py

Logits need to be padded to keep them the same length as token_ids since we don't start with token_ids[:, 0], we instead prefil will a range of tokens to give better context to the model.
Previously the logits were right padded based on the difference between in length between their size and that of token_ids. This causes token_ids[:, i] and logits[:, i] to no longer line up requiring special indexing further down.
This PR cleans up that padding approach to make the indexing consistent.

Change perplexity logit padding to align logits with tokens

---

sharktank/sharktank/ops/sharded_impls.py

There was a torch export dynamic shapes constraint violation problem with `ops.trace_tensor`. It was called on a unsharded tensor, which caused us to loop over dimension 0 of the tensor in `sharded_wrap_override.transfer_n_pin.func_wrapper`. This caused torch tracing to introduce unwanted constraints on the dynamic dims.
In any case we don't want `unshard` and `trace_tensor` to be wrapped by the verifier. `unshard` is a single tensor arg op and it is a transferring op. `trace_tensor` is a an op with tensor args that can be sharded differently.
There is the question of whether we should allow mixing of unsharded and sharded tensors args in an op. But that should be a concern of the underlying op, not the wrapper.

[sharktank] Allow for non-sharded tensor args in device verification wrapper and exclude some ops

---

sharktank/sharktank/utils/debugging.py
sharktank/sharktank/utils/patching.py
sharktank/tests/utils/patching_test.py

This can be used to trace tensors both in eager and during execution with IREE. Usually it allows to get adequate tracing density when models are decomposed into multiple nested torch modules.

[sharktank] Add module patcher that uses ops.trace_tensor

---

sharktank/hip_kernels/CMakeLists.txt

Modifies the kernel compilation to use shortfin generated iree build artifacts
- After building the editable installs of shortfin, 
```bash
mkdir -p sharktank/hip_kernels/build && cd sharktank/hip_kernels/build && cmake ..
make -j 20
```

Tweak kernel compilation

---

sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/utils/create_cache.py

Currently `create_paged_kv_cache` creates all kv_caches with the same attn_type (gqa) since it relies on the default.
`attn_type_map` should probably be refactored out to a central place so we don't have multiple of them sitting around, that or placed into `LlamaModelConfig`.

Pass correct attn_type from create_paged_kv_cache

---

sharktank/tests/models/llama/benchmark_amdgpu_test.py

Quick fix from https://github.com/nod-ai/shark-ai/pull/1612 to bring the nightly llama test back to normal.
Issue from iree-compile https://github.com/iree-org/iree/issues/21068
Temp fix is to add --iree-stream-affinity-solver-max-iterations=1024 in iree-compile.

Add --iree-stream-affinity-solver-max-iterations=1024 for llama compile

---

sharktank/hip_kernels/kernels/topk_fp16_ukernel.c
sharktank/hip_kernels/kernels/topk_fp32_ukernel.c

When doing reductions across long sequence lengths its possible to exceed a 2 GB intermediate buffer. These cases need ensure pointer arithmetic occurs in 32-bits or it will incorrectly offset.

Fix topk kernel for large cases

---

sharktank/sharktank/utils/testing.py
sharktank/tests/utils/testing_test.py

If the `xfail` condition is `False` we should not xfail on a failed exception message match.
Use `pytest.Pytester` to isolate xfailed tests and be able to test results themselves.

[sharktank] Make our xfail hanlde condition and refcator its testing

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/utils/cli.py
shortfin/python/shortfin_apps/llm/components/batcher.py

Prefill logits often only require the final logits for performing the first decode step. By optionally returning only the final logits we can minimize data transfer and reduce compute on earlier stages of the pipeline.

Support returning only the final logits from prefill

---

sharktuner/sharktuner/candidate_gen.py
sharktuner/sharktuner/common.py
sharktuner/sharktuner/constraint_generator.py
sharktuner/sharktuner/spec_builder.py
sharktuner/tests/candidate_gen_test.py
sharktuner/tests/constraint_generator_test.py
sharktuner/tests/spec_builder_test.py

This PR mainly about using config list ( replace `Iterator[iree_codegen.CompilationInfoAttr]` with `Iterator[list[tuple[str, ir.Attribute]]]`  ) for constraint generators per comments in https://github.com/nod-ai/shark-ai/pull/1602#discussion_r2138003453. All relevant tests have been updated accordingly.

[tuner] use config list for constraint generators

---

sharktank/sharktank/models/dummy/dummy.py

Fixes https://github.com/nod-ai/shark-ai/issues/1660.
The dummy model does not require to import the testing utils at the top of the file. The imports can be push into the concrete functions that use them.

[sharktank] Fix package having unwanted dependency on pytest

---

sharktank/sharktank/export_layer/export_moe.py
sharktank/sharktank/layers/testing.py
sharktank/sharktank/models/deepseek/testing.py
sharktank/sharktank/models/dummy/dummy.py
sharktank/sharktank/models/flux/flux.py
sharktank/sharktank/models/flux/testing.py
sharktank/sharktank/models/grok/testing.py
sharktank/sharktank/models/llama/testing.py
sharktank/sharktank/models/punet/testing.py
sharktank/sharktank/testing/example_builder.py
sharktank/sharktank/utils/random.py
sharktank/sharktank/utils/testing.py
sharktank/tests/layers/linear_test.py
sharktank/tests/layers/mixture_of_experts_block_test.py
sharktank/tests/layers/sharded_paged_llama_attention_block_test.py
sharktank/tests/models/clip/clip_test.py
sharktank/tests/models/t5/t5_test.py

The recent fix https://github.com/nod-ai/shark-ai/pull/1662 was not enough to mitigate the problem.
This change removes all imports of `sharktank.utils.testing` form non-testing code by moving the functions `make_rand_torch` and `make_random_mask` to another location.

[sharktank] move functions out of utils.testing to avoid unwanted dependency on pytest

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-sharktank.yml
sharktank/sharktank/utils/testing.py
sharktank/tests/models/llama/benchmark_amdgpu_test.py

- 70B fp16 tp8 path seems to have changed
- Fixing unpassed `skip_decode` arg
- Split the 8B fp16 128 & 2048 tests apart so that only the input_len=128 is run on PRs and the 2048 is left for nightlies.

Fix Llama benchmark

---

sharktank/sharktank/utils/export_artifacts.py
sharktank/tests/evaluate/perplexity_iree_test.py

Needed because of: https://github.com/iree-org/iree/issues/21068.

Add extra iterations flag to Llama 405b and 70b perplexity tests

---

sharktank/conftest.py
sharktank/tests/evaluate/perplexity_iree_test.py
sharktank/tests/evaluate/perplexity_torch_test.py
sharktank/tests/models/clip/clip_test.py
sharktank/tests/models/deepseek/test_deepseek.py
sharktank/tests/models/deepseek/test_sharded.py
sharktank/tests/models/flux/flux_test.py
sharktank/tests/models/llama/benchmark_amdgpu_test.py
sharktank/tests/models/llama/sharded_llama_test.py
sharktank/tests/models/t5/t5_test.py
sharktank/tests/models/vae/vae_test.py
sharktank/tests/pipelines/flux/flux_pipeline_test.py
sharktank/tests/pytest_fixtures_test.py
sharktank/tests/utils/iree_test.py

Our fixture get_iree_flags works only on classes and not with individual tests. This causes a bunch of problems like not being able to xfail a parametrized test for particular parameter set. Because tests in unittest.TestCase are not compatible with pytest.param. parameterized.parameterized.expand is not compatible with pytest.mark.xfail.
Resolves https://github.com/nod-ai/shark-ai/issues/1708.
Rename fixtures
get_iree_flags -> iree_flags
get_model_artifacts -> model_artifacts

[sharktank] Make IREE flags pytest fixture work at function scope

---

sharktank/sharktank/models/llama/tools/import_quark_dataset.py

This changes:
- Output scales (output_scale)
- KV cache scales (kv_cache_scale)
- Attention/probability output scales (prob_output_scale/attn_scale)
- All norm layer weights
- Embedding and output weight

Add a flag for converting quark's non-matmul parameters to a provided flag

---

sharktuner/sharktuner/candidate_gen.py
sharktuner/sharktuner/dispatch_parser.py
sharktuner/tests/dispatch_parser_test.py

After https://github.com/iree-org/iree/pull/21170 and https://github.com/iree-org/iree/pull/21216 exposing python bindings from iree side, This PR adds parser for attention op.

[tuner] add parser for attention op

---

shortfin/python/shortfin_apps/llm/components/device_array_cache.py

When `device_cache` hits `_max_allocations`, we evict the overflowing items and rebuild the table and cache.
However, we were overwriting the local `key` variable unintentionally, which was causing weirdness down the road.
Eventually, our cache ended up in a state, where there was only a single key in `_cache`, that corresponded to ALL indices in `_table`, regardless of the shape of those indices.
In the specific test case, the last key in the table rebuild loop was 4x132. That meant that we returned a 4x132 allocation, regardless of the shape of the requested allocation.
When the allocation was returned, the incorrect `4x132` key is used (since that's the `Allocation's` key). Overtime, this led to ALL `device_arrays` being stored under said key.
This caused every other shape aside from …

Ensure `key` isn't overwritten, when we cleanup the device_cache

---

shortfin/python/shortfin_apps/llm/components/generate.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/base_token_selection_strategy.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/scorer.py
shortfin/python/shortfin_apps/llm/components/token_selection_strategy/token_selector.py
shortfin/tests/apps/llm/components/token_selection_strategy/token_selection_strategy_test.py

Streaming is basically non-functional for beam search. We should be ripping out support so that we can refactor processing layers.

Remove streaming from shortfin-llm

---

sharktank/sharktank/examples/paged_llm_v1.py
sharktank/sharktank/models/llama/toy_llama.py
sharktank/sharktank/utils/cli.py
sharktank/sharktank/utils/load_llm.py
sharktank/sharktank/utils/testing.py
sharktank/tests/examples/paged_llm_v1_test.py

We don't have tests for the script.
Expand functionality with
1. Use LlamaModelConfig.from_properties to parse config instead of just the GGUF properties.
2. Actually generate a random prompt with --prompt-seq-len.
3. Add max decode steps option.

[sharktank] Fix and add tests for running models in eager with  paged_llm_v1

---

sharktank/conftest.py
sharktank/sharktank/utils/testing.py
sharktank/tests/evaluate/perplexity_iree_test.py
sharktank/tests/models/deepseek/test_deepseek.py
sharktank/tests/models/llama/test_llama.py
sharktank/tests/models/punet/sharded_resnet_block_with_iree_test.py
sharktank/tests/ops/sharded_test.py
sharktank/tests/utils/testing_test.py

Instead of making a new decorator, extend the pytest.mark.xfail to support exception message matching. Like that it can be used in parametrized tests. E.g.
```
@pytest.mark.parametrize(
"a", [pytest.param(1, marks=pytest.mark.xfail(match="not a match"))]
)
def test_f(a: int):
raise ValueError("This is the exception")
```
This is achieved through the pytest hook mechanism.

[sharktank] Make our xfail a proper Pytest mark

---

sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/tensors.py

The troch.view op has dtype overload. This aligns our op API with torch.

[sharktank] make view op support dtype overload

---

sharktank/sharktank/layers/paged_attention.py
sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/utils/iree.py
sharktank/sharktank/utils/misc.py
sharktank/tests/ops/ops_test.py

PyTorch Eager CPU does not support index_copy_ and index_put_ for f8. Because of that we need to view as int8.
On the other had the IREE compiler can't fuse these bitcasts.
With this change we are taking different paths during export and eager, such that both limitations are circumvented.
The paged KV cache is adapted to just call `ops.index_copy/put_`.

[Sharktank] Do not bitcast f8->i8 for index_copy_ and index_put_ during export to help compiler fusion

---

shortfin/python/shortfin_apps/llm/components/config_struct.py
shortfin/python/shortfin_apps/llm/components/service.py
shortfin/python/shortfin_apps/llm/server.py

Why:
Worker and fiber are now created dynamically through FiberPool, there is no need to specify number of workers statically
How:
Remove  workers and fibers_per_worker from ServerParams class

Clean up parameters in server param

---

sharktank/sharktank/examples/export_paged_llm_v1.py

Remove hardcoded split for top-k=1. If `--top-k=1` is specified in the export, the dim size will not be a multiple of the chunk size: [command and full stack trace](https://gist.github.com/AmosLewis/ab3d8a5defe96ed79ee570dd22f486d2#file-llama_405b_fp4_pp1_export_bug-md)
```
ValueError: dim's size must be a multiple of chunk_size.
Dim Size: 2
Chunk Size: 1024
```
From my understanding, the compiler will do the split, so we do not need to manually split it in the sharktank export.

Remove hardcoded split for top-k=1

---

sharktank/sharktank/ops/default_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/types/tensors.py
sharktank/sharktank/utils/load_llm.py
sharktank/sharktank/utils/testing.py
sharktank/tests/layers/kv_cache_test.py
sharktank/tests/layers/sharded_paged_kv_cache_test.py
sharktank/tests/layers/sharded_paged_latent_attention_block_test.py
sharktank/tests/layers/sharded_paged_llama_attention_block_test.py
sharktank/tests/layers/sharded_rotary_embedding_test.py
sharktank/tests/models/punet/resnet_test.py
sharktank/tests/models/punet/up_down_block_test.py
sharktank/tests/ops/ops_test.py
sharktank/tests/ops/pipeline_parallelized_test.py
sharktank/tests/ops/sharded_test.py

- Change ops.cat to not unpack primitive tensors it receives.
- Change unshard to not unwrap all the way to torch.tensor. Especially important once we used sharded quantized tensors. This function should be dequantizing, it should just be unsharding.
- Test fixes by using assert_tensor_close.
- Change is_deep_equals to correctly use `compare_name`.

Change ops.unshard and ops.cat to not unwrap tensor

---

sharkfuser/CMakeLists.txt
sharkfuser/README.md
sharkfuser/build_tools/cmake/CTestCustom.cmake.in
sharkfuser/build_tools/cmake/CTestMacros.cmake
sharkfuser/samples/CMakeLists.txt
sharkfuser/tests/CMakeLists.txt

This is a non-functional change.
Noticed a weird behavior where logs were being suppressed for all tests, but working fine for samples. After some digging into, it turns out they were clubbed into a single `sharkfuser_tests` target and among them there was the `test_logging.cpp` which had manual overrides on logging behavior, affecting other tests as well. 
In general I'd been meaning to split the tests into logical targets to help with debugging, so here it is. 
We now have:
```cmake
add_sharkfuser_test(
NAME sharkfuser_attribute_tests
SRCS
test_attributes.cpp
test_tensor_attributes.cpp
test_conv_attributes.cpp
)
add_sharkfuser_test(
NAME sharkfuser_tensor_tests
SRCS
test_tensor.cpp
)
add_sharkfuser_test(
NAME sharkfuser_node_tests
SRCS
test_conv_node.cpp
)
add_sharkfuser_test(
NAME …
```

[Fusili][NFC] Split test targets for better debuggability/logging

---

sharktank/sharktank/types/tensors.py

1. Need to create a copy of the dict since we're mutating it
2. Create for `UnreducedTensor` is incorrect since it passes a `shard_dim` argument, which `UnredicedTensor.__init__` doesn't take

Minor fixes for _clone_with_subtensors

---

.github/workflows/ci-sharkfuser.yml
sharkfuser/CMakeLists.txt
sharkfuser/README.md
sharkfuser/build_tools/cmake/CTestCustom.cmake.in
sharkfuser/build_tools/cmake/CTestMacros.cmake
sharkfuser/build_tools/cmake/strip_codecov_files.cmake
sharkfuser/tests/CMakeLists.txt
sharkfuser/tests/example_lit_test.cpp
sharkfuser/tests/lit.cfg.py

This PR sets up `lit` + `FileCheck` tests for MLIR asm emitter. `lit` + `FileCheck`  are a well known and battle tested formula for testing MLIR asm, this approach should minimize fiddling with exact string matches.

[Fusili] Test harness for MLIR asm emitter

---

sharktuner/sharktuner/candidate_gen.py
sharktuner/sharktuner/common.py
sharktuner/sharktuner/constraint_generator.py
sharktuner/sharktuner/dispatch_constraints.py
sharktuner/tests/constraint_generator_test.py
sharktuner/tests/dispatch_constraints_test.py

This PR adds initial support for the attention op in the SHARK Tuner.
- Currently supports only the standard attention op, masked attention is not yet handled.
- only about `VectorDistribute `pipeline. 
Attention constraints largely are about two matmul-like patterns along the `VectorDistribute `pipeline.
This PR is implemented mainly through understanding and following the logic of `setAttentionIntrinsicBasedVectorDistributionConfig` from IREE for attention op. 
This PR primarily focuses on adding tuner support for the attention op. It introduces some code redundancy, which I plan to address in a follow-up NFC PR by simplifying and better modularizing the code.
Issue: https://github.com/nod-ai/shark-ai/issues/1769

[tuner] add support for attention op

---

sharkfuser/CMakeLists.txt
sharkfuser/build_tools/cmake/SharkfuserUtils.cmake
sharkfuser/include/fusili.h
sharkfuser/include/fusili/external_tools.h
sharkfuser/templates/external_tools.h.in
sharkfuser/tests/CMakeLists.txt

This is NFC, but (assuming it merges) establishes the pattern we'll use to bring in `iree-compile` for a subprocess call in C++.

[Fusili] Boilerplate to bring in `iree-compile` for subprocess call

---

shortfin/python/shortfin_apps/llm/components/kvcache/base_attention_cache.py

Ensure KVCache OOM (page exhaustion) failure is properly logged when it occurs server-side.
Will do a follow up to close the client connection, instead of just leaving it hanging.
For now, this will at least make the error obvious server-side.
Output example:
```bash
[2025-07-28 15:21:47.187] [error] [base_attention_cache.py:182] FATAL CacheAllocationFailure: Failed to allocate 6 pages from `PagePool`.
Required pages: 6, Available pages: 2, Total pages: 2
Consider re-exporting the model with a higher `--device-block-count` value.
```

Ensure error message is properly logged when `kvcache OOM` occurs

---

shortfin/python/shortfin_apps/llm/components/tokenizer.py

Fix of the shortfin repeatable issue in case of longer prompts:
- It was due to truncation of the prompt at tokenizer side. 
- Added no_truncation call for now, if require, we can add higher number truncation or directly pass user given seq_length as truncation number - Need to discuss before finalizing the code.

Fix for the repeatable response due to truncation of prompt

---

sharktuner/sharktuner/candidate_gen.py
sharktuner/sharktuner/common.py
sharktuner/sharktuner/constraint_generator.py
sharktuner/sharktuner/dispatch_constraints.py
sharktuner/tests/dispatch_constraints_test.py
sharktuner/tests/dispatch_parser_test.py

This PR enhances the tuner’s support for the Attention operation by building on the constraint generation logic (mainly about layout matching, searching two mmas independently) introduced in https://github.com/iree-org/iree/pull/21448. 
- Adds the layout matching constraints based on the python binding exposed from https://github.com/iree-org/iree/pull/21454
- Extends the tuner to handle virtual MMA intrinsics according to python binding exposed from https://github.com/iree-org/iree/pull/21403
For reference, the attached log link demonstrates tuning runs for the Attention op using this PR.: https://gist.github.com/bangtianliu/ce6b925a679a2072b2ceba1bfdfe094c. 
Issue: #1769

[tuner] improve support for attention op

---

sharktank/conftest.py
sharktank/sharktank/layers/causal_llm.py
sharktank/sharktank/types/ocp_floats.py
sharktank/sharktank/utils/misc.py

Use custom device comparison to circumvent the fact that `cuda` and `cuda:0` are considered different devices.
Make cpu the default test torch device.

[sharktank] Improve non-default torch device placement

---

sharktank/sharktank/ops/custom_impls.py
sharktank/sharktank/types/quantizers.py
sharktank/sharktank/utils/misc.py
sharktank/sharktank/utils/testing.py
sharktank/tests/ops/quantized_test.py

The wave_mxfp4_bmm kernel works only for some AMD GPU architectures.
```
error: 'amdgpu.scaled_mfma' op scaled MFMA only supported on gfx908+
```
It is also desirable to have eager execution path that does not depend on IREE. This would allow us to have a simple reference implementation that we can test against.
In eager we dequantize the arguments and run a "normal" matmul.

[sharktank] In eager do not use kernel for fp4 matmul

---

sharktank/sharktank/models/llama/tools/import_quark_dataset.py
sharktank/sharktank/ops/custom_impls.py
sharktank/sharktank/ops/quantized_impls.py
sharktank/sharktank/types/layouts.py
sharktank/sharktank/types/ocp_floats.py
sharktank/sharktank/types/quantizers.py
sharktank/tests/ops/ops_test.py
sharktank/tests/types/layouts_test.py
sharktank/tests/types/quantizers_test.py

To align BlockScaledFp4Layout with the base class BlockScaledLayout make the per-block scale tensor have a shape blocked_shape + [1]. Fixes https://github.com/nod-ai/shark-ai/issues/1833.
This change breaks existing IRPA files that hold FP4 quantized tensors. They will need to be regenerated.

[sharktank] make fp4 block-quantized have scales with trailing singleton dimension

---

sharktank/sharktank/layers/conv.py
sharktank/sharktank/layers/linear.py
sharktank/sharktank/layers/paged_attention.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/punet/layers.py
sharktank/sharktank/ops/quantized_impls.py
sharktank/sharktank/ops/sharded_impls.py
sharktank/sharktank/ops/signatures.py
sharktank/sharktank/types/pipelining.py
sharktank/sharktank/types/quantizers.py
sharktank/sharktank/types/tensors.py
sharktank/tests/types/quantizers_test.py

In order to avoid proliferating quantizer types like for split and replicated sharded tensors, QuantizerTensor.quantize and descendants are implemented as an op utilizing the dispatch mechanism.

[sharktank] make quantize a proper op with multiple dispatch

---

requirements-iree-pinned.txt
requirements-iree-unpinned.txt
sharktank/sharktank/kernels/wave/attention.py
sharktank/sharktank/kernels/wave/mxfp4_gemm.py

Wave was migrated from the `iree-turbine` package to `wave-lang`.
See https://github.com/iree-org/wave

Update Wave dependency to `wave-lang` from `iree-turbine`

---

sharktank/sharktank/ops/__init__.py
sharktank/sharktank/ops/cpu_impls.py
sharktank/sharktank/ops/default_impls.py
sharktank/tests/ops/ops_test.py

In eager mode on the CPU device we need to reinterpret to int8 as torch.cat has no implementation for float8_e4m3fn and float8_e4m3fnuz.

[sharktank] make cat work with f8 eager CPU

---

.github/workflows/ci-llama-large-tests.yaml
.github/workflows/ci-llama-quick-tests.yaml
.github/workflows/ci-sharktank-nightly.yml
.github/workflows/ci-sharktank.yml
.github/workflows/ci_eval_short.yaml
build_tools/torch_rocm_version_map.py
docs/shortfin/llm/user/llama_serving.md
sharktank/build_tools/install_test_dependencies.sh
sharktank/requirements.txt
sharktank/tests/evaluate/perplexity_iree_test.py
sharktank/tests/evaluate/perplexity_torch_test.py
sharktank/tests/models/llama4/llama4_test.py
sharktank/tests/models/t5/t5_test.py

- bump torch to 2.6.0 and then to 2.7.1 in upcoming weeks
- needed for failing T5 encoder tests against Hugging Face due model loading vulnerability fix.

Add CI tests against torch version 2.6.0 and remove for 2.4.1

---

sharktank/sharktank/examples/export_paged_llm_v1.py

The code generation for scatter that assumes an upper bound to the number of pages is producing illegal results.

Disable number of page restriction

---

sharktank/conftest.py
sharktank/sharktank/ops/quantized_impls.py
sharktank/sharktank/utils/testing.py
sharktank/tests/kernels/wave/mxfp4_gemm_test.py

Fix the RHS transpose as the kernel does `A x B^T` rather than `A x B`.
During quantization don't take a view, but rashape as the tensor may have layout that can't be reshaped without copying.
Refactor the test to include different matrix sizes and make sure m != n != k.

[sharktank] fix test for wave fp4 gemm kernel

---

sharktank/sharktank/models/llm/export.py

Dropping the options dimensions treats top-k and argmax in a different way at the service side. This is unnecessary as there is no special casing required between the two.

Argmax export should not drop the options dimension

---

app_tests/integration_tests/llm/shortfin/tinystories_llama2_25m_test.py
shortfin/python/shortfin_apps/llm/components/config_struct.py
shortfin/python/shortfin_apps/llm/components/decoder/decoder.py
shortfin/python/shortfin_apps/llm/server.py

We should only be performing beam search with multiple hypothesis cases. Removed the corresponding tests and enabled the new decoder. Some fixes to the page manager work better for non topk.

Enable new decoder - remove multigreedy case

---

shortfin/python/shortfin_apps/llm/components/decoder/decoder.py
shortfin/python/shortfin_apps/llm/components/scheduler.py
shortfin/python/shortfin_apps/llm/components/tokenizer.py
shortfin/tests/apps/llm/components/tokenizer_test.py

Needed to remove padding for batch encode. Encoding does not include the sequence length for batch encoding so this would result in end paddings of the sequence.
Also - if the first token encountered was a EOS token then stepping would fail. Reworked initialization / errors to better handle this and have a uniform stepping location of page ids.

Handle prefill EOT and remove tokenizer padding

---

sharktank/sharktank/tools/bench_llm_vmfb.py
sharktank/sharktank/utils/llm_utils.py

Perform a simulated benchmark with a VMFB with a fixed context length and step count. This can be used to roughly estimate the throughput of a given export model.

Add a raw benchmark utility

---

shortfin/python/shortfin_apps/llm/components/messages.py
shortfin/tests/apps/llm/components/batcher_test.py
shortfin/tests/apps/llm/components/invocation_test.py
shortfin/tests/apps/llm/components/messages_test.py

LLM Exec request contained unused cruft including copying and status tracker types.

Remove unused cruft from exec request

---

shortfin/python/shortfin_apps/llm/components/batcher.py
shortfin/python/shortfin_apps/llm/components/decoder/decoder.py
shortfin/python/shortfin_apps/llm/components/invocation.py

1. Rewire batcher.py so that the page_cache no longer allocates in the batcher and instead perform the allocation in decoder.py. 
2. Removing the publish pages function so it occurs post prefill and post all decode steps

Move allocate_cache from btacher.py to decoder.py

---

sharktank/sharktank/tools/run_llm_vmfb.py
sharktank/sharktank/utils/llm_utils.py

Specifying kv-cache-dtype helps in running fp8 based models using run_llm_vmfb

Add kvcache dtype option to run_llm_vmfb

---

requirements-iree-pinned.txt
sharktank/sharktank/kernels/templates/batch_matmul_transpose_b.mlir
sharktank/sharktank/kernels/templates/mmtfp_2d.mlir
sharktank/sharktank/kernels/templates/mmtfp_3d.mlir
sharktank/tests/kernels/batch_matmul_transpose_b_test.py
sharktuner/model_tuner/double_mmt.mlir
shortfin/CMakeLists.txt
shortfin/src/shortfin/local/scheduler.cc

Interface changes in [IREE-21619](https://github.com/iree-org/iree/pull/21619), which require a small update in the shortfin code.
In that PR, @benvanik states that "Behavior is defaulted to what it is today before these additions...", so I followed what seemed to be the default flags throughout that PR to maintain current behavior (i.e. [here](https://github.com/iree-org/iree/pull/21619/files#diff-289c6144e8b6d353bc4e1dba6a206d8b2da145ffa66f5e659cf1b6c2345103cfR386)).
Could use a double-check to make sure that this is in fact maintaining current behavior on the `shortfin` side.
Also includes @vivekkhandelwal1's changes to fix the `matmul_transpose` op, merged from #2055

Bump iree to `3.7.0rc20250822` and kernels for matmul_transpose change

---

shortfin/python/shortfin_apps/llm/components/generate.py

removes serialization when return_input_ids is True. This is required so that input_ids are directly available without serialization and deserialization in mlperf harness.

removes serialization when return_input_ids is True

---

sharktank/sharktank/evaluate/perplexity_iree.py
sharktank/sharktank/utils/export_artifacts.py

This PR finishes plumbing through `--matmul-kernel` argument, so that we can run PPL using either assembly or sharktank fp4 matmul kernels. The argument needs to be in quotes, which is why I added them to the CLI argument.
Ex:
```
python -m sharktank.evaluate.perplexity_iree \
--irpa-file=/shark-dev/llama3.1/405b/instruct/weights/fp4/fp4_2025_07_10_fn.irpa \
--tokenizer-config-json=/shark-dev/llama3.1/405b/instruct/weights/fp4/tokenizer_config.json    \
--iree-device='hip://4'     \
--iree-hal-target-device=hip     \
--iree-hip-target=gfx950     \
--num-prompts=4     \
--verbose     \
--attention-dtype=float16     \
--activation-dtype=float16     \
--attention-kernel=torch     \
--kv-cache-dtype=float16     \
--use-hf \
--matmul-kernel="sharktank.asm;*"
```

Finish plumbing matmul-kernel arg through perplexity_iree.py

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/export_layer/export_paged_attention.py
sharktank/sharktank/layers/__init__.py
sharktank/sharktank/layers/paged_attention.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/llm/export.py
sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/utils/load_llm.py

Instead of plumbing through a list of tensors everywhere, use a small object. No functionality changes for now, just initial signature changes.

Replace KVCache list of tensors with simple CacheAllocation wrapper object

---

sharktank/sharktank/kernels/wave/mxfp4_gemm.py

Adds the Wave gemm optimizations of SchedulingType.PREFETCH and updates the WaveCompileOptions to use `use_buffer_load_ops=True` and `waves_per_eu=2`.

Add Wave gemm optimizations

---

sharktank/sharktank/examples/export_paged_llm_v1.py
sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/layers/paged_attention.py

Adds a default attention type, allows searching for config values in the absence of a model name. This isn't extensible to having defaults for these parameters though.
Also modifies export script to take model class as a func argument

[Sharktank] Add some external model support

---

sharktuner/sharktuner/dispatch_constraints.py

This PR is mainly sync with the change from https://github.com/iree-org/iree/pull/21729, adding acc layout matching constraint to tuner.
Here is the link to the tuner log based on this PR: https://gist.github.com/bangtianliu/2450e15526f4d4d1b7b5815af918c856

[tuner] add acc layout match to constraint generation for attention

---

sharktank/sharktank/layers/causal_llm.py
sharktank/sharktank/utils/attention.py
sharktank/sharktank/utils/llm_utils.py

The helper methods inside BaseCausalLMModel are being moved outside as proper helper functions. This particularly important for the attention mask related ones as the refactor is necessary in order to move the creation of the masks into the attention layer.

[Sharktank] Move implementation of helper functions out of BaseCausalLMModel

---

sharktank/sharktank/ops/attention_impls.py
sharktank/tests/kernels/attention_template_test.py

Currently "sharktank" is the default attention implementation, but this has the problem that it unconditionally always returns a f32 tensor. This diverges from the semantics of the torch operation, where the return dtype is dependent on the operands' dtypes.
It is strongly desirable for the default to do as torch does as it has a well documented behaviour. In general we should try hard for our defaults to not diverge from torch's semantics as this will cause confusion when porting models in the future. This actually already caused a problem with the Flux transformer, where downstream ops after attention would be in f32 instead of the desired bf32.
The change here relies on the resolution order of overrides, if no impl is specified then "torch" will be picked before "sharktank".

[sharktank] Make torch SDPA the default attention implementation

---

sharktank/sharktank/evaluate/perplexity_iree.py
sharktank/sharktank/evaluate/perplexity_torch.py
sharktank/sharktank/examples/validate_paged_llama_model.py
sharktank/sharktank/export_layer/export_paged_attention.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/llm/export.py
sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/models/llm/testing.py
sharktank/sharktank/utils/create_cache.py
sharktank/sharktank/utils/llm_utils.py
sharktank/sharktank/utils/load_llm.py
sharktank/tests/layers/paged_llama_attention_block_test.py
sharktank/tests/models/grok/test_grok.py
sharktank/tests/models/llama/attention_test.py
sharktank/tests/models/llama/test_llama.py
sharktank/tests/models/llama4/llama4_test.py

**Background:** The KVCache and PagedAttention objects do not hold onto the actual KVCache state.
Change how the PagedAttentionLayer is created so that each has their own distinct PagedAttention (and thus KVCache) object, so that we can add per-layer info (e.g. the kv quantizers) into the KVCache rather than pass them as args around.

[Sharktank] Replumb PagedAttention to have their own KVCache object

---

sharktank/sharktank/utils/testing.py

Currently when the assert fails we print just diff (actual - expected) statistics, but for the error (diff) it is more meaningful what is the absolute.
It is also informative to know the statistics of the expected. For example the diff looses magnitude information, which is important when judging the deviation.

[sharktank] in assert_tensor_close print abs diff and expected stats

---

requirements-iree-pinned.txt
shortfin/CMakeLists.txt

Runtime is pinned to a problematic iree pin with a nondeterministic loading issue. Bumping to the most recent pin should fix the nondeterminism issue.

Bump iree pin on shortfin runtime build to iree-3.7.0rc20250828

---

sharktank/sharktank/examples/validate_paged_llama_model.py
sharktank/sharktank/export_layer/export_kv_cache.py
sharktank/sharktank/export_layer/export_paged_attention.py
sharktank/sharktank/layers/latent_attention_block.py
sharktank/sharktank/layers/paged_attention.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/llm/export.py
sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/models/llm/testing.py
sharktank/sharktank/utils/create_cache.py
sharktank/sharktank/utils/llm_utils.py
sharktank/sharktank/utils/load_llm.py
sharktank/tests/layers/kv_cache_test.py
sharktank/tests/layers/paged_llama_attention_block_test.py
sharktank/tests/models/grok/test_grok.py
sharktank/tests/models/llama/attention_test.py
sharktank/tests/models/llama/test_llama.py
sharktank/tests/models/llama4/llama4_test.py

Instead of creating the masks outside of the model, passing them around, and relying on IREE to fuse them for us, this PR changes it so that each mask is created right before being used. This will make it easier to fuse down the line and requires less state to be passed around.

[Sharktank] Replumb Attention and embedding masks

---

sharktuner/model_tuner/model_tuner.py
sharktuner/sharktuner/libtuner.py

Make `candidate_trackers` an internal field of `TuningClient` so callers don’t have to pass it around.

[Tuner] Put candidate_trackers inside TuningClient

---

sharktank/sharktank/export_layer/export_kv_cache.py
sharktank/sharktank/layers/__init__.py
sharktank/sharktank/layers/paged_attention.py
sharktank/sharktank/layers/paged_llama_attention_block.py
sharktank/sharktank/models/llm/llm.py
sharktank/sharktank/utils/create_cache.py
sharktank/tests/layers/kv_cache_test.py
sharktank/tests/layers/paged_llama_attention_block_test.py
sharktank/tests/models/llama/attention_test.py

- Move the K and Q quantizers out of the KVCache and into the per-layer PagedAttention instance.
- Change back to using a single KVCache instance for the whole model.

[Sharktank] KV Quantizer replumb and KVCache revert

---

shortfin/python/shortfin_apps/utils.py

**Fix Issue below:**
_Run command:
export HIP_VISIBLE_DEVICES=0
export ROCR_VISIBLE_DEVICES=4
export PYTHONPATH=$(pwd)/shortfin/python
python3 -m shortfin_apps.llm.cli  --device hip  --tokenizer_json=/shark-dev/llama3.1/405b/instruct/weights/fp4/tokenizer.json  --model_config=/sharedfile/f4/2500/405b/pp1/out/f4_bs4_ds4.iree0905.shark0905_dfc.json  --vmfb=/sharedfile/f4/2500/405b/pp1/out/f4_bs4_ds4.iree0905.shark0905_dfc.vmfb  --parameters $IRPA_PATH  --benchmark  --benchmark_tasks=4  --device_ids 0  --input_token_length 128  --decode_steps=1  --workers_offline=4_
**Error:**
File "/home/chiliu12/src/shark-ai/shortfin/python/shortfin_apps/utils.py", line 518, in create_program return sf.Program( ^^^^^^^^^^^ TypeError: __new__(): incompatible function arguments. The following argument types …

Fix initialize_program_modules

---

sharktank/sharktank/layers/paged_attention.py

Per [this suggestion](https://github.com/nod-ai/shark-ai/issues/2247#issuecomment-3293041131) from @Alex-Vasile:
Fixes #2247, `pipeline-parallelism + --has-prefill-position` export by changing `torch.gather` -> `ops.gather`

Fix export w/ `pipeline-parallelism` and `has-prefill-position`

---

shortfin/python/shortfin_apps/llm/components/lifecycle.py
shortfin/python/shortfin_apps/llm/server.py

Since I was defaulting the server cli value to `8`, we were chunking when we weren't wanting to.
However, this and #2221 does not seem to be the cause of #2279. 
I was able to download the dataset being used in the mlperf harness, run a local shortfin 8b server, and checkout #2250 locally (one before), and am seeing the same reported bug:
```bash
:0:rocdevice.cpp            :2991: 123228313452 us:  Callback: Queue 0x7fa575000000 aborting with error : HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION: The agent attempted to access memory beyond the largest legal address. code: 0x29
```

Llm fix unintended chunking

---

.github/workflows/ci-sharkfuser.yml
sharkfuser/build_tools/cmake/FusilliTestUtils.cmake

Remove the ctest timeout from the CMake target and update the ctest command in GHA workflow instead, since local runs shouldn't need a timeout.

[Fusilli] CI timeout fixes

---

fusilli-plugin/build_tools/cmake/FusilliPluginDependencyUtils.cmake

This PR adds a convenience feature for development. When switching between `hipDNN` code and `fusilli-plugin` code it's nice to have one location for sources.

[FusilliPlugin] Add local build option for `hipDNN`

---

sharktank/sharktank/layers/configs/llm_configs.py
sharktank/sharktank/models/deepseek/toy_deepseek.py
sharktank/sharktank/models/grok/toy_grok.py
sharktank/sharktank/models/llama/toy_llama.py

We can identify that the IRPA source was GGUF which allows us to default to interleave rotary embedding.

Tweak gguf default for rotary embedding format

---

sharkfuser/tests/CMakeLists.txt
sharkfuser/tests/lit/test_conv_asm_emitter_nchw_kcrs.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nchw_kcrs_with_pad.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nchw_krsc.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nhwc_kcrs.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nhwc_krsc.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nhwc_krsc_with_pad.cpp

This includes the problematic case of `T -> Pad -> Conv -> T` which iree-compile doesn't optimize well today. Will update the lit test once the compiler pass is available. 
Also removes unnecessary checks from linalg input IR to make them less fragile. Eventually we'll want to clean them up further and possibly relocate to the IREE repo.

[Fusilli] Add lit tests with padding

---

.github/workflows/ci-fusilli-plugin.yml
.github/workflows/ci-sharkfuser.yml
sharkfuser/CMakeLists.txt
sharkfuser/README.md
sharkfuser/build_tools/cmake/FusilliTestUtils.cmake
sharkfuser/include/fusilli/attributes/tensor_attributes.h
sharkfuser/include/fusilli/graph/graph.h
sharkfuser/samples/convolution/conv_fprop_nchw_kcrs.cpp
sharkfuser/samples/convolution/conv_fprop_nhwc_krsc.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nchw_kcrs.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nchw_kcrs_with_pad.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nchw_krsc.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nhwc_kcrs.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nhwc_krsc.cpp
sharkfuser/tests/lit/test_conv_asm_emitter_nhwc_krsc_with_pad.cpp

There is a bug in this code which caused the release builds to never be exercised before:
```cmake
if(FUSILLI_DEBUG_BUILD OR FUSILLI_CODE_COVERAGE)
message(STATUS "Setting CMAKE_BUILD_TYPE to Debug")
set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Debug build" FORCE)
endif()
```
When `-DFUSILLI_DEBUG_BUILD=OFF` (and `-DFUSILLI_CODE_COVERAGE=OFF`), the `CMAKE_BUILD_TYPE` is left unset. If not, it is set to `Debug`. So it is never being set to `Release`.
We probably want something like this:
```cmake
if(NOT CMAKE_BUILD_TYPE)
message(STATUS "Setting CMAKE_BUILD_TYPE to Release")
set(CMAKE_BUILD_TYPE Release CACHE STRING "Release build" FORCE)
endif()
if(FUSILLI_CODE_COVERAGE)
message(STATUS "Setting CMAKE_BUILD_TYPE to Debug")
set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Debug build" FORCE)
endif() …
```

[Fusilli] Fix release builds and refactor cmake flags

---

sharkfuser/include/fusilli/support/logging.h

In release builds the assert + error message on bad `ErrorOr<T>` access is compiled out, the reported error message is rather cryptic. 
```
/home/srajeshk/code/shark-ai/sharkfuser/build/bin/lit/test_conv_asm_emitter_nhwc_krsc_with_pad | iree-opt --verify-roundtrip
```
This PR moves from assert for crash + error reporting to an if check, which will not be compiled out. The above error message becomes:
```
/home/astgeorg/Dev/python/shark-ai/sharkfuser/build/bin/lit/test_conv_asm_emitter_nhwc_kcrs | iree-opt --verify-roundtrip
```

[Fusilli] Improve error reporting

---

sharktank/sharktank/tools/list_safetensors.py
sharktank/tests/tools/list_sfaetensors_test.py

This tool helps explore tensors in a safetensors file. E.g.
```
python -m sharktank.tools.list_safetensors --show-metadata some.safetensors
```
```
tensor1: shape=[1, 2], dtype=torch.float32
tensor2: shape=[3, 4, 5], dtype=torch.int32
```

[sharktank] Add tool to print the keys/names and metadata of tensors in a safetensors file

---

.github/workflows/ci-fusilli-plugin.yml
.github/workflows/ci-libshortfin.yml
.github/workflows/ci-sharkfuser.yml
.github/workflows/ci-sharktank.yml

The intention is to stop running sharktank, sharkfuser/fusilli, and shortfin CI checks on sharktuner pull requests.
Tuner changes should never affect the other projects.

[CI] Run fewer pull_rquest checks on unrelated changes

---

sharktank/sharktank/ops/quantized_impls.py
sharktank/tests/ops/quantized_test.py

Currently it supports only transferring to another torch.device.
Changing to a single dtype maybe does not make sense in the general case. There may be certain expectations about the dtypes of the tensor planes.

[sharktank] Add ops.to for PlanarQuantizedTensor

---

.github/workflows/ci-fusilli-plugin.yml
.github/workflows/ci-libshortfin.yml
.github/workflows/ci-sharkfuser.yml
.github/workflows/ci-sharktank.yml

Reverts nod-ai/shark-ai#2367
This is causing a deadlock on all PRs (https://github.com/nod-ai/shark-ai/pull/2359, https://github.com/nod-ai/shark-ai/pull/2381) as the disabled checks are actually "required" in status checks.

Revert "[CI] Run fewer pull_rquest checks on unrelated changes"

---

sharktank/sharktank/utils/llm_artifacts.py
sharktank/sharktank/utils/llm_utils.py

Although these two classes do not inherit an ABC explicitly now, they need to have the same interface.

[sharktank] make IreeInstance expose LlamaModelConfig to be consistent with TorchInstance

---

shortfin/python/shortfin_apps/llm/server.py

- Update `help` message for `--chunk_block_size`, since we don't use `--use_chunked` arg anymore

[LLM Server] Update help message for `--chunk_block_size`

---

.github/workflows/ci-fusilli-plugin.yml
.github/workflows/ci-sharkfuser.yml
sharkfuser/build_tools/docker/exec_docker_ci.sh

The docker bump makes it so that clang-20 is the default even for local dev, to keep things in sync with CI.

[Fusilli] Switch GPU builds to clang-20 in CI

---

.github/workflows/ci-fusilli-plugin.yml
sharkfuser/CMakeLists.txt
sharkfuser/benchmarks/CMakeLists.txt
sharkfuser/benchmarks/driver.cpp
sharkfuser/build_tools/cmake/FusilliTestUtils.cmake

Adds a master benchmark driver (with CLI11 for arg parsing) that supports subcommands for benchmarking different ops (with different set of flags). Also adds CMake support to easily add benchmark suites to CI. 
Example invocation:
```
./driver conv -n 128 -c 384 -H 24 -W 48 -k 384 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 
```
(in the future)
```
./driver sdpa <flags>
```
In a follow-on (2/N...), I'll add:

[Fusilli] Benchmark Driver 1/N

---

sharktank/sharktank/layers/configs/llm_configs.py

Clarified the state of LlamaHParams and added some light design suggestion for future extension.

Update design comments in LlamaHParams

---

sharkfuser/include/fusilli/graph/graph.h
sharkfuser/include/fusilli/node/conv_node.h
sharkfuser/include/fusilli/node/node.h

These methods don't need to be virtual since they are only used internally by the class by `emitNodePreAsm()`/`emitNodePostAsm()` which makes them helpers vs being part of the Node interface.

[fusilli] Make asm helpers non-virtual

---

sharktank/sharktank/tools/import_hf_dataset_from_hub.py
sharktank/sharktank/utils/hf.py
sharktank/sharktank/utils/hf_datasets.py
sharktank/tests/models/llama/test_llama.py

Add registry for import presets and populate it with Llama 3.1 f16 models.
Add support for referencing a HF dataset during import. This decouples specification of what needs to be downloaded versus how to import the dataset after it is download.
Expand the HF datasets to specify the model files not completely explicitly, but by using filters like `huggingface_hub.snapshot_download`.
Next steps are:
1. Make the CI use this new mechanism.
2. Add importation of models with more complicated transformations like quantization.

[sharktank] Llama 3.1 f16 HF import presets

---

.github/workflows/ci-fusilli-plugin.yml
fusilli-plugin/build_tools/cmake/FusilliPluginDependencyUtils.cmake
sharkfuser/CMakeLists.txt

This PR fixes `fusilli-plugin` build failure when fusilli benchmarking (`FUSILLI_BUILD_BENCHMARKS`) was enabled, but fusilli testing (`FUSILLI_BUILD_TESTS`) was disabled: [link to CI failure](https://github.com/nod-ai/shark-ai/actions/runs/18206945208/job/51839515287?pr=2410). Both _should_ be disabled, but ideally the build wouldn't break if one wasn't.  The issue was: both fusilli tests and fusilli benchmarks depend on `libutils`, but the target was only defined if tests were enabled.

[Fusilli,FusilliPlugin] Fix missing `utils.h` in `fusilli-plugin` build.
